// Qud Lab mod workspace — references Caves of Qud Managed assemblies from your install.
// Do not commit game DLLs. HintPaths are generated by: qudlab sync-refs
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("QudLab.ModWorkspace.Tests")]