#!/usr/bin/env python3
"""Scaffold idle tile animations for Broodmother unique PNG broodlings.

Uses AAMT Pixelorama host helpers (scaffold/pack) — no .pxo required.
Installs numbered frames into the mod Textures tree and prints XML merges
for AnimatedMaterialGeneric TileAnimationFrames.

  python produce_broodling_tile_anims.py
  python produce_broodling_tile_anims.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

_TOOLS = Path(__file__).resolve().parent
_SHARED = _TOOLS.parent / "Shared"
if str(_SHARED) not in sys.path:
    sys.path.insert(0, str(_SHARED))

from pixelorama_client import scaffold_from_still  # noqa: E402

DEFAULT_MOD = Path(
    r"C:\Users\Arend\AppData\LocalLow\Freehold Games\CavesOfQud\Mods\Broodmother Mutation"
)

# Unique truecolor tiles that should idle-animate (not vanilla BMP stand-ins).
FLYERS = {
    "BroodlingSwarmling_T2",
    "BroodlingPrismfly_T3",
    "BroodlingGlowling_T2",
    "sw_broodling_flying_tile",
    "sw_broodling_flying",
}


def _style_for(stem: str) -> str:
    if stem in FLYERS or "fly" in stem.lower() or "swarm" in stem.lower():
        return "flutter"
    if any(x in stem for x in ("Flux", "Crystal", "Shard", "Neon", "Glow", "Mind")):
        return "pulse"
    return "bob"


def list_stills(creatures: Path) -> List[Path]:
    out: List[Path] = []
    # Leftover art with no ObjectBlueprint (Death-Dacca is Augerling_T5).
    skip = {"BroodlingDaccling_T7"}
    for p in sorted(creatures.glob("Broodling*.png")):
        # Skip already-numbered animation frames
        if p.stem.rsplit("_", 1)[-1].isdigit() and len(p.stem.rsplit("_", 1)[-1]) <= 3:
            # BroodlingX_1.png style — skip; BroodlingX_T3.png keep
            tail = p.stem.rsplit("_", 1)[-1]
            if tail.isdigit() and not tail.startswith("T"):
                continue
        if p.stem in skip:
            continue
        out.append(p)
    for name in ("sw_broodling_ground_tile.png", "sw_broodling_flying_tile.png"):
        p = creatures / name
        if p.is_file():
            out.append(p)
    return out


def install_frames(
    scaffold: Dict,
    creatures: Path,
    mirror: Optional[Path],
    stem: str,
    still: Optional[Path] = None,
) -> List[Path]:
    installed: List[Path] = []
    for i, src in enumerate(scaffold.get("frames") or [], start=1):
        dest_name = f"{stem}_{i}.png"
        dest = creatures / dest_name
        # Frame 1 must be byte-identical to the still so spawn → first anim tick does not flash.
        if i == 1 and still is not None and Path(still).is_file():
            shutil.copy2(still, dest)
        else:
            shutil.copy2(src, dest)
        installed.append(dest)
        if mirror and mirror.is_dir():
            shutil.copy2(dest, mirror / dest_name)
    return installed


def anim_xml_snippet(blueprint: str, stem: str, n: int, length: int = 80) -> str:
    step = max(1, length // max(1, n))
    frames = ",".join(f"{i * step}=Creatures/{stem}_{i + 1}.png" for i in range(n))
    # Truecolor: ASCII ColorString pulse only — do not pulse TileColor.
    return (
        f'  <object Name="{blueprint}" Load="Merge">\n'
        f'    <part Name="AnimatedMaterialGeneric"\n'
        f'          AnimationLength="{step * n}"\n'
        f'          LowFrameOffset="1"\n'
        f'          HighFrameOffset="1"\n'
        f'          TileAnimationFrames="{frames}" />\n'
        f"  </object>\n"
    )


def blueprint_for_stem(stem: str) -> str:
    # BroodlingStinger_T3.png → BroodlingStinger_T3
    if stem.startswith("sw_"):
        return stem  # generic; caller may skip XML
    return stem


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Broodling PNG → idle TileAnimationFrames")
    ap.add_argument("--mod", type=Path, default=DEFAULT_MOD)
    ap.add_argument("--frames", type=int, default=4)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument(
        "--write-xml",
        action="store_true",
        help="emit ObjectBlueprints_TileAnims.xml (prefer merging into ObjectBlueprints_Animations.xml)",
    )
    args = ap.parse_args(argv)

    mod: Path = args.mod
    creatures = mod / "Textures" / "Creatures"
    mirror = mod / "Assets" / "Resources" / "Textures" / "Creatures"
    work = mod / "DesignDrafts" / "pixelorama"
    work.mkdir(parents=True, exist_ok=True)

    stills = list_stills(creatures)
    if not stills:
        print(f"No Broodling*.png in {creatures}")
        return 1

    xml_parts: List[str] = [
        '<?xml version="1.0" encoding="utf-8"?>\n',
        "<!-- Auto: idle TileAnimationFrames for unique truecolor broodlings.\n",
        "     Generated by Tools/Qud/produce_broodling_tile_anims.py via Pixelorama host scaffold.\n",
        "     Refine sheets under DesignDrafts/pixelorama/<stem>/ then re-run. -->\n",
        '<objects Encoding="utf-8">\n\n',
    ]
    report: List[Dict] = []

    for still in stills:
        stem = still.stem
        style = _style_for(stem)
        proj = work / stem
        print(f"  scaffold {stem} style={style}")
        if args.dry_run:
            report.append({"stem": stem, "style": style, "dry": True})
            continue
        result = scaffold_from_still(
            still, proj, frame_count=args.frames, style=style, stem=stem
        )
        if not result.get("ok"):
            print(f"  FAIL {stem}: {result.get('error')}")
            continue
        installed = install_frames(
            result,
            creatures,
            mirror if mirror.is_dir() else None,
            stem,
            still=still,
        )
        bp = blueprint_for_stem(stem)
        if not stem.startswith("sw_"):
            xml_parts.append(anim_xml_snippet(bp, stem, len(installed)))
            xml_parts.append("\n")
        report.append(
            {
                "stem": stem,
                "style": style,
                "frames": [p.name for p in installed],
                "sheet": result.get("sheet", {}).get("path"),
            }
        )
        print(f"  OK {stem} -> {len(installed)} frames")

    xml_parts.append("</objects>\n")
    xml_path = mod / "ObjectBlueprints_TileAnims.xml"
    if args.write_xml and not args.dry_run:
        xml_path.write_text("".join(xml_parts), encoding="utf-8")
        print(f"Wrote {xml_path}")

    summary = work / "_anim_report.json"
    summary.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"Report {summary} ({len(report)} tiles)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
