<#
.SYNOPSIS
    Migrates Caves of Qud mod source (.cs / .xml) off obsolete Assembly-CSharp APIs.

.DESCRIPTION
    Loads the persisted obsolete-API dump (data\obsolete_api_dump.json) as the source of
    truth for what is obsolete and what it should become, applies a curated set of
    hand-verified, mechanically-safe rewrites, and reports every remaining obsolete-pattern
    hit that still needs a human (or a follow-up semi-automated pass).

    The dump is NOT regenerated by this script. It was captured once via the scratch\ApiDump
    reflection tool and is checked in at _tools\data\obsolete_api_dump.json. See README.md.

    Dry-run by default. Nothing is written to disk unless -Apply is passed.

.PARAMETER Path
    One or more root folders to scan. Defaults to the Mods folder (parent of _tools).

.PARAMETER IncludeWorkshop
    Also scan the Steam Workshop content folder for CoQ (333640), read-only style (dry-run
    is obviously safe there; -Apply against Workshop content is allowed but not recommended
    since Workshop syncs can clobber local edits).

.PARAMETER Mod
    Convenience filter: only scan subfolder(s) of Path whose folder name matches this
    (wildcards ok), e.g. -Mod "LogSuppressor".

.PARAMETER Apply
    Actually write fixes to disk. Without this switch the tool only reports what it WOULD do.

.PARAMETER NoBackup
    When -Apply is used, a `<file>.bak` copy is written next to any file that gets modified,
    unless this switch is passed.

.PARAMETER Report
    Path to write the Markdown report to. Defaults to
    _tools\reports\ApiMigration_<timestamp>.md

.PARAMETER DumpPath
    Path to the obsolete-API JSON dump. Defaults to _tools\data\obsolete_api_dump.json next
    to this script.

.PARAMETER Exclude
    Additional directory name patterns to exclude, on top of the built-in
    _tools, bin, obj, .git defaults.

.EXAMPLE
    .\Update-ObsoleteApis.ps1 -Mod LogSuppressor
    Dry-run a single mod folder and print/save a report of auto-fixable hits and remaining
    manual-review hits.

.EXAMPLE
    .\Update-ObsoleteApis.ps1 -Mod LogSuppressor -Apply
    Same, but actually rewrites the safe patterns in place (with .bak backups).

.EXAMPLE
    .\Update-ObsoleteApis.ps1 -IncludeWorkshop -Report C:\temp\full_report.md
    Dry-run every local mod plus the Workshop content folder.
#>

[CmdletBinding()]
param(
    [string[]]$Path,
    [switch]$IncludeWorkshop,
    [string]$Mod,
    [switch]$Apply,
    [switch]$NoBackup,
    [string]$Report,
    [string]$DumpPath,
    [string]$RulesPath,
    [string[]]$Exclude = @()
)

$ErrorActionPreference = 'Stop'

# ApiMigrator.Core is net8 — Windows PowerShell 5.1 cannot Add-Type it (HRESULT 0x80131515).
# Re-launch under pwsh 7+ when available (user has pwsh 7.6.x installed).
if ($PSVersionTable.PSEdition -ne 'Core' -and -not $env:COQ_APIMIGRATOR_PS7) {
    $pwsh = (Get-Command pwsh -ErrorAction SilentlyContinue).Source
    if ($pwsh) {
        $env:COQ_APIMIGRATOR_PS7 = '1'
        $forward = @()
        foreach ($key in $PSBoundParameters.Keys) {
            $val = $PSBoundParameters[$key]
            if ($val -is [switch] -and $val) { $forward += "-$key" }
            elseif ($val -is [array]) { $forward += "-$key"; $forward += $val }
            elseif ($null -ne $val) { $forward += "-$key"; $forward += $val }
        }
        & $pwsh -NoProfile -File $PSCommandPath @forward
        exit $LASTEXITCODE
    }
    throw @"
Update-ObsoleteApis.ps1 requires PowerShell 7+ to load ApiMigrator.Core.dll (net8).
Install PowerShell 7 (winget install Microsoft.PowerShell) or run:
  pwsh -NoProfile -File "$PSCommandPath" <your -Path/-Apply args>
"@
}

Set-StrictMode -Version Latest

$ScriptRoot = $PSScriptRoot
$ApiMigratorToolsRoot = $ScriptRoot
. (Join-Path $ScriptRoot 'scripts\CoqPaths.ps1')
. (Join-Path $ScriptRoot 'scripts\ApiMigrator.Isolated.ps1')
$ModsRoot = Get-CoqModsRoot -ToolsRoot $ScriptRoot

$SteamLibrary = Get-CoqSteamLibrary
$WorkshopRoot = Join-Path $SteamLibrary 'steamapps\workshop\content\333640'
$ManagedDll = Join-Path $SteamLibrary 'steamapps\common\Caves of Qud\CoQ_Data\Managed\Assembly-CSharp.dll'

if (-not $DumpPath) { $DumpPath = Join-Path $ScriptRoot 'data\obsolete_api_dump.json' }
if (-not $RulesPath) { $RulesPath = Join-Path $ScriptRoot 'data\curated_rewrite_rules.json' }
$DataDir = Join-Path $ScriptRoot 'data'
$DefaultDumpPath = Join-Path $DataDir 'obsolete_api_dump.json'
if (($DumpPath -eq $DefaultDumpPath) -and (Test-Path -LiteralPath $ManagedDll)) {
    try {
        $liveVer = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($ManagedDll).FileVersion
        $targetVer = $liveVer
        $overridePath = Join-Path $DataDir 'by-version\active-override.json'
        $pinned = $false
        if (Test-Path -LiteralPath $overridePath) {
            try {
                $ov = Get-Content -Raw -LiteralPath $overridePath | ConvertFrom-Json
                if ($ov.forceFileVersion) {
                    $targetVer = [string]$ov.forceFileVersion
                    $pinned = $true
                    Write-Host "API profile pinned to $targetVer (live Steam FileVersion is $liveVer). CLI: switch-api live" -ForegroundColor DarkCyan
                }
            } catch { }
        }
        if ($targetVer) {
            $profileDir = Join-Path $DataDir ("by-version\" + ($targetVer -replace '[^\w\.\-]+', '_'))
            $profileDump = Join-Path $profileDir 'obsolete_api_dump.json'
            $profileRules = Join-Path $profileDir 'curated_rewrite_rules.json'
            $profileCharts = Join-Path $profileDir 'charts'
            $activeVer = $null
            if (Test-Path -LiteralPath $DumpPath) {
                try {
                    $activeVer = (Get-Content -Raw -LiteralPath $DumpPath | ConvertFrom-Json)._meta.gameFileVersion
                } catch { $activeVer = $null }
            }
            if ((Test-Path -LiteralPath $profileDump) -and ($activeVer -ne $targetVer)) {
                if (Test-Path -LiteralPath $DumpPath) {
                    $prevLabel = if ($activeVer) { $activeVer } else { "unknown-$(Get-Date -Format 'yyyyMMdd_HHmmss')" }
                    $snapDir = Join-Path $DataDir ("by-version\" + ($prevLabel -replace '[^\w\.\-]+', '_'))
                    New-Item -ItemType Directory -Force -Path $snapDir | Out-Null
                    Copy-Item -LiteralPath $DumpPath -Destination (Join-Path $snapDir 'obsolete_api_dump.json') -Force
                    if (Test-Path -LiteralPath $RulesPath) {
                        Copy-Item -LiteralPath $RulesPath -Destination (Join-Path $snapDir 'curated_rewrite_rules.json') -Force
                    }
                    Write-Host "Snapshotted previous dump+rules → $snapDir" -ForegroundColor DarkYellow
                }
                Copy-Item -LiteralPath $profileDump -Destination $DumpPath -Force
                if (Test-Path -LiteralPath $profileRules) {
                    Copy-Item -LiteralPath $profileRules -Destination $RulesPath -Force
                }
                $activeCharts = Join-Path $DataDir 'charts'
                if (Test-Path -LiteralPath $profileCharts) {
                    New-Item -ItemType Directory -Force -Path $activeCharts | Out-Null
                    Copy-Item -Path (Join-Path $profileCharts '*') -Destination $activeCharts -Recurse -Force
                }
                $syncLabel = if ($pinned) { "pinned $targetVer" } else { "FileVersion $targetVer" }
                Write-Host "Active dump+rules synced to $syncLabel from $profileDir" -ForegroundColor Cyan
            }
            elseif (-not (Test-Path -LiteralPath $profileDump)) {
                Write-Host "No by-version profile for $targetVer yet (active dump/rules unchanged). CLI: sync-version --save-profile" -ForegroundColor DarkGray
            }
        }
    } catch {
        Write-Host "Version sync skipped: $($_.Exception.Message)" -ForegroundColor DarkYellow
    }
}

$DefaultExcludeDirs = @('_tools', 'bin', 'obj', '.git', '.vs', '_decompile', '_decompile_il', 'scratch', '_reports')
$ExcludeDirs = @($DefaultExcludeDirs + $Exclude) | Select-Object -Unique

$ScanExtensions = @('.cs', '.xml')

# ---------------------------------------------------------------------------
# 1. Resolve scan roots
# ---------------------------------------------------------------------------

if (-not $Path -or $Path.Count -eq 0) {
    $Path = @($ModsRoot)
}
if (-not $Report) {
    $stamp = Get-Date -Format 'yyyyMMdd_HHmmss'
    $Report = Join-Path $ScriptRoot "reports\ApiMigration_$stamp.md"
}
if ($IncludeWorkshop -and (Test-Path $WorkshopRoot)) {
    $Path = @($Path + $WorkshopRoot) | Select-Object -Unique
}

Write-Host "Scan roots:" -ForegroundColor Cyan
$Path | ForEach-Object { Write-Host "  $_" }

# ---------------------------------------------------------------------------
# 2. Load the obsolete-API dump (source of truth)
# ---------------------------------------------------------------------------

if (-not (Test-Path $DumpPath)) {
    throw "Obsolete API dump not found at '$DumpPath'. This tool relies on the persisted dump; see README.md for how it was captured."
}

$DumpRaw = Get-Content -Raw -LiteralPath $DumpPath | ConvertFrom-Json
$DumpEntries = @($DumpRaw.entries)
Write-Host "Loaded $($DumpEntries.Count) obsolete-API entries from $DumpPath" -ForegroundColor Cyan

# Mirror ApiMigrator.Core.RuleEngine — curated keeps 2s; dump scan uses 500ms so a single
# catastrophic pattern cannot pin a file for minutes (626 entries × 2s = 20+ min worst case).
$RegexMatchTimeout = [TimeSpan]::FromSeconds(2)
$DumpRegexMatchTimeout = [TimeSpan]::FromMilliseconds(500)
$RegexNone = [System.Text.RegularExpressions.RegexOptions]::None

function Get-DumpScanNeedle {
    param($Entry)
    # Cheap Ordinal gate before dump regex (mirrors RuleEngine.TryGetDumpScanNeedle).
    $m = [string]$Entry.member
    if ($m.Length -ge 4 -and $m -match '^[A-Za-z_][A-Za-z0-9_]*$') { return $m }
    return $null
}

# Pre-compile a regex per dump entry for the "remaining hits" scan. Matching runs against
# the FULL file content (not line-by-line) so that entries needing surrounding-context
# lookbehind (e.g. ReplaceBuilder.AddObject vs. the unrelated Cell/Inventory.AddObject) work
# correctly across line boundaries; the line number is then derived from the match index.
$DumpRegexes = @(foreach ($e in $DumpEntries) {
    [PSCustomObject]@{
        Entry  = $e
        Needle = Get-DumpScanNeedle -Entry $e
        Regex  = [regex]::new([string]$e.searchPattern, $RegexNone, $DumpRegexMatchTimeout)
    }
})

function Get-LineNumberFromIndex {
    param([string]$Text, [int]$Index)
    # Linear scan — do NOT use [regex]::Matches on a Substring (alloc + ReDoS risk per hit).
    if ($Index -le 0) { return 1 }
    $count = 1
    $lim = [Math]::Min($Index, $Text.Length)
    for ($i = 0; $i -lt $lim; $i++) {
        if ($Text[$i] -eq "`n") { $count++ }
    }
    return $count
}

function Get-LineText {
    param([string]$Text, [int]$Index)
    $start = $Text.LastIndexOf("`n", [Math]::Max($Index - 1, 0))
    if ($start -lt 0) { $start = -1 }
    $end = $Text.IndexOf("`n", $Index)
    if ($end -lt 0) { $end = $Text.Length }
    return $Text.Substring($start + 1, $end - $start - 1).Trim()
}

# Mirrors ApiMigrator.Core.HitFilter for comments / GameText / short pronoun-in-string.
# Keep in sync with HitFilter.cs when changing suppression rules.
$ShortGameObjectMembers = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
@(
    'a','A','an','An','the','The','them','Them','they','They',
    'their','Their','its','Its','itself','Itself','it','It',
    'tis','Tis','itis','Is','are'
) | ForEach-Object { [void]$ShortGameObjectMembers.Add($_) }

function Test-InsideLineOrBlockComment {
    param([string]$Content, [int]$Index)
    if ($Index -lt 0 -or $Index -gt $Content.Length) { return $false }
    $i = 0
    $block = 0
    while ($i -lt $Index) {
        $c = $Content[$i]
        if ($c -eq '"' -or $c -eq "'") {
            $i++
            while ($i -lt $Content.Length) {
                if ($Content[$i] -eq '\' ) { $i += 2; continue }
                if ($Content[$i] -eq $c) { $i++; break }
                $i++
            }
            continue
        }
        if ($c -eq '/' -and ($i + 1) -lt $Content.Length) {
            $n = $Content[$i + 1]
            if ($n -eq '/' -and $block -eq 0) {
                $eol = $Content.IndexOf("`n", $i + 2)
                if ($eol -lt 0) { $eol = $Content.Length }
                # Match on this comment line → suppress; otherwise skip past and keep scanning.
                if ($Index -gt $i -and $Index -lt $eol) { return $true }
                $i = $eol
                continue
            }
            if ($n -eq '*') { $block++; $i += 2; continue }
        }
        if ($block -gt 0 -and $c -eq '*' -and ($i + 1) -lt $Content.Length -and $Content[$i + 1] -eq '/') {
            $block--; $i += 2; continue
        }
        $i++
    }
    return ($block -gt 0)
}

function Test-InsideGameTextToken {
    param([string]$Content, [int]$Index)
    if ($Index -le 0 -or $Index -ge $Content.Length) { return $false }
    $lineStart = if ($Index -eq 0) { 0 } else { $Content.LastIndexOf("`n", $Index - 1) + 1 }
    $lineEnd = $Content.IndexOf("`n", $Index)
    if ($lineEnd -lt 0) { $lineEnd = $Content.Length }
    for ($open = $Index - 1; $open -ge $lineStart; $open--) {
        if ($Content[$open] -ne '=') { continue }
        if (($open + 1) -ge $lineEnd) { continue }
        if (-not [char]::IsLetter($Content[$open + 1])) { continue }
        $close = $Content.IndexOf('=', $Index)
        if ($close -lt 0 -or $close -ge $lineEnd) { return $false }
        for ($k = $open + 1; $k -lt $close; $k++) {
            $ch = $Content[$k]
            if ([char]::IsLetterOrDigit($ch)) { continue }
            if ($ch -eq '.' -or $ch -eq '_' -or $ch -eq ':' -or $ch -eq '#' -or $ch -eq "'" -or $ch -eq '-') { continue }
            return $false
        }
        return ($close -gt ($open + 1))
    }
    return $false
}

function Test-InsideStringLiteralSimple {
    param([string]$Content, [int]$Index)
    if ($Index -lt 0 -or $Index -ge $Content.Length) { return $false }
    $i = 0
    while ($i -lt $Index) {
        $c = $Content[$i]
        if ($c -eq '"') {
            $start = $i
            $i++
            while ($i -lt $Content.Length) {
                if ($Content[$i] -eq '\') { $i += 2; continue }
                if ($Content[$i] -eq '"') { $i++; break }
                $i++
            }
            if ($Index -gt $start -and $Index -lt $i) { return $true }
            continue
        }
        if ($c -eq '/' -and ($i + 1) -lt $Content.Length) {
            $n = $Content[$i + 1]
            if ($n -eq '/') {
                $eol = $Content.IndexOf("`n", $i + 2)
                $i = if ($eol -lt 0) { $Content.Length } else { $eol }
                continue
            }
            if ($n -eq '*') {
                $end = $Content.IndexOf('*/', $i + 2)
                $i = if ($end -lt 0) { $Content.Length } else { $end + 2 }
                continue
            }
        }
        $i++
    }
    return $false
}

function Test-ShouldReportHit {
    param($Entry, [string]$Content, $Match)
    $index = $Match.Index
    if (Test-InsideLineOrBlockComment -Content $Content -Index $index) { return $false }
    if (Test-InsideGameTextToken -Content $Content -Index $index) { return $false }
    $isGo = $Entry.type -like '*GameObject'
    if ($isGo -and $ShortGameObjectMembers.Contains([string]$Entry.member)) {
        if (Test-InsideStringLiteralSimple -Content $Content -Index $index) { return $false }
    }
    return $true
}

# ---------------------------------------------------------------------------
# 3. Curated safe auto-fix rules — loaded from data\curated_rewrite_rules.json
#    (the same file the C# ApiMigrator.Core/GUI engine reads), so the CLI and
#    GUI can never drift out of sync. Each rule is a hand-verified regex +
#    replacement (same method name/signature on both sides, or called out by
#    the user from prior mod-fix work). See that JSON file for notes.
# ---------------------------------------------------------------------------

if (-not (Test-Path $RulesPath)) {
    throw "Curated rewrite rules file not found at '$RulesPath'."
}
$RulesRaw = Get-Content -Raw -LiteralPath $RulesPath | ConvertFrom-Json
$disabledRuleCount = 0
$CuratedRules = @(foreach ($r in $RulesRaw.rules) {
    # Optional enabled:false keeps the rule in JSON for history but skips Apply/dry-run.
    if (($r.PSObject.Properties.Name -contains 'enabled') -and ($r.enabled -eq $false)) {
        $disabledRuleCount++
        continue
    }
    $ensure = @()
    if (($r.PSObject.Properties.Name -contains 'ensureUsings') -and ($null -ne $r.ensureUsings)) {
        $ensure = @($r.ensureUsings)
    }
    $requires = $null
    if (($r.PSObject.Properties.Name -contains 'requiresSubstring') -and $r.requiresSubstring) {
        $requires = [string]$r.requiresSubstring
    }
    [PSCustomObject]@{
        Name               = $r.name
        Regex              = [regex]::new([string]$r.pattern, $RegexNone, $RegexMatchTimeout)
        Replacement        = $r.replacement
        DumpMember         = $r.dumpMember
        Note               = $r.note
        EnsureUsings       = $ensure
        RequiresSubstring  = $requires
    }
})
$PostEnsureUsings = @()
if (($RulesRaw.PSObject.Properties.Name -contains 'postEnsureUsings') -and ($null -ne $RulesRaw.postEnsureUsings)) {
    $PostEnsureUsings = @(foreach ($p in $RulesRaw.postEnsureUsings) {
        [PSCustomObject]@{
            Name     = $p.name
            IfRegex  = [regex]::new([string]$p.ifPattern, $RegexNone, $RegexMatchTimeout)
            Usings   = @($p.usings)
        }
    })
}
Write-Host "Loaded $($CuratedRules.Count) curated auto-fix rules from $RulesPath" -ForegroundColor Cyan
if ($disabledRuleCount -gt 0) {
    Write-Host "Skipped $disabledRuleCount disabled curated rule(s) (enabled:false)." -ForegroundColor DarkYellow
}
if ($PostEnsureUsings.Count -gt 0) {
    Write-Host "Loaded $($PostEnsureUsings.Count) post-ensure-using heuristics" -ForegroundColor Cyan
}

function Remove-NullableRefAnnotations {
    <#
    .SYNOPSIS
      Strip #nullable directives and reference-type Type? annotations (CoQ CS8632).
      Keeps ?., ??, ternary, value-type nullables (int?, bool?, DialogResult?, …),
      file-local enums, struct/Enum-constrained type params (TEnum?), and strips List<T>? / T[]?.
    #>
    param([string]$Content)
    if ([string]::IsNullOrEmpty($Content)) {
        return [PSCustomObject]@{ Content = $Content; EditCount = 0 }
    }

    $script:NullableEditCount = 0
    $working = [regex]::Replace($Content, '(?m)^[ \t]*#nullable[ \t]+(?:enable|disable|restore)[ \t]*\r?\n?', {
        $script:NullableEditCount++
        ''
    })

    $preserve = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
    foreach ($v in @(
        'bool','byte','sbyte','short','ushort','int','uint','long','ulong','float','double','decimal','char','nint','nuint',
        'Boolean','Byte','SByte','Int16','UInt16','Int32','UInt32','Int64','UInt64','Single','Double','Decimal','Char',
        'DialogResult','DateTime','DateTimeOffset','TimeSpan','Guid','IntPtr','UIntPtr','Half','Rune','Index','Range',
        'DayOfWeek','ConsoleKey','ConsoleModifiers','KeyCode','Color','Color32','Vector2','Vector3','Vector4','Quaternion',
        'Rect','RectInt','Bounds','BoundsInt','Ray','Ray2D','Plane','Matrix4x4','Vector2Int','Vector3Int','LayerMask','Hash128'
    )) { [void]$preserve.Add($v) }

    foreach ($m in [regex]::Matches($Content, '\benum\s+(?<name>[A-Za-z_][\w]*)\b')) {
        [void]$preserve.Add($m.Groups['name'].Value)
    }
    foreach ($m in [regex]::Matches($Content, '\bwhere\s+(?<name>[A-Za-z_][\w]*)\s*:\s*(?:struct\b|Enum\b|System\.Enum\b)')) {
        [void]$preserve.Add($m.Groups['name'].Value)
    }

    $working = [regex]::Replace($working,
        '(?<![.\w])(?<type>[A-Za-z_][\w]*(?:\.[A-Za-z_][\w]*)*)\?(?=\s*(?:[A-Za-z_>\],\)=;\{\[]|/\*|$))',
        {
            param($m)
            $typeName = $m.Groups['type'].Value
            $simple = $typeName
            $dot = $typeName.LastIndexOf('.')
            if ($dot -ge 0) { $simple = $typeName.Substring($dot + 1) }
            if ($preserve.Contains($simple) -or $preserve.Contains($typeName)) {
                return $m.Value
            }
            $script:NullableEditCount++
            return $typeName
        })

    $working = [regex]::Replace($working,
        '(?<=[\]\)>])\?(?=\s*(?:[A-Za-z_>\],\)=;\{\[]|/\*|$))',
        {
            $script:NullableEditCount++
            ''
        })

    return [PSCustomObject]@{ Content = $working; EditCount = $script:NullableEditCount }
}

# Mirrors ApiMigrator.Core.CountMethodGroupFixer — CS0019 .Count method-group fixes/flags.
# Override preference hits: Find-OverridePreferenceHits (mirrors OverridePreferenceScanner).
$script:LinqChainMethods = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
@(
    'Where','Select','SelectMany','OfType','Cast',
    'Concat','Union','Intersect','Except','Zip','Join','GroupJoin',
    'Skip','Take','SkipWhile','TakeWhile','Distinct',
    'OrderBy','OrderByDescending','ThenBy','ThenByDescending',
    'GroupBy','Reverse','AsEnumerable','AsQueryable','DefaultIfEmpty',
    'Append','Prepend'
) | ForEach-Object { [void]$script:LinqChainMethods.Add($_) }
$script:LinqMaterializers = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
@('ToList','ToArray','ToHashSet','ToDictionary','ToLookup') | ForEach-Object { [void]$script:LinqMaterializers.Add($_) }

function Test-IsIdentChar {
    param([char]$c)
    return [char]::IsLetterOrDigit($c) -or $c -eq [char]'_'
}

function Test-IsLinqChainCount {
    param([string]$Content, [int]$CountDotIndex)
    if ($CountDotIndex -le 0 -or $CountDotIndex -ge $Content.Length -or $Content[$CountDotIndex] -ne '.') { return $false }
    $i = $CountDotIndex - 1
    while ($i -ge 0 -and [char]::IsWhiteSpace($Content[$i])) { $i-- }
    if ($i -lt 0 -or $Content[$i] -ne ')') { return $false }

    $depth = 0
    for (; $i -ge 0; $i--) {
        $c = $Content[$i]
        if ($c -eq ')') { $depth++; continue }
        if ($c -eq '(') {
            $depth--
            if ($depth -eq 0) { break }
            continue
        }
    }
    if ($i -lt 0 -or $Content[$i] -ne '(' -or $depth -ne 0) { return $false }

    $beforeCall = $i - 1
    while ($beforeCall -ge 0 -and [char]::IsWhiteSpace($Content[$beforeCall])) { $beforeCall-- }

    if ($beforeCall -ge 0 -and $Content[$beforeCall] -eq '>') {
        $gDepth = 0
        for (; $beforeCall -ge 0; $beforeCall--) {
            $c = $Content[$beforeCall]
            if ($c -eq '>') { $gDepth++; continue }
            if ($c -eq '<') {
                $gDepth--
                if ($gDepth -eq 0) { $beforeCall--; break }
            }
        }
        while ($beforeCall -ge 0 -and [char]::IsWhiteSpace($Content[$beforeCall])) { $beforeCall-- }
    }

    $methodEnd = $beforeCall
    if ($methodEnd -lt 0 -or -not (Test-IsIdentChar -c $Content[$methodEnd])) { return $false }
    while ($methodEnd -ge 0 -and (Test-IsIdentChar -c $Content[$methodEnd])) { $methodEnd-- }
    $methodStart = $methodEnd + 1
    $method = $Content.Substring($methodStart, $beforeCall - $methodStart + 1)

    if ($script:LinqMaterializers.Contains($method)) { return $false }
    if (-not $script:LinqChainMethods.Contains($method)) { return $false }
    return $true
}

function Get-ReceiverNameBeforeCount {
    param([string]$Content, [int]$CountDotIndex)
    $i = $CountDotIndex - 1
    while ($i -ge 0 -and [char]::IsWhiteSpace($Content[$i])) { $i-- }
    if ($i -ge 0 -and $Content[$i] -eq '?') { $i-- }
    while ($i -ge 0 -and [char]::IsWhiteSpace($Content[$i])) { $i-- }
    if ($i -lt 0 -or -not (Test-IsIdentChar -c $Content[$i])) { return $null }
    $end = $i
    while ($i -ge 0 -and (Test-IsIdentChar -c $Content[$i])) { $i-- }
    return $Content.Substring($i + 1, $end - $i)
}

function Get-EnumerableTypedNames {
    param([string]$Content)
    $names = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
    $re = [regex]::new('\b(?:IEnumerable|IQueryable|IOrderedEnumerable|IOrderedQueryable)\s*<(?:[^<>]|<[^<>]*>)*>\s+(?<name>[A-Za-z_]\w*)\b')
    foreach ($m in $re.Matches($Content)) {
        if (Test-InsideLineOrBlockComment -Content $Content -Index $m.Index) { continue }
        if (Test-InsideStringLiteralSimple -Content $Content -Index $m.Index) { continue }
        $name = $m.Groups['name'].Value
        $afterName = $m.Index + $m.Length
        while ($afterName -lt $Content.Length -and [char]::IsWhiteSpace($Content[$afterName])) { $afterName++ }
        if ($afterName -lt $Content.Length -and $Content[$afterName] -eq '(') { continue }
        [void]$names.Add($name)
    }
    # Unary comma: keep HashSet as one object (empty must not unwrap to $null).
    return , $names
}

function Repair-CountMethodGroups {
    <#
    .SYNOPSIS
      High-confidence CS0019 fixes: LINQ-chain .Count OP → .Count(); IEnumerable-typed name.Count → .Count().
      Leaves List/Dictionary/ToList().Count property uses alone.
    #>
    param([string]$Content)
    if ([string]::IsNullOrEmpty($Content)) {
        return [PSCustomObject]@{ Content = $Content; EditCount = 0 }
    }

    $enumerableNames = Get-EnumerableTypedNames -Content $Content
    $countCompare = [regex]::new('\.Count(?!\s*\()(?=\s*(?:==|!=|<=|>=|<|>))')
    $matches = $countCompare.Matches($Content)
    if ($matches.Count -eq 0) {
        return [PSCustomObject]@{ Content = $Content; EditCount = 0 }
    }

    $sb = [System.Text.StringBuilder]::new($Content)
    $edits = 0
    for ($i = $matches.Count - 1; $i -ge 0; $i--) {
        $m = $matches[$i]
        if (Test-InsideLineOrBlockComment -Content $Content -Index $m.Index) { continue }
        if (Test-InsideStringLiteralSimple -Content $Content -Index $m.Index) { continue }

        $fix = $false
        if (Test-IsLinqChainCount -Content $Content -CountDotIndex $m.Index) {
            $fix = $true
        }
        else {
            $recv = Get-ReceiverNameBeforeCount -Content $Content -CountDotIndex $m.Index
            if ($recv -and $null -ne $enumerableNames -and $enumerableNames.Contains($recv)) { $fix = $true }
        }
        if (-not $fix) { continue }

        [void]$sb.Insert($m.Index + $m.Length, '()')
        $edits++
    }
    return [PSCustomObject]@{ Content = $sb.ToString(); EditCount = $edits }
}

function Find-CountMethodGroupHits {
    <#
    .SYNOPSIS
      Flag leftover LINQ-chain .Count compares and ?? Enumerable.Empty<(...)> tuple CS0019 notes.
    #>
    param([string]$Content)
    $hits = New-Object System.Collections.Generic.List[object]
    if ([string]::IsNullOrEmpty($Content)) { return $hits }

    $countCompare = [regex]::new('\.Count(?!\s*\()(?=\s*(?:==|!=|<=|>=|<|>))')
    foreach ($m in $countCompare.Matches($Content)) {
        if (Test-InsideLineOrBlockComment -Content $Content -Index $m.Index) { continue }
        if (Test-InsideStringLiteralSimple -Content $Content -Index $m.Index) { continue }
        if (Test-IsLinqChainCount -Content $Content -CountDotIndex $m.Index) {
            $hits.Add([PSCustomObject]@{
                Line    = Get-LineNumberFromIndex -Text $Content -Index $m.Index
                Member  = 'CS0019.CountMethodGroup'
                Message = 'CS0019 method-group Count — use .Count() or .Count property'
                Manual  = $true
                Text    = Get-LineText -Text $Content -Index $m.Index
            })
        }
    }

    $tupleEmpty = [regex]::new('\?\?\s*Enumerable\.Empty\s*<\s*\(')
    foreach ($m in $tupleEmpty.Matches($Content)) {
        if (Test-InsideLineOrBlockComment -Content $Content -Index $m.Index) { continue }
        if (Test-InsideStringLiteralSimple -Content $Content -Index $m.Index) { continue }
        $hits.Add([PSCustomObject]@{
            Line    = Get-LineNumberFromIndex -Text $Content -Index $m.Index
            Member  = 'CS0019.TupleEmptyCoalesce'
            Message = 'CS0019 possible incompatible ?? with Enumerable.Empty<(...)> — named vs unnamed tuple element names often differ; align tuple types by hand'
            Manual  = $true
            Text    = Get-LineText -Text $Content -Index $m.Index
        })
    }
    return $hits
}

function Find-OverridePreferenceHits {
    <#
    .SYNOPSIS
      Report-only: flag curated override extension points as PreferXML / PreferHarmonyPatch.
      Delegates to ApiMigrator.Core.OverridePreferenceScanner (IPart/Effect event-pipeline carve-out).
    #>
    param([string]$Content)
    [void](Ensure-ApiMigratorCoreDll)
    $hits = New-Object System.Collections.Generic.List[object]
    if ([string]::IsNullOrEmpty($Content)) { return $hits }
    foreach ($h in [ApiMigrator.Core.OverridePreferenceScanner]::Scan($Content)) {
        $hits.Add([PSCustomObject]@{
            Line    = $h.Line
            Member  = $h.Member
            Message = $h.Message
            Advice  = $h.Advice
            Manual  = $true
            Text    = $h.Text
        })
    }
    return $hits
}

function Test-HasUsing {
    param([string]$Content, [string]$Namespace)
    return [regex]::IsMatch($Content, "(?m)^(?:global\s+)?using\s+$([regex]::Escape($Namespace))\s*;")
}

function Add-MissingUsings {
    param([string]$Content, [string[]]$Namespaces)
    $needed = @(
        $Namespaces |
            Where-Object { $_ -and $_.Trim() } |
            Select-Object -Unique |
            Where-Object { -not (Test-HasUsing -Content $Content -Namespace $_) } |
            Sort-Object
    )
    if ($needed.Count -eq 0) {
        return [PSCustomObject]@{ Content = $Content; Inserted = @() }
    }

    $nl = if ($Content -match "`r`n") { "`r`n" } else { "`n" }
    $block = ($needed | ForEach-Object { "using $_;$nl" }) -join ''

    $usingMatches = [regex]::Matches($Content, '(?m)^(?:global\s+)?using\s+[^;]+;\r?\n')
    if ($usingMatches.Count -gt 0) {
        $last = $usingMatches[$usingMatches.Count - 1]
        $insertAt = $last.Index + $last.Length
        $newContent = $Content.Insert($insertAt, $block)
        return [PSCustomObject]@{ Content = $newContent; Inserted = $needed }
    }

    $nsMatch = [regex]::Match($Content, '(?m)^(?:(?:public|internal|file)\s+)?namespace\s')
    if ($nsMatch.Success) {
        $newContent = $Content.Insert($nsMatch.Index, $block + $nl)
        return [PSCustomObject]@{ Content = $newContent; Inserted = $needed }
    }

    return [PSCustomObject]@{ Content = ($block + $nl + $Content); Inserted = $needed }
}

# ---------------------------------------------------------------------------
# 4. Enumerate target files
# ---------------------------------------------------------------------------

function Test-ExcludedPath {
    param([string]$FullPath)
    $normalized = $FullPath -replace '/', '\'
    foreach ($dir in $ExcludeDirs) {
        if ($normalized -match "(?i)\\$([regex]::Escape($dir))(\\|$)") { return $true }
    }
    return $false
}

function Get-TargetFiles {
    param([string[]]$Roots)
    $files = New-Object System.Collections.Generic.List[System.IO.FileInfo]
    foreach ($root in $Roots) {
        if (-not (Test-Path -LiteralPath $root)) {
            Write-Warning "Path not found, skipping: $root"
            continue
        }
        if (Test-Path -LiteralPath $root -PathType Leaf) {
            $item = Get-Item -LiteralPath $root
            if ($ScanExtensions -contains $item.Extension.ToLowerInvariant() -and
                -not (Test-ExcludedPath $item.FullName)) {
                if (-not $Mod -or $item.FullName -like "*$Mod*") { $files.Add($item) }
            }
            continue
        }
        $rootFiles = Get-ChildItem -LiteralPath $root -Recurse -File -ErrorAction SilentlyContinue |
            Where-Object {
                $ScanExtensions -contains $_.Extension.ToLowerInvariant() -and
                -not (Test-ExcludedPath $_.FullName)
            }
        if ($Mod) {
            $rootFiles = $rootFiles | Where-Object { $_.FullName -match "(?i)\\$([regex]::Escape($Mod))(\\|_[^\\]*\\)" -or $_.FullName -like "*\$Mod\*" -or $_.FullName -like "*$Mod*" }
        }
        foreach ($f in $rootFiles) { $files.Add($f) }
    }
    return $files
}

function Get-ManifestTargetFiles {
    param([string[]]$Roots)
    $names = @('manifest.json', 'Manifest.json', 'config.json', 'Config.json')
    $files = New-Object System.Collections.Generic.List[System.IO.FileInfo]
    foreach ($root in $Roots) {
        if (-not (Test-Path $root)) { continue }
        $rootFiles = Get-ChildItem -LiteralPath $root -Recurse -File -ErrorAction SilentlyContinue |
            Where-Object {
                ($names -contains $_.Name) -and
                -not (Test-ExcludedPath $_.FullName)
            }
        if ($Mod) {
            $rootFiles = $rootFiles | Where-Object { $_.FullName -match "(?i)\\$([regex]::Escape($Mod))(\\|_[^\\]*\\)" -or $_.FullName -like "*\$Mod\*" -or $_.FullName -like "*$Mod*" }
        }
        foreach ($f in $rootFiles) { $files.Add($f) }
    }
    return $files
}

function Repair-ModManifestContent {
    <#
    .SYNOPSIS
      Calls ApiMigrator.Core.ManifestFixer (deps array→object, strip loadOrder,
      normalize bad version strings, seed empty manifests). Preserves id/title.
    #>
    param([string]$Content)
    [void](Ensure-ApiMigratorCoreDll)
    $tuple = [ApiMigrator.Core.ManifestFixer]::Fix($(if ($null -eq $Content) { '' } else { $Content }))
    $fixList = New-Object System.Collections.Generic.List[object]
    foreach ($f in $tuple.Item2) {
        $fixList.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
    }
    return [PSCustomObject]@{ Content = $tuple.Item1; Fixes = $fixList }
}

function Repair-BlueprintTypeNamespaces {
    <#
    .SYNOPSIS
      IPart/Mutation/ObjectBuilder classes must live in XRL.World.Parts(.Mutation) /
      ObjectBuilders so ObjectBlueprintLoader ResolveType finds them. Mod-scoped.
    #>
    param([System.Collections.Generic.List[System.IO.FileInfo]]$CsFiles)
    [void](Ensure-ApiMigratorCoreDll)
    $workingMap = @{}
    $fixMap = @{}  # path -> list of {Rule,Count}
    if ($null -eq $CsFiles -or $CsFiles.Count -eq 0) {
        return [PSCustomObject]@{ Working = $workingMap; Fixes = $fixMap }
    }

    $byMod = $CsFiles | Group-Object {
        [ApiMigrator.Core.FileScanner]::GetModRoot($_.FullName)
    }

    foreach ($grp in $byMod) {
        $map = New-Object 'System.Collections.Generic.Dictionary[string,string]' ([StringComparer]::OrdinalIgnoreCase)
        foreach ($f in $grp.Group) {
            $text = Get-Content -Raw -LiteralPath $f.FullName -ErrorAction SilentlyContinue
            if ($null -eq $text) { continue }
            $map[$f.FullName] = $text
            # Seed every .cs file — sidecar fixers (Liquids.xml / InventoryActions / Statistics)
            # must see untouched files, not only ones BlueprintTypeNamespaceFixer rewrote.
            if (-not $workingMap.ContainsKey($f.FullName)) {
                $workingMap[$f.FullName] = $text
            }
        }
        if ($map.Count -eq 0) { continue }

        $result = [ApiMigrator.Core.BlueprintTypeNamespaceFixer]::FixMod($map)
        foreach ($kv in $result.UpdatedContents.GetEnumerator()) {
            $workingMap[$kv.Key] = $kv.Value
        }
        foreach ($pair in $result.Fixes) {
            $path = $pair.Item1
            $fix = $pair.Item2
            if (-not $fixMap.ContainsKey($path)) {
                $fixMap[$path] = New-Object System.Collections.Generic.List[object]
            }
            $fixMap[$path].Add([PSCustomObject]@{ Rule = $fix.RuleName; Count = $fix.Count })
        }

        # Refresh map with namespace-fixed content for FriendOrFoe pass
        $fofMap = New-Object 'System.Collections.Generic.Dictionary[string,string]' ([StringComparer]::OrdinalIgnoreCase)
        foreach ($f in $grp.Group) {
            if ($workingMap.ContainsKey($f.FullName)) {
                $fofMap[$f.FullName] = $workingMap[$f.FullName]
            }
            elseif ($map.ContainsKey($f.FullName)) {
                $fofMap[$f.FullName] = $map[$f.FullName]
            }
        }
        $fof = [ApiMigrator.Core.FriendOrFoeSpiceFixer]::FixMod($grp.Name, $fofMap)
        foreach ($kv in $fof.UpdatedContents.GetEnumerator()) {
            $workingMap[$kv.Key] = $kv.Value
        }
        foreach ($pair in $fof.Fixes) {
            $path = $pair.Item1
            $fix = $pair.Item2
            if ($fof.SpiceFiles.ContainsKey($path)) { continue }
            if (-not $fixMap.ContainsKey($path)) {
                $fixMap[$path] = New-Object System.Collections.Generic.List[object]
            }
            $fixMap[$path].Add([PSCustomObject]@{ Rule = $fix.RuleName; Count = $fix.Count })
        }
        foreach ($kv in $fof.SpiceFiles.GetEnumerator()) {
            $spicePath = $kv.Key
            $spiceContent = $kv.Value
            $workingMap[$spicePath] = $spiceContent
            if (-not $fixMap.ContainsKey($spicePath)) {
                $fixMap[$spicePath] = New-Object System.Collections.Generic.List[object]
            }
            $fixMap[$spicePath].Add([PSCustomObject]@{
                Rule  = [ApiMigrator.Core.FriendOrFoeSpiceFixer]::FixRuleName + ' (HistorySpice.json)'
                Count = 1
            })
            Write-Host "FriendOrFoe spice → $spicePath" -ForegroundColor DarkCyan
        }

        function Apply-SidecarFixer([string]$Label, $FixerResult) {
            foreach ($kv in $FixerResult.UpdatedContents.GetEnumerator()) {
                $workingMap[$kv.Key] = $kv.Value
            }
            foreach ($pair in $FixerResult.Fixes) {
                $path = $pair.Item1
                $fix = $pair.Item2
                if ($FixerResult.SidecarFiles.ContainsKey($path)) { continue }
                if (-not $fixMap.ContainsKey($path)) {
                    $fixMap[$path] = New-Object System.Collections.Generic.List[object]
                }
                $fixMap[$path].Add([PSCustomObject]@{ Rule = $fix.RuleName; Count = $fix.Count })
            }
            foreach ($kv in $FixerResult.SidecarFiles.GetEnumerator()) {
                $sidePath = $kv.Key
                $sideContent = $kv.Value
                $workingMap[$sidePath] = $sideContent
                if (-not $fixMap.ContainsKey($sidePath)) {
                    $fixMap[$sidePath] = New-Object System.Collections.Generic.List[object]
                }
                $fixMap[$sidePath].Add([PSCustomObject]@{
                    Rule  = $Label
                    Count = 1
                })
                Write-Host "$Label → $sidePath" -ForegroundColor DarkCyan
            }
        }

        function New-CsMap {
            $m = New-Object 'System.Collections.Generic.Dictionary[string,string]' ([StringComparer]::OrdinalIgnoreCase)
            foreach ($f in $grp.Group) {
                if ($workingMap.ContainsKey($f.FullName)) { $m[$f.FullName] = $workingMap[$f.FullName] }
                elseif ($map.ContainsKey($f.FullName)) { $m[$f.FullName] = $map[$f.FullName] }
            }
            $xml = Join-Path $grp.Name 'Liquids.xml'
            if ($workingMap.ContainsKey($xml)) { $m[$xml] = $workingMap[$xml] }
            elseif (Test-Path -LiteralPath $xml) { $m[$xml] = Get-Content -Raw -LiteralPath $xml }
            return $m
        }
        Apply-SidecarFixer 'InventoryActions.xml' ([ApiMigrator.Core.InventoryActionsXmlFixer]::FixMod($grp.Name, (New-CsMap)))
        Apply-SidecarFixer 'Statistics.xml' ([ApiMigrator.Core.StatisticCtorFixer]::FixMod($grp.Name, (New-CsMap)))
        Apply-SidecarFixer 'Liquids.xml' ([ApiMigrator.Core.LiquidCsToXmlFixer]::FixMod($grp.Name, (New-CsMap)))
        Apply-SidecarFixer 'Liquids.xml (OnDrink part)' ([ApiMigrator.Core.LiquidDrankToPartFixer]::FixMod($grp.Name, (New-CsMap)))
    }

    return [PSCustomObject]@{ Working = $workingMap; Fixes = $fixMap }
}

function Repair-ProgrammaticCsFixes {
    <#
    .SYNOPSIS
      ShowOptionList→PickOption, Register last-resort, ReverseTranslateBit→FetchBitByCode,
      AddAction→InventoryAction, own BaseLiquid.Drank → OnDrink part (sidecar), leftover vanilla
      Drank StringBuilder→TextBuilder, Event.FinalizeString(TB)→ToString,
      AppendSigned/AddsRep arity, Harmony dynamic patches for removed minigame types,
      Options.Sifrah* branch stripping.
      Mirrors ApiMigrator.Core programmatic fixers (after Count fixer).
    #>
    param([string]$Content)
    [void](Ensure-ApiMigratorCoreDll)
    $working = $(if ($null -eq $Content) { '' } else { $Content })
    $fixList = New-Object System.Collections.Generic.List[object]

    $pick = [ApiMigrator.Core.ShowOptionListFixer]::Fix($working)
    $working = $pick.Item1
    if ($pick.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.ShowOptionListFixer]::FixRuleName
            Count = [int]$pick.Item2
        })
    }
    if ($pick.Item3 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.ShowOptionListFixer]::FixRuleNameAsync
            Count = [int]$pick.Item3
        })
    }

    $reg = [ApiMigrator.Core.RegisterOverrideFixer]::Fix($working)
    $working = $reg.Item1
    if ($reg.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.RegisterOverrideFixer]::FixRuleName
            Count = [int]$reg.Item2
        })
    }

    $bit = [ApiMigrator.Core.ReverseTranslateBitFixer]::Fix($working)
    $working = $bit.Item1
    if ($bit.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.ReverseTranslateBitFixer]::FixRuleNameId
            Count = [int]$bit.Item2
        })
    }
    if ($bit.Item3 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.ReverseTranslateBitFixer]::FixRuleNameColor
            Count = [int]$bit.Item3
        })
    }
    if ($bit.Item4 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.ReverseTranslateBitFixer]::FixRuleNameChar
            Count = [int]$bit.Item4
        })
    }

    $add = [ApiMigrator.Core.AddActionFixer]::Fix($working)
    $working = $add.Item1
    if ($add.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.AddActionFixer]::FixRuleName
            Count = [int]$add.Item2
        })
    }

    $rep = [ApiMigrator.Core.AppendReputationDescriptionFixer]::Fix($working)
    $working = $rep.Item1
    if ($rep.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.AppendReputationDescriptionFixer]::FixRuleName
            Count = [int]$rep.Item2
        })
        $usingResult = Add-MissingUsings -Content $working -Namespaces @('XRL.World.Text')
        $working = $usingResult.Content
        if ($usingResult.Inserted -and $usingResult.Inserted.Count -gt 0) {
            $fixList.Add([PSCustomObject]@{
                Rule  = "ensure using: " + ($usingResult.Inserted -join ', ')
                Count = [int]$usingResult.Inserted.Count
            })
        }
    }

    $things = [ApiMigrator.Core.ThingsFixer]::Fix($working)
    $working = $things.Item1
    if ($things.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.ThingsFixer]::FixRuleName
            Count = [int]$things.Item2
        })
    }

    $gt = [ApiMigrator.Core.GameTextCallSiteFixer]::Fix($working)
    $working = $gt.Item1
    if ($gt.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.GameTextCallSiteFixer]::FixRuleName
            Count = [int]$gt.Item2
        })
        $usingResult = Add-MissingUsings -Content $working -Namespaces @('XRL.World.Text')
        $working = $usingResult.Content
        if ($usingResult.Inserted -and $usingResult.Inserted.Count -gt 0) {
            $fixList.Add([PSCustomObject]@{
                Rule  = "ensure using: " + ($usingResult.Inserted -join ', ')
                Count = [int]$usingResult.Inserted.Count
            })
        }
    }

    $tb = [ApiMigrator.Core.TextBuilderCsFixer]::Fix($working)
    $working = $tb.Item1
    if ($tb.Item2 -and $tb.Item2.Count -gt 0) {
        foreach ($f in $tb.Item2) {
            $fixList.Add([PSCustomObject]@{
                Rule  = $f.RuleName
                Count = [int]$f.Count
            })
        }
    }

    $modern = [ApiMigrator.Core.ModernCompilerFixer]::Fix($working)
    $working = $modern.Item1
    if ($modern.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.ModernCompilerFixer]::FixRuleName
            Count = [int]$modern.Item2
        })
    }

    $gdn = [ApiMigrator.Core.GetDisplayNameArgFixer]::Fix($working)
    $working = $gdn.Item1
    if ($gdn.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.GetDisplayNameArgFixer]::FixRuleName
            Count = [int]$gdn.Item2
        })
    }

    $mutSet = [ApiMigrator.Core.BaseMutationSetterFixer]::Fix($working)
    $working = $mutSet.Item1
    if ($mutSet.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.BaseMutationSetterFixer]::FixRuleName
            Count = [int]$mutSet.Item2
        })
    }

    $moe = [ApiMigrator.Core.MutationOnEquipCsFixer]::Fix($working)
    $working = $moe.Item1
    if ($moe.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.MutationOnEquipCsFixer]::FixRuleName
            Count = [int]$moe.Item2
        })
    }

    $drank = [ApiMigrator.Core.DrankOverrideFixer]::Fix($working)
    $working = $drank.Item1
    if ($drank.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.DrankOverrideFixer]::FixRuleName
            Count = [int]$drank.Item2
        })
        $usingResult = Add-MissingUsings -Content $working -Namespaces @('XRL.World.Text')
        $working = $usingResult.Content
        if ($usingResult.Inserted -and $usingResult.Inserted.Count -gt 0) {
            $fixList.Add([PSCustomObject]@{
                Rule  = "ensure using: $($usingResult.Inserted -join ', ')"
                Count = $usingResult.Inserted.Count
            })
        }
    }

    $cap = [ApiMigrator.Core.CapitalizeFixer]::Fix($working)
    $working = $cap.Item1
    if ($cap.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.CapitalizeFixer]::FixRuleName
            Count = [int]$cap.Item2
        })
        $usingResult = Add-MissingUsings -Content $working -Namespaces @('XRL.Language')
        $working = $usingResult.Content
        if ($usingResult.Inserted -and $usingResult.Inserted.Count -gt 0) {
            $fixList.Add([PSCustomObject]@{
                Rule  = "ensure using: $($usingResult.Inserted -join ', ')"
                Count = $usingResult.Inserted.Count
            })
        }
    }

    $vr = [ApiMigrator.Core.VariableReplacerFixer]::Fix($working)
    $working = $vr.Item1
    if (($vr.Item2 + $vr.Item3) -gt 0) {
        if ($vr.Item2 -gt 0) {
            $fixList.Add([PSCustomObject]@{
                Rule  = [ApiMigrator.Core.VariableReplacerFixer]::FixRuleNameAttr
                Count = [int]$vr.Item2
            })
        }
        if ($vr.Item3 -gt 0) {
            $fixList.Add([PSCustomObject]@{
                Rule  = [ApiMigrator.Core.VariableReplacerFixer]::FixRuleNameSignature
                Count = [int]$vr.Item3
            })
        }
        $usingResult = Add-MissingUsings -Content $working -Namespaces @(
            'XRL.World', 'XRL.World.Text.Delegates', 'XRL.World.Text.Attributes')
        $working = $usingResult.Content
        if ($usingResult.Inserted -and $usingResult.Inserted.Count -gt 0) {
            $fixList.Add([PSCustomObject]@{
                Rule  = "ensure using: $($usingResult.Inserted -join ', ')"
                Count = $usingResult.Inserted.Count
            })
        }
    }

    $fr = [ApiMigrator.Core.FinalRenderOverrideFixer]::Fix($working)
    $working = $fr.Item1
    if ($fr.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.FinalRenderOverrideFixer]::FixRuleName
            Count = [int]$fr.Item2
        })
    }

    $dyn = [ApiMigrator.Core.HarmonyDynamicPatchFixer]::Fix($working)
    $working = $dyn.Item1
    if ($dyn.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.HarmonyDynamicPatchFixer]::FixRuleName
            Count = [int]$dyn.Item2
        })
    }

    $harmonyParam = [ApiMigrator.Core.HarmonyPatchParameterFixer]::Fix($working)
    $working = $harmonyParam.Item1
    if ($harmonyParam.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.HarmonyPatchParameterFixer]::FixRuleName
            Count = [int]$harmonyParam.Item2
        })
    }

    $sif = [ApiMigrator.Core.RemovedGameApiFixer]::Fix($working)
    $working = $sif.Item1
    if ($sif.Item2 -gt 0) {
        $fixList.Add([PSCustomObject]@{
            Rule  = [ApiMigrator.Core.RemovedGameApiFixer]::FixRuleName
            Count = [int]$sif.Item2
        })
    }

    return [PSCustomObject]@{ Content = $working; Fixes = $fixList }
}

function Get-ManualAdvice {
    <#
    .SYNOPSIS
      Actionable manual-fix guidance (never suggests [Obsolete]). Mirrors ManualAdvice.ForMember.
    #>
    param([string]$Member, [string]$Message, [string]$Code = '')
    [void](Ensure-ApiMigratorCoreDll)
    return [ApiMigrator.Core.ManualAdvice]::ForMember(
        $(if ($null -eq $Member) { '' } else { $Member }),
        $(if ($null -eq $Message) { '' } else { $Message }),
        $(if ($null -eq $Code) { '' } else { $Code }))
}

$TargetFiles = @(Get-TargetFiles -Roots $Path)
$ManifestFiles = @(Get-ManifestTargetFiles -Roots $Path)
Write-Host "Found $($TargetFiles.Count) candidate .cs/.xml files to scan." -ForegroundColor Cyan
Write-Host "Found $($ManifestFiles.Count) manifest.json/config.json files to scan." -ForegroundColor Cyan

$CsTargets = New-Object System.Collections.Generic.List[System.IO.FileInfo]
foreach ($f in $TargetFiles) {
    if ($f.Extension -eq '.cs') { [void]$CsTargets.Add($f) }
}
$NsPass = Repair-BlueprintTypeNamespaces -CsFiles $CsTargets
if ($NsPass.Working.Count -gt 0) {
    Write-Host "Blueprint-type namespace fixes prepared for $($NsPass.Working.Count) file(s)." -ForegroundColor DarkCyan
}

# ---------------------------------------------------------------------------
# 5. Process each file: apply curated rules, then scan what's left via the dump
# ---------------------------------------------------------------------------

$FileResults = New-Object System.Collections.Generic.List[object]
$TotalAutoFixes = 0
$TotalRemainingHits = 0
$fileIndex = 0
$fileTotal = $TargetFiles.Count

foreach ($file in $TargetFiles) {
    $fileIndex++
    if ($fileIndex -eq 1 -or ($fileIndex % 25) -eq 0 -or $fileIndex -eq $fileTotal) {
        Write-Host "Scanning $fileIndex/$fileTotal`: $($file.Name)" -ForegroundColor DarkGray
    }

    $original = Get-Content -Raw -LiteralPath $file.FullName -ErrorAction SilentlyContinue
    if ($null -eq $original) { continue }

    $working = $original
    $appliedFixes = New-Object System.Collections.Generic.List[object]
    if ($NsPass.Working.ContainsKey($file.FullName)) {
        $working = $NsPass.Working[$file.FullName]
    }
    if ($NsPass.Fixes.ContainsKey($file.FullName)) {
        foreach ($f in $NsPass.Fixes[$file.FullName]) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.Rule; Count = $f.Count })
        }
    }
    $pendingUsings = New-Object 'System.Collections.Generic.HashSet[string]'
    $isCs = $file.Extension -eq '.cs'

    foreach ($rule in $CuratedRules) {
        if ($rule.RequiresSubstring -and ($working.IndexOf([string]$rule.RequiresSubstring, [StringComparison]::Ordinal) -lt 0)) {
            continue
        }
        try {
            $matches = $rule.Regex.Matches($working)
        }
        catch [System.Text.RegularExpressions.RegexMatchTimeoutException] {
            Write-Warning "$($file.Name): regex timeout on curated rule '$($rule.Name)' (skipped)"
            continue
        }
        if ($matches.Count -gt 0) {
            $appliedFixes.Add([PSCustomObject]@{
                Rule  = $rule.Name
                Count = $matches.Count
            })
            try {
                $working = $rule.Regex.Replace($working, $rule.Replacement)
            }
            catch [System.Text.RegularExpressions.RegexMatchTimeoutException] {
                Write-Warning "$($file.Name): regex timeout replacing curated rule '$($rule.Name)' (skipped)"
                continue
            }
            if ($isCs) {
                foreach ($u in $rule.EnsureUsings) {
                    if ($u) { [void]$pendingUsings.Add([string]$u) }
                }
            }
        }
    }

    if ($isCs) {
        foreach ($post in $PostEnsureUsings) {
            if ($post.IfRegex.IsMatch($working)) {
                foreach ($u in $post.Usings) {
                    if ($u) { [void]$pendingUsings.Add([string]$u) }
                }
            }
        }

        if ($pendingUsings.Count -gt 0) {
            $usingResult = Add-MissingUsings -Content $working -Namespaces @($pendingUsings)
            $working = $usingResult.Content
            if ($usingResult.Inserted.Count -gt 0) {
                $appliedFixes.Add([PSCustomObject]@{
                    Rule  = 'ensure using: ' + ($usingResult.Inserted -join ', ')
                    Count = $usingResult.Inserted.Count
                })
            }
        }

        $nullableResult = Remove-NullableRefAnnotations -Content $working
        if ($nullableResult.EditCount -gt 0) {
            $working = $nullableResult.Content
            $appliedFixes.Add([PSCustomObject]@{
                Rule  = 'strip nullable-ref annotations (#nullable / Type?)'
                Count = $nullableResult.EditCount
            })
        }

        $countResult = Repair-CountMethodGroups -Content $working
        if ($countResult.EditCount -gt 0) {
            $working = $countResult.Content
            $appliedFixes.Add([PSCustomObject]@{
                Rule  = 'Count method-group -> Count() (LINQ / IEnumerable)'
                Count = $countResult.EditCount
            })
        }

        # ShowOptionList→PickOption + simple Register last-resort (ApiMigrator.Core)
        $progResult = Repair-ProgrammaticCsFixes -Content $working
        $working = $progResult.Content
        foreach ($f in $progResult.Fixes) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.Rule; Count = $f.Count })
        }
    }
    elseif ($file.Extension -eq '.xml') {
        [void](Ensure-ApiMigratorCoreDll)
        $closed = [ApiMigrator.Core.XmlUnclosedElementFixer]::Fix($working)
        $working = $closed.Item1
        foreach ($f in $closed.Item2) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
        }
        $inv = [ApiMigrator.Core.ObjectBlueprintXmlFixer]::Fix($working)
        $working = $inv.Item1
        foreach ($f in $inv.Item2) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
        }
        $worlds = [ApiMigrator.Core.WorldsXmlFixer]::Fix($working)
        $working = $worlds.Item1
        foreach ($f in $worlds.Item2) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
        }
        $factions = [ApiMigrator.Core.FactionsXmlFixer]::Fix($working)
        $working = $factions.Item1
        foreach ($f in $factions.Item2) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
        }
        $popXml = [ApiMigrator.Core.PopulationXmlFixer]::Fix($working)
        $working = $popXml.Item1
        foreach ($f in $popXml.Item2) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
        }
        $liquidXml = [ApiMigrator.Core.LiquidXmlFixer]::Fix($working)
        $working = $liquidXml.Item1
        foreach ($f in $liquidXml.Item2) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
        }
        $mutXml = [ApiMigrator.Core.MutationsXmlFixer]::Fix($working)
        $working = $mutXml.Item1
        foreach ($f in $mutXml.Item2) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
        }
        $namingXml = [ApiMigrator.Core.NamingXmlFixer]::Fix($working)
        $working = $namingXml.Item1
        foreach ($f in $namingXml.Item2) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
        }
        $genoXml = [ApiMigrator.Core.GenotypesXmlFixer]::Fix($working)
        $working = $genoXml.Item1
        foreach ($f in $genoXml.Item2) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
        }
        $subXml = [ApiMigrator.Core.SubtypesXmlFixer]::Fix($working)
        $working = $subXml.Item1
        foreach ($f in $subXml.Item2) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
        }
        $enc = [ApiMigrator.Core.XmlUtf8EncodingFixer]::Ensure($working)
        $working = $enc.Item1
        foreach ($f in $enc.Item2) {
            $appliedFixes.Add([PSCustomObject]@{ Rule = $f.RuleName; Count = $f.Count })
        }
    }

    # Scan the POST-fix content for anything the dump says is still obsolete.
    $remainingHits = New-Object System.Collections.Generic.List[object]
    foreach ($dr in $DumpRegexes) {
        if ($dr.Needle -and ($working.IndexOf([string]$dr.Needle, [StringComparison]::Ordinal) -lt 0)) {
            continue
        }
        try {
            $dumpMatches = $dr.Regex.Matches($working)
        }
        catch [System.Text.RegularExpressions.RegexMatchTimeoutException] {
            Write-Warning "$($file.Name): regex timeout scanning dump '$($dr.Entry.type).$($dr.Entry.member)' (skipped)"
            continue
        }
        foreach ($m in $dumpMatches) {
            if (-not (Test-ShouldReportHit -Entry $dr.Entry -Content $working -Match $m)) { continue }
            $member = "$($dr.Entry.type).$($dr.Entry.member)"
            $msg = $dr.Entry.obsoleteMessage
            $remainingHits.Add([PSCustomObject]@{
                Line    = Get-LineNumberFromIndex -Text $working -Index $m.Index
                Member  = $member
                Message = $msg
                Advice  = Get-ManualAdvice -Member $member -Message $msg -Code (Get-LineText -Text $working -Index $m.Index)
                Manual  = [bool]$dr.Entry.needsManual
                Text    = Get-LineText -Text $working -Index $m.Index
            })
        }
    }
    if ($isCs) {
        foreach ($h in (Find-CountMethodGroupHits -Content $working)) {
            if (-not $h.PSObject.Properties['Advice']) {
                $h | Add-Member -NotePropertyName Advice -NotePropertyValue (Get-ManualAdvice -Member $h.Member -Message $h.Message -Code $h.Text) -Force
            }
            $remainingHits.Add($h)
        }
        foreach ($h in (Find-OverridePreferenceHits -Content $working)) {
            $remainingHits.Add($h)
        }
        [void](Ensure-ApiMigratorCoreDll)
        foreach ($h in [ApiMigrator.Core.LiquidXmlAdviceScanner]::Scan($working)) {
            $remainingHits.Add([PSCustomObject]@{
                Line    = $h.Line
                Member  = $h.Member
                Message = $h.Message
                Advice  = $h.Advice
                Manual  = $true
                Text    = $h.Text
            })
        }
        foreach ($h in [ApiMigrator.Core.TextBuilderHalfMigrationScanner]::Scan($working)) {
            $remainingHits.Add([PSCustomObject]@{
                Line    = $h.Line
                Member  = $h.Member
                Message = $h.Message
                Advice  = $h.Advice
                Manual  = $true
                Text    = $h.Text
            })
        }
        foreach ($h in [ApiMigrator.Core.RemovedGameApiFixer]::Scan($working)) {
            $remainingHits.Add([PSCustomObject]@{
                Line    = $h.Line
                Member  = $h.Member
                Message = $h.Message
                Advice  = $h.Advice
                Manual  = $true
                Text    = $h.Text
            })
        }
    }
    else {
        # Worlds.xml + Liquids.xml report-only; also runs after WorldsXmlFixer / LiquidXmlFixer
        [void](Ensure-ApiMigratorCoreDll)
        foreach ($h in [ApiMigrator.Core.WorldsXmlAdviceScanner]::Scan($working)) {
            $remainingHits.Add([PSCustomObject]@{
                Line    = $h.Line
                Member  = $h.Member
                Message = $h.Message
                Advice  = $h.Advice
                Manual  = $true
                Text    = $h.Text
            })
        }
        foreach ($h in [ApiMigrator.Core.LiquidXmlRenderAdviceScanner]::Scan($working)) {
            $remainingHits.Add([PSCustomObject]@{
                Line    = $h.Line
                Member  = $h.Member
                Message = $h.Message
                Advice  = $h.Advice
                Manual  = $true
                Text    = $h.Text
            })
        }
        foreach ($h in [ApiMigrator.Core.FactionsXmlAdviceScanner]::Scan($working)) {
            $remainingHits.Add([PSCustomObject]@{
                Line    = $h.Line
                Member  = $h.Member
                Message = $h.Message
                Advice  = $h.Advice
                Manual  = $true
                Text    = $h.Text
            })
        }
        foreach ($h in [ApiMigrator.Core.PopulationXmlAdviceScanner]::Scan($working)) {
            $remainingHits.Add([PSCustomObject]@{
                Line    = $h.Line
                Member  = $h.Member
                Message = $h.Message
                Advice  = $h.Advice
                Manual  = $true
                Text    = $h.Text
            })
        }
    }
    $sortedHits = New-Object System.Collections.Generic.List[object]
    foreach ($h in ($remainingHits | Sort-Object Line)) { $sortedHits.Add($h) }
    $remainingHits = $sortedHits

    $changed = ($working -ne $original)

    if ($changed -or $remainingHits.Count -gt 0) {
        $FileResults.Add([PSCustomObject]@{
            File          = $file.FullName
            Changed       = $changed
            AppliedFixes  = $appliedFixes
            RemainingHits = $remainingHits
            NewContent    = $working
        })
        if ($appliedFixes.Count -gt 0) {
            $TotalAutoFixes += ($appliedFixes | Measure-Object -Property Count -Sum).Sum
        }
        $TotalRemainingHits += $remainingHits.Count
    }

    if ($changed -and $Apply) {
        if (-not $NoBackup) {
            $bak = "$($file.FullName).bak"
            if (-not (Test-Path $bak)) {
                Copy-Item -LiteralPath $file.FullName -Destination $bak -Force
            }
        }
        Set-Content -LiteralPath $file.FullName -Value $working -NoNewline:$false -Encoding UTF8
    }
}

# ---------------------------------------------------------------------------
# 5a. FriendOrFoe HistorySpice.json (created by mod-scoped pre-pass; not in .cs/.xml scan)
# ---------------------------------------------------------------------------

foreach ($spicePath in @($NsPass.Working.Keys)) {
    if ($spicePath -notmatch '(?i)[\\/]HistorySpice\.json$') { continue }
    $spiceContent = $NsPass.Working[$spicePath]
    $originalSpice = if (Test-Path -LiteralPath $spicePath) {
        Get-Content -Raw -LiteralPath $spicePath -ErrorAction SilentlyContinue
    } else { '' }
    $changedSpice = ($spiceContent -ne $originalSpice)
    if (-not $changedSpice) { continue }

    $spiceFixes = New-Object System.Collections.Generic.List[object]
    if ($NsPass.Fixes.ContainsKey($spicePath)) {
        foreach ($f in $NsPass.Fixes[$spicePath]) {
            $spiceFixes.Add([PSCustomObject]@{ Rule = $f.Rule; Count = $f.Count })
        }
    }
    $FileResults.Add([PSCustomObject]@{
        File          = $spicePath
        Changed       = $true
        AppliedFixes  = $spiceFixes
        RemainingHits = @()
        NewContent    = $spiceContent
    })
    if ($spiceFixes.Count -gt 0) {
        $TotalAutoFixes += ($spiceFixes | Measure-Object -Property Count -Sum).Sum
    }
    if ($Apply) {
        Set-Content -LiteralPath $spicePath -Value $spiceContent -NoNewline:$false -Encoding UTF8
        Write-Host "Wrote $spicePath" -ForegroundColor Green
    }
}

# ---------------------------------------------------------------------------
# 5b. Manifest / config JSON load-killer fixes (ManifestFixer)
# ---------------------------------------------------------------------------

if ($ManifestFiles.Count -gt 0) {
    [void](Ensure-ApiMigratorCoreDll)
}

foreach ($file in $ManifestFiles) {
    $original = Get-Content -Raw -LiteralPath $file.FullName -ErrorAction SilentlyContinue
    if ($null -eq $original) { $original = '' }

    $result = Repair-ModManifestContent -Content $original
    $working = $result.Content
    $appliedFixes = New-Object System.Collections.Generic.List[object]
    foreach ($af in $result.Fixes) { $appliedFixes.Add($af) }
    $changed = ($working -ne $original)

    if ($changed) {
        $FileResults.Add([PSCustomObject]@{
            File          = $file.FullName
            Changed       = $changed
            AppliedFixes  = $appliedFixes
            RemainingHits = @()
            NewContent    = $working
        })
        if ($appliedFixes.Count -gt 0) {
            $TotalAutoFixes += ($appliedFixes | Measure-Object -Property Count -Sum).Sum
        }

        if ($Apply) {
            if (-not $NoBackup) {
                $bak = "$($file.FullName).bak"
                if (-not (Test-Path $bak)) {
                    Copy-Item -LiteralPath $file.FullName -Destination $bak -Force -ErrorAction SilentlyContinue
                }
            }
            # UTF-8 no BOM (CoQ / Steam Workshop friendly)
            $utf8 = New-Object System.Text.UTF8Encoding $false
            [System.IO.File]::WriteAllText($file.FullName, $working, $utf8)
        }
    }
}

# ---------------------------------------------------------------------------
# 6. Report
# ---------------------------------------------------------------------------

$reportDir = Split-Path -Parent $Report
if ($reportDir -and -not (Test-Path $reportDir)) {
    New-Item -ItemType Directory -Force -Path $reportDir | Out-Null
}

$mode = if ($Apply) { 'APPLY (files written)' } else { 'DRY-RUN (no files written)' }
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# Caves of Qud Obsolete-API Migration Report")
[void]$sb.AppendLine()
[void]$sb.AppendLine("- Mode: **$mode**")
[void]$sb.AppendLine("- Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
[void]$sb.AppendLine("- Dump source: ``$DumpPath`` ($($DumpEntries.Count) entries)")
[void]$sb.AppendLine("- Curated rules source: ``$RulesPath`` ($($CuratedRules.Count) rules)")
[void]$sb.AppendLine("- Scan roots: $($Path -join ', ')")
if ($Mod) { [void]$sb.AppendLine("- Mod filter: ``$Mod``") }
[void]$sb.AppendLine("- Files scanned: $($TargetFiles.Count) .cs/.xml + $($ManifestFiles.Count) manifest/config.json")
[void]$sb.AppendLine("- Files with auto-fixes and/or remaining hits: $($FileResults.Count)")
[void]$sb.AppendLine("- Total auto-fix rewrites: **$TotalAutoFixes**")
[void]$sb.AppendLine("- Total remaining obsolete-pattern hits needing review: **$TotalRemainingHits**")
[void]$sb.AppendLine()
[void]$sb.AppendLine("> Advice never says to add ``[Obsolete]``. PreferXML -> PreferHarmonyPatch -> C# override only when there is no other option. In-place API body fixes are separate.")
[void]$sb.AppendLine()

if ($FileResults.Count -eq 0) {
    [void]$sb.AppendLine("No obsolete-API patterns or auto-fixes found in scope. Clean.")
} else {
    foreach ($fr in $FileResults) {
        [void]$sb.AppendLine("## $($fr.File)")
        [void]$sb.AppendLine()
        if ($fr.AppliedFixes.Count -gt 0) {
            [void]$sb.AppendLine("**Auto-fixes $(if ($Apply) { 'applied' } else { 'that WOULD be applied with -Apply' }):**")
            foreach ($af in $fr.AppliedFixes) {
                [void]$sb.AppendLine("- $($af.Rule) x $($af.Count)")
            }
            [void]$sb.AppendLine()
        }
        if ($fr.RemainingHits.Count -gt 0) {
            [void]$sb.AppendLine("**Remaining hits needing human review:**")
            [void]$sb.AppendLine()
            foreach ($h in $fr.RemainingHits) {
                $codeEsc = ($h.Text -replace '\|', '\|') -replace '`', '\`'
                if ($codeEsc.Length -gt 160) { $codeEsc = $codeEsc.Substring(0, 157) + '...' }
                [void]$sb.AppendLine("- **L$($h.Line)** ``$($h.Member)`` - $($h.Message)")
                [void]$sb.AppendLine("  - Code: ``$codeEsc``")
                $advice = $h.Advice
                if (-not $advice) {
                    $advice = Get-ManualAdvice -Member $h.Member -Message $h.Message -Code $h.Text
                }
                if ($advice) {
                    [void]$sb.AppendLine("  - Advice:")
                    [void]$sb.AppendLine('    ```')
                    foreach ($aline in ($advice -replace "`r`n", "`n") -split "`n") {
                        [void]$sb.AppendLine("    $aline")
                    }
                    [void]$sb.AppendLine('    ```')
                }
            }
            [void]$sb.AppendLine()
        }
    }
}

$sb.ToString() | Set-Content -LiteralPath $Report -Encoding UTF8

Write-Host ""
Write-Host "=== Summary ===" -ForegroundColor Green
Write-Host "Mode:                     $mode"
Write-Host "Files scanned:            $($TargetFiles.Count)"
Write-Host "Files needing attention:  $($FileResults.Count)"
Write-Host "Auto-fix rewrites:        $TotalAutoFixes"
Write-Host "Remaining manual hits:    $TotalRemainingHits"
Write-Host "Report written to:       $Report" -ForegroundColor Yellow

if (-not $Apply -and $TotalAutoFixes -gt 0) {
    Write-Host ""
    Write-Host "This was a dry run. Re-run with -Apply to write the $TotalAutoFixes auto-fix(es) to disk." -ForegroundColor Magenta
}
