# Space Whale Item Generator
# Creates Transcendence ItemType definitions using generated assets
# Generates: Weapons, Devices, Armor, and Ammunition

param(
    [Parameter(Mandatory=$false)]
    [string]$AssetDir = "Output/SpaceWhaleAssets_HQ/Stage4_Final",
    
    [Parameter(Mandatory=$false)]
    [string]$OutputDir = "Output/Items",
    
    [Parameter(Mandatory=$false)]
    [ValidateSet("All", "Weapons", "Devices", "Armor", "Ammunition", "Reactors")]
    [string]$ItemType = "All",
    
    [Parameter(Mandatory=$false)]
    [int]$ItemCount = 6
)

$ErrorActionPreference = "Stop"

Write-Host "Space Whale Item Generator" -ForegroundColor Cyan
Write-Host "==========================" -ForegroundColor Cyan
Write-Host ""

# Check if asset directory exists
if (-not (Test-Path $AssetDir)) {
    Write-Host "ERROR: Asset directory not found: $AssetDir" -ForegroundColor Red
    Write-Host "Please run space_whale_quality_asset_generator.py first" -ForegroundColor Yellow
    exit 1
}

# Create output directory
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

Write-Host "Configuration:" -ForegroundColor Green
Write-Host "  Asset Directory: $AssetDir" -ForegroundColor Gray
Write-Host "  Output Directory: $OutputDir" -ForegroundColor Gray
Write-Host "  Item Type: $ItemType" -ForegroundColor Gray
Write-Host "  Item Count: $ItemCount per category" -ForegroundColor Gray
Write-Host ""

# ===== WEAPON GENERATION =====

function Generate-SpaceWhaleWeapons {
    Write-Host "[1/4] Generating Space Whale Weapons..." -ForegroundColor Yellow
    
    $weapons = @(
        @{
            name = "Bio-Pulse Cannon"
            unid = "0xE2000001"
            level = 4
            damage = "laser:3d6"
            fireRate = 15
            powerUse = 120
            description = "Fires concentrated bio-energy pulses harvested from space whale cellular structures."
            price = 4500
        },
        @{
            name = "Organic Plasma Launcher"
            unid = "0xE2000002"
            level = 5
            damage = "plasma:4d8"
            fireRate = 25
            powerUse = 200
            description = "Launches plasma spheres grown in bio-organic chambers."
            price = 8000
        },
        @{
            name = "Whale Song Resonator"
            unid = "0xE2000003"
            level = 6
            damage = "sonic:5d10"
            fireRate = 20
            powerUse = 180
            description = "Weaponizes space whale communication frequencies into devastating sonic waves."
            price = 12000
        },
        @{
            name = "Symbiotic Missile Pod"
            unid = "0xE2000004"
            level = 5
            damage = "kinetic:6d6+blast:2"
            fireRate = 30
            powerUse = 150
            description = "Fires living missiles that home in on targets using bio-sensing."
            price = 9500
        },
        @{
            name = "Bioluminescent Beam"
            unid = "0xE2000005"
            level = 7
            damage = "laser:8d6"
            fireRate = 10
            powerUse = 300
            description = "Continuous beam weapon powered by bio-luminescent organs."
            price = 18000
        },
        @{
            name = "Gill Vent Cannon"
            unid = "0xE2000006"
            level = 4
            damage = "thermo:3d8"
            fireRate = 12
            powerUse = 140
            description = "Expels superheated gas from synthetic gill vents."
            price = 5500
        }
    )
    
    $xmlOutput = @"
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TranscendenceModule [
$(foreach ($w in $weapons[0..($ItemCount-1)]) { "    <!ENTITY it$($w.name -replace '[\s-]','') `"$($w.unid)`">`n" })
    <!-- FX Resources -->
    <!ENTITY fxBioPulse "0xE2001000">
    <!ENTITY fxWhalesong "0xE2001001">
    <!ENTITY fxBioLuminescence "0xE2001002">
]>

<TranscendenceModule apiVersion="57">

<!-- ========================================
     SPACE WHALE WEAPONS
     Generated by SpaceWhaleItemGenerator.ps1
     ======================================== -->

"@

    foreach ($weapon in $weapons[0..($ItemCount-1)]) {
        $xmlOutput += @"
<!-- $($weapon.name) -->
<ItemType UNID="`&it$($weapon.name -replace '[\s-]','');"
    name="$($weapon.name)"
    level="$($weapon.level)"
    value="$($weapon.price)"
    frequency="uncommon"
    mass="2000"
    attributes="spaceWhale, bioWeapon, commonwealth">
    
    <Image imageID="&rsSpaceWhaleWeapons;" imageX="0" imageY="0" imageWidth="96" imageHeight="96"/>
    
    <Names definiteArticle="true" nouns="nouns"/>
    
    <Weapon
        type="projectile"
        damage="$($weapon.damage)"
        fireRate="$($weapon.fireRate)"
        powerUse="$($weapon.powerUse)"
        speed="100"
        lifetime="720"
        sound="&snLaserCannon;">
        
        <Configuration>
            <Shot/>
        </Configuration>
        
        <!-- Generated projectile using FX assets -->
        <Effect>
            <Orb
                style="smooth"
                intensity="50"
                radius="24"
                primaryColor="#4488ff"
                secondaryColor="#66ccff"
                lifetime="20"
            />
        </Effect>
        
        <!-- Impact effect -->
        <HitEffect>
            <Flare
                style="fadingBlast"
                radius="48"
                primaryColor="#4488ff"
                lifetime="12"
            />
        </HitEffect>
    </Weapon>
    
    <Language>
        <Text id="core.description">
            $($weapon.description)
        </Text>
    </Language>
</ItemType>

"@
    }
    
    $xmlOutput += "</TranscendenceModule>"
    
    $weaponFile = Join-Path $OutputDir "SpaceWhaleWeapons.xml"
    $xmlOutput | Set-Content $weaponFile
    
    Write-Host "  Generated $ItemCount weapons: $weaponFile" -ForegroundColor Green
}

# ===== DEVICE GENERATION =====

function Generate-SpaceWhaleDevices {
    Write-Host "[2/4] Generating Space Whale Devices..." -ForegroundColor Yellow
    
    $devices = @(
        @{
            name = "Bio-Regenerative Shield"
            unid = "0xE2000010"
            level = 5
            maxHP = 200
            regenRate = 8
            description = "Self-healing shield that mimics space whale cellular regeneration."
            price = 15000
        },
        @{
            name = "Symbiotic Repair System"
            unid = "0xE2000011"
            level = 6
            repairRate = 12
            description = "Living repair system that continuously heals hull damage."
            price = 20000
        },
        @{
            name = "Whale Heart Reactor"
            unid = "0xE2000012"
            level = 7
            powerGen = 500
            description = "Bio-reactor modeled after space whale metabolic organs."
            price = 35000
        },
        @{
            name = "Echo Location Scanner"
            unid = "0xE2000013"
            level = 4
            range = 150
            description = "Uses whale song frequencies to detect cloaked ships."
            price = 8000
        },
        @{
            name = "Adaptive Camouflage"
            unid = "0xE2000014"
            level = 6
            description = "Bio-mimetic skin that provides stealth capabilities."
            price = 25000
        },
        @{
            name = "Gill Drive Afterburner"
            unid = "0xE2000015"
            level = 5
            thrustBonus = 150
            description = "Propulsion system using bio-organic gill vent technology."
            price = 18000
        }
    )
    
    $xmlOutput = @"
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TranscendenceModule [
$(foreach ($d in $devices[0..($ItemCount-1)]) { "    <!ENTITY it$($d.name -replace '[\s-]','') `"$($d.unid)`">`n" })
]>

<TranscendenceModule apiVersion="57">

<!-- ========================================
     SPACE WHALE DEVICES
     Generated by SpaceWhaleItemGenerator.ps1
     ======================================== -->

"@

    foreach ($device in $devices[0..($ItemCount-1)]) {
        $xmlOutput += @"
<!-- $($device.name) -->
<ItemType UNID="`&it$($device.name -replace '[\s-]','');"
    name="$($device.name)"
    level="$($device.level)"
    value="$($device.price)"
    frequency="rare"
    mass="1500"
    attributes="spaceWhale, bioDevice, commonwealth">
    
    <Image imageID="&rsSpaceWhaleDevices;" imageX="0" imageY="0" imageWidth="96" imageHeight="96"/>
    
    <Names definiteArticle="true" nouns="nouns"/>
    
    <DeviceSlot criteria="*"/>
    
    <Language>
        <Text id="core.description">
            $($device.description)
        </Text>
    </Language>
</ItemType>

"@
    }
    
    $xmlOutput += "</TranscendenceModule>"
    
    $deviceFile = Join-Path $OutputDir "SpaceWhaleDevices.xml"
    $xmlOutput | Set-Content $deviceFile
    
    Write-Host "  Generated $ItemCount devices: $deviceFile" -ForegroundColor Green
}

# ===== ARMOR GENERATION =====

function Generate-SpaceWhaleArmor {
    Write-Host "[3/4] Generating Space Whale Armor..." -ForegroundColor Yellow
    
    $armors = @(
        @{
            name = "Living Carapace Plating"
            unid = "0xE2000020"
            level = 5
            hp = 180
            regen = 2
            description = "Self-healing armor grown from space whale cellular tissue."
            price = 12000
        },
        @{
            name = "Bio-Reactive Hull"
            unid = "0xE2000021"
            level = 6
            hp = 220
            regen = 3
            description = "Adaptive armor that hardens in response to damage types."
            price = 18000
        },
        @{
            name = "Symbiotic Scales"
            unid = "0xE2000022"
            level = 7
            hp = 280
            regen = 4
            description = "Interlocking bio-scales with extreme damage resistance."
            price = 28000
        },
        @{
            name = "Whale Skin Composite"
            unid = "0xE2000023"
            level = 4
            hp = 150
            regen = 1
            description = "Light armor combining synthetic whale skin with alloys."
            price = 8000
        },
        @{
            name = "Organic Ablative Coating"
            unid = "0xE2000024"
            level = 5
            hp = 200
            description = "Sacrificial bio-layer that regenerates between combats."
            price = 14000
        },
        @{
            name = "Leviathan Plate"
            unid = "0xE2000025"
            level = 8
            hp = 350
            regen = 5
            description = "Heavy armor forged from ancient leviathan remains."
            price = 45000
        }
    )
    
    $xmlOutput = @"
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TranscendenceModule [
$(foreach ($a in $armors[0..($ItemCount-1)]) { "    <!ENTITY it$($a.name -replace '[\s-]','') `"$($a.unid)`">`n" })
]>

<TranscendenceModule apiVersion="57">

<!-- ========================================
     SPACE WHALE ARMOR
     Generated by SpaceWhaleItemGenerator.ps1
     ======================================== -->

"@

    foreach ($armor in $armors[0..($ItemCount-1)]) {
        $xmlOutput += @"
<!-- $($armor.name) -->
<ItemType UNID="`&it$($armor.name -replace '[\s-]','');"
    name="$($armor.name)"
    level="$($armor.level)"
    value="$($armor.price)"
    frequency="rare"
    mass="5000"
    attributes="spaceWhale, bioArmor, commonwealth">
    
    <Image imageID="&rsSpaceWhaleArmor;" imageX="0" imageY="0" imageWidth="96" imageHeight="96"/>
    
    <Names definiteArticle="true" nouns="nouns"/>
    
    <Armor
        hitPoints="$($armor.hp)"
        hpBonus="+regenerate:$($armor.regen)"
        repairTech="6"
        installCost="500"
    />
    
    <Language>
        <Text id="core.description">
            $($armor.description)
        </Text>
    </Language>
</ItemType>

"@
    }
    
    $xmlOutput += "</TranscendenceModule>"
    
    $armorFile = Join-Path $OutputDir "SpaceWhaleArmor.xml"
    $xmlOutput | Set-Content $armorFile
    
    Write-Host "  Generated $ItemCount armor types: $armorFile" -ForegroundColor Green
}

# ===== REACTOR GENERATION =====

function Generate-SpaceWhaleReactors {
    Write-Host "[4/5] Generating Space Whale Reactors..." -ForegroundColor Yellow
    
    $reactors = @(
        @{
            name = "Bio-Organic Core Mk I"
            unid = "0xE2000040"
            level = 3
            powerGen = 300
            fuelEfficiency = 0.25
            description = "Basic bio-reactor using space whale cellular metabolism. Burns fuel efficiently through organic processes."
            price = 3000
        },
        @{
            name = "Symbiotic Heart Reactor"
            unid = "0xE2000041"
            level = 5
            powerGen = 600
            fuelEfficiency = 0.20
            description = "Mid-tier reactor modeled after space whale cardiac chambers. Exceptional fuel efficiency."
            price = 12000
        },
        @{
            name = "Leviathan Core Mk II"
            unid = "0xE2000042"
            level = 7
            powerGen = 1200
            fuelEfficiency = 0.15
            description = "Advanced bio-reactor using leviathan-class metabolic processes. Extreme power output."
            price = 35000
        },
        @{
            name = "Whale Song Resonance Core"
            unid = "0xE2000043"
            level = 6
            powerGen = 900
            fuelEfficiency = 0.18
            description = "Unique reactor that generates power from harmonic frequencies. Produces melodic hum."
            price = 20000
        },
        @{
            name = "Bioluminescent Matrix"
            unid = "0xE2000044"
            level = 4
            powerGen = 450
            fuelEfficiency = 0.22
            description = "Reactor using bio-luminescent organs for energy conversion. Glows softly in the dark."
            price = 7500
        },
        @{
            name = "Ancient Leviathan Heart"
            unid = "0xE2000045"
            level = 9
            powerGen = 2000
            fuelEfficiency = 0.10
            description = "Legendary reactor reverse-engineered from ancient leviathan remains. Unmatched power."
            price = 75000
        }
    )
    
    $xmlOutput = @"
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TranscendenceModule [
$(foreach ($r in $reactors[0..($ItemCount-1)]) { "    <!ENTITY it$($r.name -replace '[\s-]','') `"$($r.unid)`">`n" })
]>

<TranscendenceModule apiVersion="57">

<!-- ========================================
     SPACE WHALE REACTORS
     Generated by SpaceWhaleItemGenerator.ps1
     ======================================== -->

"@

    foreach ($reactor in $reactors[0..($ItemCount-1)]) {
        $xmlOutput += @"
<!-- $($reactor.name) -->
<ItemType UNID="`&it$($reactor.name -replace '[\s-]','');"
    name="$($reactor.name)"
    level="$($reactor.level)"
    value="$($reactor.price)"
    frequency="rare"
    mass="3000"
    attributes="spaceWhale, bioReactor, commonwealth">
    
    <Image imageID="&rsSpaceWhaleReactors;" imageX="0" imageY="0" imageWidth="96" imageHeight="96"/>
    
    <Names definiteArticle="true" nouns="nouns"/>
    
    <ReactorDevice
        maxPower="$($reactor.powerGen)"
        maxFuel="25000"
        fuelEfficiency="$($reactor.fuelEfficiency)"
        reactorEfficiency="100"
    />
    
    <Language>
        <Text id="core.description">
            $($reactor.description)
        </Text>
    </Language>
</ItemType>

"@
    }
    
    $xmlOutput += "</TranscendenceModule>"
    
    $reactorFile = Join-Path $OutputDir "SpaceWhaleReactors.xml"
    $xmlOutput | Set-Content $reactorFile
    
    Write-Host "  Generated $ItemCount reactors: $reactorFile" -ForegroundColor Green
}

# ===== AMMUNITION GENERATION =====

function Generate-SpaceWhaleAmmo {
    Write-Host "[5/5] Generating Space Whale Ammunition..." -ForegroundColor Yellow
    
    $ammo = @(
        @{
            name = "Bio-Missile Pack"
            unid = "0xE2000030"
            level = 5
            damage = "blast:4d10"
            count = 20
            description = "Living missiles with bio-tracking capabilities."
            price = 500
        },
        @{
            name = "Symbiotic Torpedoes"
            unid = "0xE2000031"
            level = 6
            damage = "blast:6d12"
            count = 10
            description = "Heavy torpedoes with living guidance systems."
            price = 1200
        },
        @{
            name = "Whale Oil Charges"
            unid = "0xE2000032"
            level = 4
            damage = "fire:3d8"
            count = 50
            description = "Incendiary charges using processed bio-fuel."
            price = 300
        }
    )
    
    $xmlOutput = @"
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TranscendenceModule [
$(foreach ($am in $ammo) { "    <!ENTITY it$($am.name -replace '[\s-]','') `"$($am.unid)`">`n" })
]>

<TranscendenceModule apiVersion="57">

<!-- ========================================
     SPACE WHALE AMMUNITION
     Generated by SpaceWhaleItemGenerator.ps1
     ======================================== -->

"@

    foreach ($ammunition in $ammo) {
        $xmlOutput += @"
<!-- $($ammunition.name) -->
<ItemType UNID="`&it$($ammunition.name -replace '[\s-]','');"
    name="$($ammunition.name) ($($ammunition.count))"
    level="$($ammunition.level)"
    value="$($ammunition.price)"
    frequency="common"
    mass="100"
    attributes="spaceWhale, ammunition">
    
    <Image imageID="&rsSpaceWhaleAmmo;" imageX="0" imageY="0" imageWidth="96" imageHeight="96"/>
    
    <Missile
        damage="$($ammunition.damage)"
        missileSpeed="50"
        interaction="100"
        hitPoints="10"
        maneuverability="8"
        maneuverRate="5"
    />
    
    <Language>
        <Text id="core.description">
            $($ammunition.description)
        </Text>
    </Language>
</ItemType>

"@
    }
    
    $xmlOutput += "</TranscendenceModule>"
    
    $ammoFile = Join-Path $OutputDir "SpaceWhaleAmmunition.xml"
    $xmlOutput | Set-Content $ammoFile
    
    Write-Host "  Generated $($ammo.Count) ammunition types: $ammoFile" -ForegroundColor Green
}

# ===== REGISTRY GENERATION =====

function Generate-ItemRegistry {
    Write-Host ""
    Write-Host "Generating Item Registry..." -ForegroundColor Yellow
    
    $registry = @{
        version = "1.0.0"
        generated = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"
        itemCategories = @{
            weapons = "$ItemCount generated"
            devices = "$ItemCount generated"
            armor = "$ItemCount generated"
            reactors = "$ItemCount generated"
            ammunition = "3 generated"
        }
        integration = @{
            xmlFiles = @(
                "SpaceWhaleWeapons.xml"
                "SpaceWhaleDevices.xml"
                "SpaceWhaleArmor.xml"
                "SpaceWhaleReactors.xml"
                "SpaceWhaleAmmunition.xml"
            )
            assetSource = $AssetDir
            unidRange = "0xE2000000 - 0xE2000999"
        }
        notes = @(
            "All items use bio-organic space whale technology"
            "Items are compatible with Commonwealth factions"
            "Assets reference Stage4_Final from quality generator"
            "UNIDs are reserved in range 0xE2000000+"
        )
    }
    
    $registryPath = Join-Path $OutputDir "item_registry.json"
    $registry | ConvertTo-Json -Depth 10 | Set-Content $registryPath
    
    Write-Host "  Registry created: $registryPath" -ForegroundColor Green
}

# ===== MAIN EXECUTION =====

try {
    if ($ItemType -eq "All" -or $ItemType -eq "Weapons") {
        Generate-SpaceWhaleWeapons
    }
    
    if ($ItemType -eq "All" -or $ItemType -eq "Devices") {
        Generate-SpaceWhaleDevices
    }
    
    if ($ItemType -eq "All" -or $ItemType -eq "Armor") {
        Generate-SpaceWhaleArmor
    }
    
    if ($ItemType -eq "All" -or $ItemType -eq "Reactors") {
        Generate-SpaceWhaleReactors
    }
    
    if ($ItemType -eq "All" -or $ItemType -eq "Ammunition") {
        Generate-SpaceWhaleAmmo
    }
    
    Generate-ItemRegistry
    
    Write-Host ""
    Write-Host "============================================" -ForegroundColor Green
    Write-Host "Item Generation Complete!" -ForegroundColor Green
    Write-Host "============================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Output Directory: $OutputDir" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Generated Files:" -ForegroundColor Yellow
    if ($ItemType -eq "All" -or $ItemType -eq "Weapons") {
        Write-Host "  - SpaceWhaleWeapons.xml ($ItemCount weapons)" -ForegroundColor Gray
    }
    if ($ItemType -eq "All" -or $ItemType -eq "Devices") {
        Write-Host "  - SpaceWhaleDevices.xml ($ItemCount devices)" -ForegroundColor Gray
    }
    if ($ItemType -eq "All" -or $ItemType -eq "Armor") {
        Write-Host "  - SpaceWhaleArmor.xml ($ItemCount armor types)" -ForegroundColor Gray
    }
    if ($ItemType -eq "All" -or $ItemType -eq "Reactors") {
        Write-Host "  - SpaceWhaleReactors.xml ($ItemCount reactors)" -ForegroundColor Gray
    }
    if ($ItemType -eq "All" -or $ItemType -eq "Ammunition") {
        Write-Host "  - SpaceWhaleAmmunition.xml (3 ammo types)" -ForegroundColor Gray
    }
    Write-Host "  - item_registry.json (metadata)" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Next Steps:" -ForegroundColor Yellow
    Write-Host "  1. Review generated XML files" -ForegroundColor Gray
    Write-Host "  2. Copy to your Transcendence extension" -ForegroundColor Gray
    Write-Host "  3. Add image resources for item icons" -ForegroundColor Gray
    Write-Host "  4. Test in-game" -ForegroundColor Gray
    Write-Host ""
    
} catch {
    Write-Host ""
    Write-Host "ERROR: Item generation failed" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    Write-Host ""
    exit 1
}
