<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QudLab.Core\QudLab.Core.csproj" />
    <ProjectReference Include="..\QudLab.Indexer\QudLab.Indexer.csproj" />
    <ProjectReference Include="..\QudLab.RoslynCompile\QudLab.RoslynCompile.csproj" />
    <ProjectReference Include="..\QudLab.Simulator\QudLab.Simulator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
