# Emit-TerrariaContentModPack.ps1
# Drop-in tModLoader 1.4+ packs for Weapon / Projectile / Item / Creature.

function Get-SafeCsIdent {
    param([string]$Name)
    $s = ($Name -replace '[^A-Za-z0-9_]', '')
    if ([string]::IsNullOrWhiteSpace($s)) { $s = "Asset" }
    if ($s[0] -match '\d') { $s = "A$s" }
    return $s
}

function Invoke-TerrariaArt {
    param([Parameter(Mandatory)][string[]]$ArtArgs)
    $py = (Get-Command python -ErrorAction SilentlyContinue).Source
    if (-not $py) { throw "python not on PATH" }
    $script = Join-Path $PSScriptRoot "terraria_procedural_art.py"
    & $py $script @ArtArgs
    if ($LASTEXITCODE -ne 0) { throw "terraria_procedural_art.py failed" }
}

function New-TerrariaModScaffold {
    param(
        [string]$ModRoot,
        [string]$ModName,
        [string]$DisplayName,
        [string]$Description,
        [string]$AuthorNote
    )
    foreach ($sub in @(
            $ModRoot,
            (Join-Path $ModRoot "Content\Items"),
            (Join-Path $ModRoot "Content\Projectiles"),
            (Join-Path $ModRoot "Content\NPCs"),
            (Join-Path $ModRoot "Localization")
        )) {
        if (-not (Test-Path -LiteralPath $sub)) {
            New-Item -ItemType Directory -Path $sub -Force | Out-Null
        }
    }
    @"
displayName = AAMT $DisplayName
author = AAMT Terraria Asset Generator
version = 0.1.0
hideCode = false
hideResources = false
includeSource = true
buildIgnore = *.user, obj\*, bin\*, .vs\*, .git\*
"@ | Set-Content -LiteralPath (Join-Path $ModRoot "build.txt") -Encoding UTF8

    @"
$DisplayName — generated by AAMT TerrariaAssetGenerator.

$Description

$AuthorNote
"@ | Set-Content -LiteralPath (Join-Path $ModRoot "description.txt") -Encoding UTF8

    @"
using Terraria.ModLoader;

namespace $ModName
{
	public class $ModName : Mod
	{
	}
}
"@ | Set-Content -LiteralPath (Join-Path $ModRoot "$ModName.cs") -Encoding UTF8
}

function Emit-TerrariaWeaponMod {
    param(
        [string]$Name,
        [string]$OutputDir,
        [string]$Description = "",
        [string]$Color = "#c8c8ff",
        [ValidateSet("Melee", "Ranged", "Magic")][string]$DamageClass = "Melee",
        [int]$Damage = 24,
        [int]$UseTime = 20,
        [int]$Size = 40
    )
    $safe = Get-SafeCsIdent $Name
    $modName = "AamtWeapon_$safe"
    $modRoot = Join-Path $OutputDir $modName
    $itemClass = "${safe}Weapon"
    $projClass = "${safe}Shot"
    $display = ($Name -replace '([a-z])([A-Z])', '$1 $2')
    New-TerrariaModScaffold -ModRoot $modRoot -ModName $modName -DisplayName $display `
        -Description $Description -AuthorNote "Craft at an Anvil. $($DamageClass) weapon."

    $itemDir = Join-Path $modRoot "Content\Items"
    $projDir = Join-Path $modRoot "Content\Projectiles"
    $itemPng = Join-Path $itemDir "$itemClass.png"
    $projPng = Join-Path $projDir "$projClass.png"
    $style = switch ($DamageClass) { "Ranged" { "bow" } "Magic" { "staff" } default { "sword" } }
    Invoke-TerrariaArt -ArtArgs @("weapon", "--path", $itemPng, "--size", "$Size", "--color", $Color, "--style", $style)
    Copy-Item $itemPng (Join-Path $modRoot "icon.png") -Force

    $needsProj = $DamageClass -ne "Melee"
    if ($needsProj) {
        Invoke-TerrariaArt -ArtArgs @("projectile", "--path", $projPng, "--size", "32", "--color", $Color, "--frames", "1")
    }

    $dmgType = switch ($DamageClass) {
        "Ranged" { "DamageClass.Ranged" }
        "Magic" { "DamageClass.Magic" }
        default { "DamageClass.Melee" }
    }
    $useStyle = switch ($DamageClass) {
        "Ranged" { "ItemUseStyleID.Shoot" }
        "Magic" { "ItemUseStyleID.Shoot" }
        default { "ItemUseStyleID.Swing" }
    }

    $shootBlock = ""
    $extraUsings = ""
    if ($needsProj) {
        $extraUsings = "using ${modName}.Content.Projectiles;`n"
        $shootBlock = @"

			Item.shoot = ModContent.ProjectileType<$projClass>();
			Item.shootSpeed = 10f;
			Item.noMelee = true;
"@
        if ($DamageClass -eq "Magic") {
            $shootBlock += "`n`t`t`tItem.mana = 6;"
        }
        if ($DamageClass -eq "Ranged") {
            $shootBlock += "`n`t`t`tItem.useAmmo = AmmoID.Arrow;"
        }
    }

    @"
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;
$extraUsings
namespace ${modName}.Content.Items
{
	public class $itemClass : ModItem
	{
		public override void SetDefaults() {
			Item.width = $Size;
			Item.height = $Size;
			Item.rare = ItemRarityID.Orange;
			Item.value = Item.buyPrice(gold: 1);
			Item.useTime = $UseTime;
			Item.useAnimation = $UseTime;
			Item.useStyle = $useStyle;
			Item.autoReuse = true;
			Item.UseSound = SoundID.Item1;
			Item.damage = $Damage;
			Item.knockBack = 4f;
			Item.DamageType = $dmgType;$shootBlock
		}

		public override void AddRecipes() {
			CreateRecipe()
				.AddIngredient(ItemID.IronBar, 10)
				.AddIngredient(ItemID.FallenStar, 1)
				.AddTile(TileID.Anvils)
				.Register();
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $itemDir "$itemClass.cs") -Encoding UTF8

    if ($needsProj) {
        @"
using Microsoft.Xna.Framework;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace ${modName}.Content.Projectiles
{
	public class $projClass : ModProjectile
	{
		public override void SetDefaults() {
			Projectile.width = 16;
			Projectile.height = 16;
			Projectile.friendly = true;
			Projectile.hostile = false;
			Projectile.DamageType = $dmgType;
			Projectile.penetrate = 1;
			Projectile.timeLeft = 180;
			Projectile.ignoreWater = true;
			Projectile.tileCollide = true;
			Projectile.aiStyle = 1;
			AIType = ProjectileID.Bullet;
		}

		public override void AI() {
			Lighting.AddLight(Projectile.Center, 0.3f, 0.4f, 0.8f);
			if (Main.rand.NextBool(3)) {
				Dust.NewDust(Projectile.position, Projectile.width, Projectile.height, DustID.MagicMirror, 0f, 0f, 100, default, 0.8f);
			}
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $projDir "$projClass.cs") -Encoding UTF8
    }

    $locExtra = ""
    if ($needsProj) {
        # no projectile display name required in 1.4 hjson for basic
    }
    @"
Mods: {
	${modName}: {
		ItemName: {
			${itemClass}: $display
		}
		ItemTooltip: {
			${itemClass}: $DamageClass weapon. $Description
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $modRoot "Localization\en-US_Mods.$modName.hjson") -Encoding UTF8

    @"
# $modName

| Piece | Role |
|-------|------|
| ``$itemClass`` | $($DamageClass) weapon ($Damage damage) |
$(if ($needsProj) { "| ``$projClass`` | Fired projectile |" } else { "" })

Craft at an Anvil: 10 Iron Bar + 1 Fallen Star.
"@ | Set-Content -LiteralPath (Join-Path $modRoot "README.md") -Encoding UTF8

    Write-Host "[Created] Weapon mod: $modRoot" -ForegroundColor Green
    return @{ ModRoot = $modRoot; ModName = $modName; ItemClass = $itemClass }
}

function Emit-TerrariaProjectileMod {
    param(
        [string]$Name,
        [string]$OutputDir,
        [string]$Description = "",
        [string]$Color = "#88ccff",
        [int]$Damage = 18,
        [int]$Size = 32,
        [switch]$WithAmmoItem
    )
    $safe = Get-SafeCsIdent $Name
    $modName = "AamtProjectile_$safe"
    $modRoot = Join-Path $OutputDir $modName
    $projClass = "${safe}Projectile"
    $ammoClass = "${safe}Ammo"
    $display = ($Name -replace '([a-z])([A-Z])', '$1 $2')
    New-TerrariaModScaffold -ModRoot $modRoot -ModName $modName -DisplayName $display `
        -Description $Description -AuthorNote "Standalone projectile(+ optional ammo item)."

    $projDir = Join-Path $modRoot "Content\Projectiles"
    $itemDir = Join-Path $modRoot "Content\Items"
    $projPng = Join-Path $projDir "$projClass.png"
    Invoke-TerrariaArt -ArtArgs @("projectile", "--path", $projPng, "--size", "$Size", "--color", $Color, "--frames", "2")
    # icon from first frame
    $py = (Get-Command python -ErrorAction SilentlyContinue).Source
    if ($py) {
        & $py -c "from PIL import Image; im=Image.open(r'$projPng'); im.crop((0,0,$Size,$Size)).save(r'$(Join-Path $modRoot 'icon.png')')"
    } else {
        Copy-Item $projPng (Join-Path $modRoot "icon.png") -Force
    }

    @"
using Microsoft.Xna.Framework;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace ${modName}.Content.Projectiles
{
	public class $projClass : ModProjectile
	{
		public override void SetStaticDefaults() {
			Main.projFrames[Type] = 2;
		}

		public override void SetDefaults() {
			Projectile.width = $Size;
			Projectile.height = $Size;
			Projectile.friendly = true;
			Projectile.hostile = false;
			Projectile.DamageType = DamageClass.Ranged;
			Projectile.penetrate = 2;
			Projectile.timeLeft = 240;
			Projectile.ignoreWater = true;
			Projectile.tileCollide = true;
			Projectile.aiStyle = 1;
			AIType = ProjectileID.Bullet;
		}

		public override void AI() {
			if (++Projectile.frameCounter >= 5) {
				Projectile.frameCounter = 0;
				Projectile.frame = ++Projectile.frame % Main.projFrames[Type];
			}
			Lighting.AddLight(Projectile.Center, 0.2f, 0.5f, 0.9f);
		}

		public override void OnHitNPC(NPC target, NPC.HitInfo hit, int damageDone) {
			target.AddBuff(BuffID.OnFire, 60);
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $projDir "$projClass.cs") -Encoding UTF8

    $ammoLoc = ""
    if ($WithAmmoItem) {
        $ammoPng = Join-Path $itemDir "$ammoClass.png"
        Invoke-TerrariaArt -ArtArgs @("item", "--path", $ammoPng, "--size", "24", "--color", $Color, "--kind", "material")
        @"
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;
using ${modName}.Content.Projectiles;

namespace ${modName}.Content.Items
{
	public class $ammoClass : ModItem
	{
		public override void SetDefaults() {
			Item.width = 16;
			Item.height = 16;
			Item.maxStack = 9999;
			Item.consumable = true;
			Item.ammo = AmmoID.Bullet;
			Item.shoot = ModContent.ProjectileType<$projClass>();
			Item.damage = $Damage;
			Item.DamageType = DamageClass.Ranged;
			Item.rare = ItemRarityID.Blue;
			Item.value = Item.buyPrice(copper: 50);
		}

		public override void AddRecipes() {
			CreateRecipe(50)
				.AddIngredient(ItemID.MusketBall, 50)
				.AddIngredient(ItemID.FallenStar, 1)
				.AddTile(TileID.Anvils)
				.Register();
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $itemDir "$ammoClass.cs") -Encoding UTF8
        $ammoLoc = @"

		ItemName: {
			${ammoClass}: $display Ammo
		}
		ItemTooltip: {
			${ammoClass}: Fires $display. $Description
		}
"@
    }

    @"
Mods: {
	${modName}: {$ammoLoc
	}
}
"@ | Set-Content -LiteralPath (Join-Path $modRoot "Localization\en-US_Mods.$modName.hjson") -Encoding UTF8

    @"
# $modName

Projectile ``$projClass`` ($Damage base when used as ammo).
$(if ($WithAmmoItem) { "Ammo item ``$ammoClass`` crafts 50 from Musket Balls + Fallen Star." } else { "Reference from another weapon via ``ModContent.ProjectileType<$projClass>()``." })
"@ | Set-Content -LiteralPath (Join-Path $modRoot "README.md") -Encoding UTF8

    Write-Host "[Created] Projectile mod: $modRoot" -ForegroundColor Green
    return @{ ModRoot = $modRoot; ModName = $modName; ProjectileClass = $projClass }
}

function Emit-TerrariaItemMod {
    param(
        [string]$Name,
        [string]$OutputDir,
        [string]$Description = "",
        [string]$Color = "#88ffaa",
        [ValidateSet("Material", "Consumable", "Accessory")][string]$ItemKind = "Material",
        [int]$Size = 32
    )
    $safe = Get-SafeCsIdent $Name
    $modName = "AamtItem_$safe"
    $modRoot = Join-Path $OutputDir $modName
    $itemClass = "${safe}Item"
    $display = ($Name -replace '([a-z])([A-Z])', '$1 $2')
    New-TerrariaModScaffold -ModRoot $modRoot -ModName $modName -DisplayName $display `
        -Description $Description -AuthorNote "Kind: $ItemKind"

    $itemDir = Join-Path $modRoot "Content\Items"
    $png = Join-Path $itemDir "$itemClass.png"
    $artKind = switch ($ItemKind) { "Consumable" { "potion" } "Accessory" { "accessory" } default { "material" } }
    Invoke-TerrariaArt -ArtArgs @("item", "--path", $png, "--size", "$Size", "--color", $Color, "--kind", $artKind)
    Copy-Item $png (Join-Path $modRoot "icon.png") -Force

    $defaultsExtra = switch ($ItemKind) {
        "Consumable" {
            @"

			Item.useStyle = ItemUseStyleID.DrinkLiquid;
			Item.useAnimation = 17;
			Item.useTime = 17;
			Item.useTurn = true;
			Item.UseSound = SoundID.Item3;
			Item.consumable = true;
			Item.maxStack = 9999;
			Item.buffType = BuffID.Regeneration;
			Item.buffTime = 3600;
"@
        }
        "Accessory" {
            @"

			Item.accessory = true;
			Item.maxStack = 1;
"@
        }
        default {
            @"

			Item.maxStack = 9999;
"@
        }
    }

    $updateAcc = ""
    if ($ItemKind -eq "Accessory") {
        $updateAcc = @"

		public override void UpdateAccessory(Player player, bool hideVisual) {
			player.GetDamage(DamageClass.Generic) += 0.05f;
			player.moveSpeed += 0.05f;
		}
"@
    }

    @"
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace ${modName}.Content.Items
{
	public class $itemClass : ModItem
	{
		public override void SetDefaults() {
			Item.width = $Size;
			Item.height = $Size;
			Item.rare = ItemRarityID.Green;
			Item.value = Item.buyPrice(silver: 25);$defaultsExtra
		}
$updateAcc
		public override void AddRecipes() {
			CreateRecipe()
				.AddIngredient(ItemID.FallenStar, 2)
				.AddIngredient(ItemID.Gel, 5)
				.AddTile(TileID.WorkBenches)
				.Register();
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $itemDir "$itemClass.cs") -Encoding UTF8

    @"
Mods: {
	${modName}: {
		ItemName: {
			${itemClass}: $display
		}
		ItemTooltip: {
			${itemClass}: $ItemKind. $Description
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $modRoot "Localization\en-US_Mods.$modName.hjson") -Encoding UTF8

    @"
# $modName

``$itemClass`` — $ItemKind item. Craft at Work Bench (2 Fallen Star + 5 Gel).
"@ | Set-Content -LiteralPath (Join-Path $modRoot "README.md") -Encoding UTF8

    Write-Host "[Created] Item mod: $modRoot" -ForegroundColor Green
    return @{ ModRoot = $modRoot; ModName = $modName; ItemClass = $itemClass }
}

function Emit-TerrariaCreatureMod {
    param(
        [string]$Name,
        [string]$OutputDir,
        [string]$Description = "",
        [string]$Color = "#66aa66",
        [int]$Life = 80,
        [int]$Damage = 12,
        [int]$Defense = 6,
        [int]$Size = 40,
        [int]$Frames = 4
    )
    $safe = Get-SafeCsIdent $Name
    $modName = "AamtCreature_$safe"
    $modRoot = Join-Path $OutputDir $modName
    $npcClass = "${safe}Creature"
    $bannerClass = "${safe}Banner"
    $display = ($Name -replace '([a-z])([A-Z])', '$1 $2')
    New-TerrariaModScaffold -ModRoot $modRoot -ModName $modName -DisplayName $display `
        -Description $Description -AuthorNote "Hostile NPC + banner item."

    $npcDir = Join-Path $modRoot "Content\NPCs"
    $itemDir = Join-Path $modRoot "Content\Items"
    if (-not (Test-Path $npcDir)) { New-Item -ItemType Directory -Path $npcDir -Force | Out-Null }

    $npcPng = Join-Path $npcDir "$npcClass.png"
    $bannerPng = Join-Path $itemDir "$bannerClass.png"
    Invoke-TerrariaArt -ArtArgs @("creature", "--path", $npcPng, "--size", "$Size", "--color", $Color, "--frames", "$Frames")
    Invoke-TerrariaArt -ArtArgs @("item", "--path", $bannerPng, "--size", "24", "--color", $Color, "--kind", "material")
    $py = (Get-Command python -ErrorAction SilentlyContinue).Source
    if ($py) {
        & $py -c "from PIL import Image; im=Image.open(r'$npcPng'); im.crop((0,0,$Size,$Size)).save(r'$(Join-Path $modRoot 'icon.png')')"
    }

    @"
using Terraria;
using Terraria.GameContent.Bestiary;
using Terraria.GameContent.ItemDropRules;
using Terraria.ID;
using Terraria.ModLoader;
using Terraria.ModLoader.Utilities;
using ${modName}.Content.Items;

namespace ${modName}.Content.NPCs
{
	public class $npcClass : ModNPC
	{
		public override void SetStaticDefaults() {
			Main.npcFrameCount[Type] = $Frames;
		}

		public override void SetDefaults() {
			NPC.width = $Size;
			NPC.height = $Size;
			NPC.damage = $Damage;
			NPC.defense = $Defense;
			NPC.lifeMax = $Life;
			NPC.HitSound = SoundID.NPCHit1;
			NPC.DeathSound = SoundID.NPCDeath1;
			NPC.value = 50f;
			NPC.knockBackResist = 0.5f;
			NPC.aiStyle = 3; // Fighter
			AIType = NPCID.GoblinScout;
			AnimationType = NPCID.GoblinScout;
			Banner = Type;
			BannerItem = ModContent.ItemType<$bannerClass>();
		}

		public override float SpawnChance(NPCSpawnInfo spawnInfo) {
			return SpawnCondition.OverworldDay.Chance * 0.1f;
		}

		public override void SetBestiary(BestiaryDatabase database, BestiaryEntry bestiaryEntry) {
			bestiaryEntry.Info.AddRange(new IBestiaryInfoElement[] {
				BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Surface,
				new FlavorTextBestiaryInfoElement("$Description")
			});
		}

		public override void ModifyNPCLoot(NPCLoot npcLoot) {
			npcLoot.Add(ItemDropRule.Common(ItemID.Gel, 1, 1, 3));
			npcLoot.Add(ItemDropRule.Common(ModContent.ItemType<$bannerClass>(), 50));
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $npcDir "$npcClass.cs") -Encoding UTF8

    @"
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace ${modName}.Content.Items
{
	public class $bannerClass : ModItem
	{
		public override void SetDefaults() {
			Item.width = 12;
			Item.height = 28;
			Item.maxStack = 9999;
			Item.useTurn = true;
			Item.autoReuse = true;
			Item.useAnimation = 15;
			Item.useTime = 10;
			Item.useStyle = ItemUseStyleID.Swing;
			Item.consumable = true;
			Item.rare = ItemRarityID.Blue;
			Item.value = Item.buyPrice(silver: 10);
			Item.createTile = TileID.Banners; // placeholder placeable; swap for custom banner tile if desired
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $itemDir "$bannerClass.cs") -Encoding UTF8

    @"
Mods: {
	${modName}: {
		NPCName: {
			${npcClass}: $display
		}
		ItemName: {
			${bannerClass}: $display Banner
		}
		ItemTooltip: {
			${bannerClass}: Trophy banner for $display.
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $modRoot "Localization\en-US_Mods.$modName.hjson") -Encoding UTF8

    @"
# $modName

| Piece | Role |
|-------|------|
| ``$npcClass`` | Hostile fighter NPC ($Life HP, $Damage dmg) |
| ``$bannerClass`` | Banner drop / placeable |

Spawns on surface day (10% of overworld day chance).
"@ | Set-Content -LiteralPath (Join-Path $modRoot "README.md") -Encoding UTF8

    Write-Host "[Created] Creature mod: $modRoot" -ForegroundColor Green
    return @{ ModRoot = $modRoot; ModName = $modName; NpcClass = $npcClass }
}
