# Emit-TerrariaPortalModPack.ps1
# Writes a drop-in tModLoader 1.4+ mod pack for one portal (gameplay + art paths).
# Dot-sourced / invoked from TerrariaPortalGenerator.ps1

function Get-SafeCsIdent {
    param([string]$Name)
    $s = ($Name -replace '[^A-Za-z0-9_]', '')
    if ([string]::IsNullOrWhiteSpace($s)) { $s = "Portal" }
    if ($s[0] -match '\d') { $s = "P$s" }
    return $s
}

function Emit-TerrariaPortalModPack {
    param(
        [Parameter(Mandatory)][string]$PortalName,
        [Parameter(Mandatory)][string]$PortalDir,
        [Parameter(Mandatory)][string]$Description,
        [Parameter(Mandatory)][string]$Preset,
        [Parameter(Mandatory)][int]$TileSize,
        [Parameter(Mandatory)][int[]]$CoreRgb,
        [Parameter(Mandatory)][int[]]$RimRgb,
        [Parameter(Mandatory)][int[]]$AccentRgb,
        [Parameter(Mandatory)][string]$MotionPattern,
        [Parameter(Mandatory)][int]$ParticleCount,
        [Parameter(Mandatory)][float]$DistortStrength,
        [Parameter(Mandatory)][float]$WaveFrequency,
        [Parameter(Mandatory)][float]$ChromaticAberration,
        [string]$ProfileJsonPath = "",
        [string]$BaseTexturePath = "",
        [switch]$Animated,
        [int]$AnimationFrames = 4
    )

    $safe = Get-SafeCsIdent -Name $PortalName
    $modName = "AamtPortal_$safe"
    $itemClass = "${safe}PortalItem"
    $tileClass = "${safe}PortalTile"
    $systemClass = "${safe}PortalSystem"
    $displayName = ($PortalName -replace '([a-z])([A-Z])', '$1 $2') + " Portal"

    $modRoot = Join-Path $PortalDir $modName
    $itemDir = Join-Path $modRoot "Content\Items"
    $tileDir = Join-Path $modRoot "Content\Tiles"
    $sysDir = Join-Path $modRoot "Content\Systems"
    $locDir = Join-Path $modRoot "Localization"
    $dataDir = Join-Path $modRoot "Data"
    foreach ($d in @($modRoot, $itemDir, $tileDir, $sysDir, $locDir, $dataDir)) {
        if (-not (Test-Path -LiteralPath $d)) {
            New-Item -ItemType Directory -Path $d -Force | Out-Null
        }
    }

    # --- build.txt ---
    @"
displayName = AAMT $displayName
author = AAMT Terraria Portal Generator
version = 0.1.0
homepage = 
hideCode = false
hideResources = false
includeSource = true
buildIgnore = *.user, obj\*, bin\*, .vs\*, .git\*
"@ | Set-Content -LiteralPath (Join-Path $modRoot "build.txt") -Encoding UTF8

    # --- description.txt ---
    @"
$displayName — generated by AAMT TerrariaPortalGenerator.

Craft the portal item (Glass + Fallen Star), place the tile, stand near it for particle FX,
right-click the tile to recall to your spawn / bed.

Preset: $Preset
$Description
"@ | Set-Content -LiteralPath (Join-Path $modRoot "description.txt") -Encoding UTF8

    # --- profile data ---
    if ($ProfileJsonPath -and (Test-Path -LiteralPath $ProfileJsonPath)) {
        Copy-Item -LiteralPath $ProfileJsonPath -Destination (Join-Path $dataDir "${safe}_profile.json") -Force
    }

    # --- textures into Content paths ---
    $tileTex = Join-Path $tileDir "$tileClass.png"
    $itemTex = Join-Path $itemDir "$itemClass.png"
    $iconTex = Join-Path $modRoot "icon.png"
    if ($BaseTexturePath -and (Test-Path -LiteralPath $BaseTexturePath)) {
        Copy-Item -LiteralPath $BaseTexturePath -Destination $tileTex -Force
        # Item icon: reuse base (or first frame if we had a strip)
        Copy-Item -LiteralPath $BaseTexturePath -Destination $itemTex -Force
        Copy-Item -LiteralPath $BaseTexturePath -Destination $iconTex -Force
        $extractPy = Join-Path $PSScriptRoot "extract_portal_item.py"
        if (Test-Path -LiteralPath $extractPy) {
            $py = (Get-Command python -ErrorAction SilentlyContinue).Source
            if ($py) {
                & $py $extractPy $BaseTexturePath $itemTex 2>$null
                if (Test-Path -LiteralPath $itemTex) {
                    Copy-Item -LiteralPath $itemTex -Destination $iconTex -Force
                }
            }
        }
    }

    $r = $CoreRgb[0]; $g = $CoreRgb[1]; $b = $CoreRgb[2]
    $rr = $RimRgb[0]; $rg = $RimRgb[1]; $rb = $RimRgb[2]
    $lightR = [math]::Round($r / 255.0, 3)
    $lightG = [math]::Round($g / 255.0, 3)
    $lightB = [math]::Round($b / 255.0, 3)
    $animFrames = if ($Animated) { [math]::Max(1, $AnimationFrames) } else { 1 }
    $animateTileBody = if ($animFrames -le 1) {
        "frame = 0;"
    } else {
        @"
			if (++frameCounter >= 8) {
				frameCounter = 0;
				frame = ++frame % $animFrames;
			}
"@
    }

    # --- Mod entry ---
    @"
using Terraria.ModLoader;

namespace $modName
{
	public class $modName : Mod
	{
	}
}
"@ | Set-Content -LiteralPath (Join-Path $modRoot "$modName.cs") -Encoding UTF8

    # --- Item (placeable + craftable) ---
    @"
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;
using ${modName}.Content.Tiles;

namespace ${modName}.Content.Items
{
	public class $itemClass : ModItem
	{
		public override void SetDefaults() {
			Item.width = $TileSize;
			Item.height = $TileSize;
			Item.maxStack = 9999;
			Item.useTurn = true;
			Item.autoReuse = true;
			Item.useAnimation = 15;
			Item.useTime = 10;
			Item.useStyle = ItemUseStyleID.Swing;
			Item.consumable = true;
			Item.value = Item.buyPrice(silver: 50);
			Item.rare = ItemRarityID.Orange;
			Item.createTile = ModContent.TileType<$tileClass>();
		}

		public override void AddRecipes() {
			CreateRecipe()
				.AddIngredient(ItemID.Glass, 20)
				.AddIngredient(ItemID.FallenStar, 3)
				.AddTile(TileID.WorkBenches)
				.Register();
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $itemDir "$itemClass.cs") -Encoding UTF8

    # --- Tile (light + animate + right-click recall) ---
    @"
using Microsoft.Xna.Framework;
using Terraria;
using Terraria.Audio;
using Terraria.DataStructures;
using Terraria.Enums;
using Terraria.ID;
using Terraria.Localization;
using Terraria.ModLoader;
using Terraria.ObjectData;
using ${modName}.Content.Systems;

namespace ${modName}.Content.Tiles
{
	public class $tileClass : ModTile
	{
		public override void SetStaticDefaults() {
			Main.tileFrameImportant[Type] = true;
			Main.tileNoAttach[Type] = true;
			Main.tileLavaDeath[Type] = true;
			Main.tileLighted[Type] = true;
			Main.tileSolid[Type] = false;

			TileObjectData.newTile.CopyFrom(TileObjectData.Style1x1);
			TileObjectData.newTile.StyleHorizontal = true;
			TileObjectData.newTile.LavaDeath = true;
			TileObjectData.newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, TileObjectData.newTile.Width, 0);
			TileObjectData.addTile(Type);

			AddMapEntry(new Color($rr, $rg, $rb), Language.GetText("Mods.${modName}.Tiles.${tileClass}.MapEntry"));
			DustType = DustID.MagicMirror;
			HitSound = SoundID.Dig;
		}

		public override void ModifyLight(int i, int j, ref float r, ref float g, ref float b) {
			r = ${lightR}f;
			g = ${lightG}f;
			b = ${lightB}f;
		}

		public override void AnimateTile(ref int frame, ref int frameCounter) {
$animateTileBody
		}

		public override void NearbyEffects(int i, int j, bool closer) {
			if (!closer) return;
			${systemClass}.SpawnNearTile(i, j);
		}

		public override bool RightClick(int i, int j) {
			Player player = Main.LocalPlayer;
			if (player.whoAmI != Main.myPlayer) return true;

			player.RemoveAllGrapplingHooks();
			player.Spawn(PlayerSpawnContext.RecallFromItem);
			SoundEngine.PlaySound(SoundID.Item6, player.Center);
			for (int d = 0; d < 20; d++) {
				Dust.NewDust(player.position, player.width, player.height, DustID.MagicMirror, 0f, 0f, 150, new Color($r, $g, $b), 1.2f);
			}
			return true;
		}

		public override void MouseOver(int i, int j) {
			Player player = Main.LocalPlayer;
			player.noThrow = 2;
			player.cursorItemIconEnabled = true;
			player.cursorItemIconID = ModContent.ItemType<Items.$itemClass>();
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $tileDir "$tileClass.cs") -Encoding UTF8

    # --- Particle / FX system (self-contained, no external deps) ---
    @"
using Microsoft.Xna.Framework;
using Terraria;
using Terraria.ModLoader;

namespace ${modName}.Content.Systems
{
	/// <summary>
	/// Lightweight nearby FX for $displayName. Profile: motion=$MotionPattern, particles~$ParticleCount.
	/// Distort=$DistortStrength wave=$WaveFrequency chroma=$ChromaticAberration (metadata for shaders).
	/// </summary>
	public class $systemClass : ModSystem
	{
		private static int _spawnCooldown;

		public static void SpawnNearTile(int i, int j) {
			if (Main.gamePaused) return;
			if (++_spawnCooldown < 4) return;
			_spawnCooldown = 0;

			Vector2 center = new Vector2(i * 16 + 8, j * 16 + 8);
			int count = System.Math.Max(1, $ParticleCount / 20);
			for (int n = 0; n < count; n++) {
				Vector2 offset = Main.rand.NextVector2Circular(18f, 18f);
				int dust = Dust.NewDust(center + offset, 1, 1, Terraria.ID.DustID.RainbowTorch, 0f, 0f, 100, new Color($r, $g, $b), 0.9f);
				Main.dust[dust].noGravity = true;
				string motion = "$MotionPattern";
				if (motion.Contains("outflow")) {
					Main.dust[dust].velocity = Vector2.Normalize(offset + Vector2.UnitY * 0.01f) * Main.rand.NextFloat(0.4f, 1.2f);
				} else if (motion.Contains("inflow")) {
					Main.dust[dust].velocity = -Vector2.Normalize(offset + Vector2.UnitY * 0.01f) * Main.rand.NextFloat(0.4f, 1.2f);
				} else {
					Main.dust[dust].velocity = offset.RotatedBy(0.2f) * 0.05f;
				}
			}
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $sysDir "$systemClass.cs") -Encoding UTF8

    # --- Localization ---
    @"
Mods: {
	${modName}: {
		ItemName: {
			${itemClass}: $displayName
		}
		ItemTooltip: {
			${itemClass}: Places a $Preset portal. Right-click the tile to recall to spawn.
		}
		Tiles: {
			${tileClass}: {
				MapEntry: $displayName
			}
		}
	}
}
"@ | Set-Content -LiteralPath (Join-Path $locDir "en-US_Mods.$modName.hjson") -Encoding UTF8

    # --- README ---
    @"
# $modName

Generated by AAMT ``TerrariaPortalGenerator.ps1``.

## Gameplay

| Piece | Role |
|-------|------|
| ``$itemClass`` | Placeable item; craft at Work Bench (20 Glass + 3 Fallen Star) |
| ``$tileClass`` | Lit portal tile; nearby dust FX; **right-click recalls to spawn/bed** |
| ``$systemClass`` | Particle spawn helper |

## Install

1. Copy the ``$modName`` folder into ``Documents\My Games\Terraria\tModLoader\ModSources\``
2. Build/publish from tModLoader (or ``dotnet build`` with tML refs)
3. Enable the mod in-game

## Art

Tile texture: ``Content/Tiles/$tileClass.png``
Item / mod icon: ``Content/Items/$itemClass.png``, ``icon.png``

Preset: **$Preset** — $Description
"@ | Set-Content -LiteralPath (Join-Path $modRoot "README.md") -Encoding UTF8

    Write-Host "[Created] tModLoader pack: $modRoot" -ForegroundColor Green
    Write-Host "  Item:  Content/Items/$itemClass.cs (+ png)" -ForegroundColor Gray
    Write-Host "  Tile:  Content/Tiles/$tileClass.cs (+ png)" -ForegroundColor Gray
    Write-Host "  System: Content/Systems/$systemClass.cs" -ForegroundColor Gray
    Write-Host "  build.txt / description.txt / Localization / README.md" -ForegroundColor Gray

    return @{
        ModRoot = $modRoot
        ModName = $modName
        ItemClass = $itemClass
        TileClass = $tileClass
    }
}
