#!/usr/bin/env python3
"""
Generate Soulash 2 Hydromancy mod branding assets (icon + thumbnail).

Modes:
  references  — apply core2_asset_references.json to mod JSON only
  procedural  — PIL-render icon/thumbnail from hydromancy palette (no Ollama)
  ollama      — Ollama design spec + procedural render + quality gate
  sd          — post-process SD design drafts → icon/thumbnail (see PS1 for SD gen)
  all         — references + best available branding (sd > ollama > procedural)

Uses Shared/ollama_integration.py when available.
SD drafts are generated by GenerateHydromancyAssets.ps1 via StableDiffusionIntegration.psm1.
"""

from __future__ import annotations

import argparse
import json
import random
import subprocess
import sys
from pathlib import Path
from typing import Any, Callable, Dict, Optional, Tuple

from PIL import Image, ImageDraw, ImageFilter

SCRIPT_DIR = Path(__file__).resolve().parent
SHARED_DIR = SCRIPT_DIR.parent / "Shared"
if str(SHARED_DIR) not in sys.path:
    sys.path.insert(0, str(SHARED_DIR))

from hydromancy_quality import (  # noqa: E402
    HYDROMANCY_PALETTE,
    finalize_icon,
    finalize_icon_from_sd,
    finalize_thumbnail_from_sd,
    parse_ollama_json,
    run_quality_gate,
    SOULASH_ART_SYSTEM,
)

try:
    from ollama_integration import call_ollama, test_ollama_connection
    OLLAMA_AVAILABLE = True
except ImportError:
    OLLAMA_AVAILABLE = False

DEFAULT_MOD = Path(r"E:\SteamLibrary\steamapps\common\Soulash 2\data\mods\arendeth_water_magic")
DRAFT_ICON_NAME = "icon_design_draft.png"
DRAFT_THUMB_NAME = "thumbnail_design_draft.png"


def hex_to_rgb(h: str) -> Tuple[int, int, int]:
    h = h.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def lerp_color(c1: Tuple[int, int, int], c2: Tuple[int, int, int], t: float) -> Tuple[int, int, int]:
    return tuple(int(a + (b - a) * t) for a, b in zip(c1, c2))  # type: ignore


def default_design_spec() -> Dict[str, Any]:
    return {
        "motif": "hydraulic droplet under pressure ring",
        "colorScheme": {
            "background": HYDROMANCY_PALETTE[0],
            "deep": HYDROMANCY_PALETTE[1],
            "mid": HYDROMANCY_PALETTE[2],
            "accent": HYDROMANCY_PALETTE[3],
            "highlight": HYDROMANCY_PALETTE[4],
            "rim": HYDROMANCY_PALETTE[5],
        },
        "composition": "centered teardrop with concentric ripples",
    }


def fetch_ollama_design_spec(asset_type: str) -> Dict[str, Any]:
    if not OLLAMA_AVAILABLE or not test_ollama_connection():
        print("  [WARN] Ollama unavailable; using default hydromancy palette")
        return default_design_spec()

    prompt = (
        f"Design a Soulash 2 mod {asset_type} for Hydromancy (pressure water magic). "
        "JSON fields: motif (string), colorScheme (background, deep, mid, accent, highlight, rim as #hex), "
        "composition (string). Dark fantasy pixel UI, teal/cyan, readable at small size."
    )
    try:
        response = call_ollama(
            prompt=prompt,
            task_type="visual",
            response_length="standard",
            system_prompt=SOULASH_ART_SYSTEM,
        )
        spec = parse_ollama_json(response, asset_type)
        cs = spec.get("colorScheme") or {}
        if len(cs) < 3:
            base = default_design_spec()
            base.update(spec)
            return base
        return spec
    except Exception as exc:
        print(f"  [WARN] Ollama design failed ({exc}); using defaults")
        return default_design_spec()


def draw_hydromancy_motif(
    draw: ImageDraw.ImageDraw,
    cx: float,
    cy: float,
    radius: float,
    colors: Dict[str, str],
) -> None:
    deep = hex_to_rgb(colors.get("deep", HYDROMANCY_PALETTE[1]))
    mid = hex_to_rgb(colors.get("mid", HYDROMANCY_PALETTE[2]))
    accent = hex_to_rgb(colors.get("accent", HYDROMANCY_PALETTE[3]))
    highlight = hex_to_rgb(colors.get("highlight", HYDROMANCY_PALETTE[4]))
    rim = hex_to_rgb(colors.get("rim", HYDROMANCY_PALETTE[5]))

    for i in range(4, 0, -1):
        r = radius * (0.35 + i * 0.18)
        c = lerp_color(deep, accent, i / 5)
        draw.ellipse((cx - r, cy - r, cx + r, cy + r), outline=c + (90,), width=max(1, int(radius * 0.04)))

    drop_h = radius * 1.1
    drop_w = radius * 0.65
    drop = [
        (cx, cy - drop_h * 0.55),
        (cx + drop_w, cy + drop_h * 0.15),
        (cx, cy + drop_h * 0.55),
        (cx - drop_w, cy + drop_h * 0.15),
    ]
    draw.polygon(drop, fill=mid + (255,))
    draw.polygon(
        [
            (cx - drop_w * 0.15, cy - drop_h * 0.35),
            (cx + drop_w * 0.25, cy - drop_h * 0.05),
            (cx, cy + drop_h * 0.2),
            (cx - drop_w * 0.35, cy + drop_h * 0.05),
        ],
        fill=highlight + (180,),
    )
    draw.ellipse(
        (cx - drop_w * 0.35, cy - drop_h * 0.25, cx - drop_w * 0.05, cy + drop_h * 0.05),
        fill=rim + (220,),
    )


def render_icon(spec: Dict[str, Any], seed: int = 0) -> Image.Image:
    random.seed(seed)
    size = 32
    cs = spec.get("colorScheme") or {}
    bg = hex_to_rgb(cs.get("background", HYDROMANCY_PALETTE[0]))
    img = Image.new("RGBA", (size, size), bg + (255,))
    draw = ImageDraw.Draw(img)
    draw_hydromancy_motif(draw, size / 2, size / 2 + 1, size * 0.38, cs)
    return finalize_icon(img)


def render_thumbnail(spec: Dict[str, Any], seed: int = 0) -> Image.Image:
    random.seed(seed)
    w, h = 800, 600
    cs = spec.get("colorScheme") or {}
    bg = hex_to_rgb(cs.get("background", HYDROMANCY_PALETTE[0]))
    deep = hex_to_rgb(cs.get("deep", HYDROMANCY_PALETTE[1]))
    accent = hex_to_rgb(cs.get("accent", HYDROMANCY_PALETTE[3]))
    img = Image.new("RGBA", (w, h), bg + (255,))
    draw = ImageDraw.Draw(img)

    for y in range(h):
        t = y / h
        row = lerp_color(deep, bg, t * 0.6)
        draw.line([(0, y), (w, y)], fill=row + (255,))

    for i in range(6):
        cx = w * (0.15 + i * 0.14) + random.randint(-20, 20)
        cy = h * (0.45 + (i % 3) * 0.08)
        draw_hydromancy_motif(draw, cx, cy, 48 + i * 6, cs)

    draw_hydromancy_motif(draw, w * 0.5, h * 0.48, 140, cs)

    title_y = int(h * 0.78)
    draw.rectangle((40, title_y - 8, w - 40, title_y + 52), fill=deep + (160,))
    draw.text((56, title_y), "Hydromancy", fill=hex_to_rgb(cs.get("highlight", HYDROMANCY_PALETTE[4])) + (255,))
    draw.text((56, title_y + 22), "Pressure · Flow · Wet", fill=accent + (220,))

    img = img.filter(ImageFilter.GaussianBlur(radius=0.4))
    return finalize_icon(img)


def render_icon_from_sd(draft_path: Path, seed: int = 0) -> Image.Image:
    with Image.open(draft_path) as src:
        return finalize_icon_from_sd(src.copy())


def render_thumbnail_from_sd(draft_path: Path, seed: int = 0) -> Image.Image:
    with Image.open(draft_path) as src:
        return finalize_thumbnail_from_sd(src.copy())


def generate_with_retries(
    render_fn: Callable[..., Image.Image],
    spec_or_path: Any,
    out_path: Path,
    asset_type: str,
    quality_depth: str,
    max_attempts: int = 5,
    from_sd: bool = False,
) -> Tuple[bool, Dict[str, Any]]:
    last_report: Dict[str, Any] = {}
    for attempt in range(max_attempts):
        if from_sd:
            img = render_fn(spec_or_path, seed=attempt)
        else:
            img = render_fn(spec_or_path, seed=attempt)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        img.save(out_path, "PNG")
        passed, report = run_quality_gate(out_path, asset_type, quality_depth)
        last_report = report
        if passed:
            print(f"  [OK] {asset_type} passed QA (attempt {attempt + 1}): {out_path.name}")
            return True, report
        print(f"  [RETRY] {asset_type} attempt {attempt + 1}: {report}")
    return False, last_report


def resolve_sd_drafts(
    mod_path: Path,
    sd_drafts_dir: Optional[Path],
    sd_draft_icon: Optional[Path],
    sd_draft_thumbnail: Optional[Path],
) -> Tuple[Optional[Path], Optional[Path]]:
    drafts_dir = sd_drafts_dir or (mod_path / "DesignDrafts")
    icon = sd_draft_icon or (drafts_dir / DRAFT_ICON_NAME)
    thumb = sd_draft_thumbnail or (drafts_dir / DRAFT_THUMB_NAME)
    icon_ok = icon.exists() and icon.stat().st_size > 0
    thumb_ok = thumb.exists() and thumb.stat().st_size > 0
    return (icon if icon_ok else None, thumb if thumb_ok else None)


def apply_references(mod_path: Path) -> None:
    script = SCRIPT_DIR / "apply_core2_references.py"
    subprocess.run([sys.executable, str(script), "--mod-path", str(mod_path)], check=True)


def generate_branding(
    mode: str,
    icon_path: Path,
    thumb_path: Path,
    quality: str,
    max_attempts: int,
    sd_draft_icon: Optional[Path],
    sd_draft_thumbnail: Optional[Path],
    use_sd: bool,
) -> bool:
    want_sd = mode == "sd" or use_sd or (mode == "all" and sd_draft_icon and sd_draft_thumbnail)

    if want_sd and sd_draft_icon and sd_draft_thumbnail:
        print("[2/3] Post-processing SD design drafts...")
        ok_icon, _ = generate_with_retries(
            render_icon_from_sd,
            sd_draft_icon,
            icon_path,
            "icon",
            quality,
            max_attempts,
            from_sd=True,
        )
        ok_thumb, _ = generate_with_retries(
            render_thumbnail_from_sd,
            sd_draft_thumbnail,
            thumb_path,
            "thumbnail",
            quality,
            max_attempts,
            from_sd=True,
        )
        if ok_icon and ok_thumb:
            return True
        if mode == "sd":
            print("  [WARN] SD post-process failed quality gate; falling back to procedural")
        else:
            print("  [WARN] SD drafts failed QA; trying procedural fallback")

    if mode == "sd" and not (sd_draft_icon and sd_draft_thumbnail):
        print("  [WARN] SD mode requested but no design drafts found; using procedural fallback")

    use_ollama = mode in ("ollama", "all") and OLLAMA_AVAILABLE and not (want_sd and sd_draft_icon)
    label = "ollama+procedural" if use_ollama else "procedural"
    print(f"[2/3] Generating branding assets ({label})...")

    icon_spec = fetch_ollama_design_spec("icon") if use_ollama else default_design_spec()
    thumb_spec = fetch_ollama_design_spec("thumbnail") if use_ollama else default_design_spec()

    ok_icon, _ = generate_with_retries(
        render_icon, icon_spec, icon_path, "icon", quality, max_attempts
    )
    ok_thumb, _ = generate_with_retries(
        render_thumbnail, thumb_spec, thumb_path, "thumbnail", quality, max_attempts
    )
    return ok_icon and ok_thumb


def main() -> int:
    parser = argparse.ArgumentParser(description="Soulash 2 Hydromancy asset generator")
    parser.add_argument("--mod-path", type=Path, default=DEFAULT_MOD)
    parser.add_argument(
        "--mode",
        choices=["references", "procedural", "ollama", "sd", "all"],
        default="all",
    )
    parser.add_argument(
        "--quality",
        choices=["fast", "mechanical", "full"],
        default="mechanical",
    )
    parser.add_argument("--max-attempts", type=int, default=5)
    parser.add_argument("--use-sd", action="store_true", help="Prefer SD drafts when available")
    parser.add_argument("--sd-drafts-dir", type=Path, default=None)
    parser.add_argument("--sd-draft-icon", type=Path, default=None)
    parser.add_argument("--sd-draft-thumbnail", type=Path, default=None)
    args = parser.parse_args()

    mod_path = args.mod_path.resolve()
    branding = {}
    ref_file = mod_path / "core2_asset_references.json"
    if ref_file.exists():
        with open(ref_file, encoding="utf-8") as f:
            branding = json.load(f).get("mod_branding", {})

    icon_name = branding.get("icon", "S.png")
    thumb_name = branding.get("thumbnail", "thumbnail2.png")
    icon_path = mod_path / icon_name
    thumb_path = mod_path / thumb_name

    sd_icon, sd_thumb = resolve_sd_drafts(
        mod_path, args.sd_drafts_dir, args.sd_draft_icon, args.sd_draft_thumbnail
    )

    if args.mode in ("references", "all"):
        print("[1/3] Applying core_2 asset references...")
        apply_references(mod_path)

    if args.mode in ("procedural", "ollama", "sd", "all"):
        ok = generate_branding(
            args.mode,
            icon_path,
            thumb_path,
            args.quality,
            args.max_attempts,
            sd_icon,
            sd_thumb,
            args.use_sd,
        )
        if not ok:
            print("[FAIL] Quality gate rejected one or more assets")
            return 1

    print(f"[3/3] Done. Mod assets at {mod_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
