-- AI-Driven Crossbow Generation Pipeline Demo
-- This demonstrates the complete system that generates both game assets AND sprites automatically

print("=== AI-Driven Crossbow Generation Pipeline Demo ===")

-- 1. Initialize AI Art Generator
print("Initializing AI Art Generator...")

local aiConfig = {
    modelPath = "models/starbound-style-sd-v1.5",
    loraPath = "models/starbound-lora-v1.0",
    styleTokens = "pixel-art, 8-directional, clean-lines, starbound-style",
    maxSteps = 25,
    guidanceScale = 7.5,
    useHalfPrecision = true,
    useTensorRT = true,
    batchSize = 4
}

-- Initialize AI art generator (this would be done in C++)
-- local aiGenerator = initialize_ai_art_generator(aiConfig)

-- 2. Create an explosive crossbow with AI-generated art
local explosiveCrossbow = create_light_crossbow()
explosiveCrossbow.id = "mt_ai_explosive_crossbow_v1"
explosiveCrossbow.drawLength = 0.5
explosiveCrossbow.drawWeight = 300
explosiveCrossbow.autoReload = true
explosiveCrossbow.reloadTime = 1.2
explosiveCrossbow.stockMaterial = "WoodOak"
explosiveCrossbow.limbMaterial = "Fiberglass"
explosiveCrossbow.stringMaterial = "Synthetic"

local explosiveConfig = {
    itemName = "AI-Generated Explosive Crossbow",
    description = "A crossbow with explosive bolts, generated entirely by AI",
    rarity = "Rare",
    category = "weapon",
    level = "5",
    damageType = "physical",
    damage = 15.0,
    fireRate = 1.5,
    abilityType = "crossbow",
    behaviorSystem = "hybrid",
    effectSystem = "projectile",
    materialSystem = "magitech",
    projectileTypes = {"mt_ai_explosive_bolt"},
    specialEffects = {"explosive", "piercing"},
    
    -- AI Art generation settings
    useAIArt = true,
    artStyle = "pixel-art",
    colorPalette = "starbound",
    artEffects = {"metallic", "glowing", "weathered"}
}

-- Generate complete crossbow with AI art
local explosiveAssets = generate_crossbow_assets_with_ai(explosiveCrossbow, explosiveConfig)
if explosiveAssets.spriteFile then
    print("✓ Generated AI crossbow assets:")
    print("  Item file: " .. explosiveAssets.itemFile)
    print("  AI Sprite: " .. explosiveAssets.spriteFile)
    print("  AI Icon: " .. explosiveAssets.iconFile)
    print("  Behavior: " .. explosiveAssets.behaviorFile)
    print("  Effects: " .. explosiveAssets.effectFile)
    print("  Metadata: " .. explosiveAssets.metadataFile)
else
    print("✗ AI crossbow generation failed")
end

-- 3. Create AI-generated explosive bolts
local explosiveBolt = create_steel_bolt()
explosiveBolt.id = "mt_ai_explosive_bolt_v1"
explosiveBolt.length = 0.4
explosiveBolt.shaftRadius = 0.005
explosiveBolt.useFletching = false
explosiveBolt.tipMass = 0.025
explosiveBolt.barbedTip = true

local boltConfig = {
    itemName = "AI-Generated Explosive Bolt",
    description = "A bolt that explodes on impact, generated by AI",
    rarity = "Uncommon",
    category = "ammo",
    level = "5",
    damageType = "physical",
    damage = 8.0,
    fireRate = 1.0,
    abilityType = "projectile",
    effectSystem = "projectile",
    specialEffects = {"explosive", "fire"},
    
    -- AI Art settings
    useAIArt = true,
    artStyle = "pixel-art",
    colorPalette = "neon",
    artEffects = {"glowing", "explosive"}
}

-- Generate bolt with AI art
local boltAssets = generate_bolt_assets_with_ai(explosiveBolt, boltConfig)
if boltAssets.spriteFile then
    print("✓ Generated AI bolt assets:")
    print("  Projectile: " .. boltAssets.projectileFile)
    print("  AI Sprite: " .. boltAssets.spriteFile)
    print("  AI Icon: " .. boltAssets.iconFile)
    print("  Effects: " .. boltAssets.effectFile)
else
    print("✗ AI bolt generation failed")
end

-- 4. Create AI-generated elemental arrows
local iceArrow = create_wood_arrow()
iceArrow.id = "mt_ai_ice_arrow_v1"
iceArrow.shaftLength = 1.1
iceArrow.shaftDiameter = 0.008
iceArrow.spineRating = 600
iceArrow.useFletching = true
iceArrow.fletchStyle = "Parabolic"
iceArrow.nockSize = 0.02
iceArrow.tipMass = 0.015

local iceArrowConfig = {
    itemName = "AI-Generated Ice Arrow",
    description = "An arrow that freezes targets, generated by AI",
    rarity = "Uncommon",
    category = "ammo",
    level = "8",
    damageType = "ice",
    damage = 12.0,
    fireRate = 1.0,
    abilityType = "projectile",
    effectSystem = "spell",
    specialEffects = {"freezing", "slow"},
    
    -- AI Art settings
    useAIArt = true,
    artStyle = "pixel-art",
    colorPalette = "ice",
    artEffects = {"crystalline", "frost"}
}

-- Generate arrow with AI art
local iceArrowAssets = generate_arrow_assets_with_ai(iceArrow, iceArrowConfig)
if iceArrowAssets.spriteFile then
    print("✓ Generated AI arrow assets:")
    print("  Projectile: " .. iceArrowAssets.projectileFile)
    print("  AI Sprite: " .. iceArrowAssets.spriteFile)
    print("  AI Icon: " .. iceArrowAssets.iconFile)
    print("  Effects: " .. iceArrowAssets.effectFile)
else
    print("✗ AI arrow generation failed")
end

-- 5. Batch generation example
print("\n--- Batch AI Generation ---")

local batchItems = {
    {create_light_crossbow(), "mt_ai_batch_crossbow_1", "Light Crossbow"},
    {create_heavy_crossbow(), "mt_ai_batch_crossbow_2", "Heavy Crossbow"},
    {create_steel_bolt(), "mt_ai_batch_bolt_1", "Steel Bolt"},
    {create_wood_arrow(), "mt_ai_batch_arrow_1", "Wood Arrow"}
}

local batchConfig = {
    useAIArt = true,
    artStyle = "pixel-art",
    colorPalette = "starbound",
    artEffects = {"metallic", "clean"}
}

-- Generate batch of items with AI art
local batchResults = generate_batch_assets_with_ai(batchItems, batchConfig)
print("Generated " .. #batchResults .. " items in batch")

-- 6. Advanced AI Art Features
print("\n--- Advanced AI Art Features ---")

-- Custom art prompt generation
local customPrompt = {
    description = "A futuristic plasma crossbow with glowing energy cores",
    style = "pixel-art",
    colorPalette = "neon",
    resolution = 64,
    frameCount = 8,
    direction = "8-directional",
    useAlpha = true,
    specialEffects = {"glowing", "energy", "futuristic"}
}

-- Generate custom art
local customArt = generate_custom_art(customPrompt)
if customArt.success then
    print("✓ Generated custom art: " .. customArt.spriteFile)
else
    print("✗ Custom art generation failed: " .. customArt.errorMessage)
end

-- 7. AI Art Quality Control
print("\n--- AI Art Quality Control ---")

-- Check generated art quality
local qualityResults = check_ai_art_quality(explosiveAssets.spriteFile)
print("Art quality score: " .. qualityResults.score)
print("Style consistency: " .. qualityResults.styleConsistency)
print("Color palette match: " .. qualityResults.colorMatch)

-- 8. Integration with Existing Systems
print("\n--- Integration with Existing Systems ---")

-- The AI-generated assets automatically integrate with:
print("✓ Hybrid C++/Lua behavior system")
print("✓ Existing spell/effect systems")
print("✓ Existing material systems")
print("✓ Existing projectile tracking")
print("✓ Existing special effects")
print("✓ Existing animation systems")

-- 9. Performance Metrics
print("\n--- Performance Metrics ---")

local performance = get_ai_generation_performance()
print("Average generation time: " .. performance.avgTime .. " seconds")
print("GPU memory usage: " .. performance.gpuMemory .. " MB")
print("Cache hit rate: " .. performance.cacheHitRate .. "%")
print("Success rate: " .. performance.successRate .. "%")

-- 10. File Structure Overview
print("\n--- Generated File Structure ---")
print("items/active/weapons/crossbow/")
print("├── mt_ai_explosive_crossbow_v1/")
print("│   ├── mt_ai_explosive_crossbow_v1.activeitem")
print("│   ├── mt_ai_explosive_crossbow_v1full.frames")
print("│   ├── mt_ai_explosive_crossbow_v1full.png (AI-generated)")
print("│   ├── mt_ai_explosive_crossbow_v1icon.png (AI-generated)")
print("│   ├── mt_ai_explosive_crossbow_v1.lua")
print("│   ├── mt_ai_explosive_crossbow_v1_effects.json")
print("│   └── mt_ai_explosive_crossbow_v1_metadata.json")
print("└── ammo/")
print("    ├── mt_ai_explosive_bolt_v1/")
print("    │   ├── mt_ai_explosive_bolt_v1.projectile")
print("    │   ├── mt_ai_explosive_bolt_v1.png (AI-generated)")
print("    │   ├── mt_ai_explosive_bolt_v1icon.png (AI-generated)")
print("    │   ├── mt_ai_explosive_bolt_v1_effects.json")
print("    │   └── mt_ai_explosive_bolt_v1_metadata.json")
print("    └── mt_ai_ice_arrow_v1/")
print("        ├── mt_ai_ice_arrow_v1.projectile")
print("        ├── mt_ai_ice_arrow_v1.png (AI-generated)")
print("        ├── mt_ai_ice_arrow_v1icon.png (AI-generated)")
print("        ├── mt_ai_ice_arrow_v1_effects.json")
print("        └── mt_ai_ice_arrow_v1_metadata.json")

print("\n=== AI-Driven Crossbow Generation Complete ===")
print("All assets and sprites were generated automatically by AI!")
print("The system integrates seamlessly with your existing hybrid C++/Lua system.")
print("No manual art creation required - just describe what you want!") 