# Auto-generated asset generation script
# Generated from asset requirements scan

$itemsToGenerate = @(
    @{ Id = 'chemicalgrenadeammo_mk2'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadeammo_mk2' },
    @{ Id = 'shell_mk2'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadeammo_mk2' },
    @{ Id = 'reagent1_mk2'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadeammo_mk2' },
    @{ Id = 'reagent2_mk2'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadeammo_mk2' },
    @{ Id = 'reagent3_mk2'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadeammo_mk2' },
    @{ Id = 'reinforcement'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadeammo_mk2' },
    @{ Id = 'chemicalgrenadeammo_mk3'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'shell_mk3'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'reagent1_mk3'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'reagent2_mk3'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'reagent3_mk3'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'runes'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'mana_glow'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'chemicalgrenadeammo'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadeammo' },
    @{ Id = 'shell'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadeammo' },
    @{ Id = 'reagent1'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadeammo' },
    @{ Id = 'reagent2'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadeammo' },
    @{ Id = 'reagent3'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadeammo' },
    @{ Id = 'grenade_acid'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_acid' },
    @{ Id = 'shell_acid'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_acid' },
    @{ Id = 'fuse_acid'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_acid' },
    @{ Id = 'corrosion_mark'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_acid' },
    @{ Id = 'grenade_fire'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_fire' },
    @{ Id = 'shell_fire'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_fire' },
    @{ Id = 'fuse_fire'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_fire' },
    @{ Id = 'fire_glow'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_fire' },
    @{ Id = 'grenade_frost'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_frost' },
    @{ Id = 'shell_frost'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_frost' },
    @{ Id = 'fuse_frost'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_frost' },
    @{ Id = 'frost_coating'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_frost' },
    @{ Id = 'grenade_shadow'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_shadow' },
    @{ Id = 'shell_shadow'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_shadow' },
    @{ Id = 'fuse_shadow'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_shadow' },
    @{ Id = 'void_essence'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_shadow' },
    @{ Id = 'grenade_storm'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_storm' },
    @{ Id = 'shell_storm'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_storm' },
    @{ Id = 'fuse_storm'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_storm' },
    @{ Id = 'lightning_charge'; Type = 'ItemSprite'; Prompt = 'Item sprite for grenade_storm' },
    @{ Id = 'reagent_catalyst'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_catalyst' },
    @{ Id = 'satchel'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_catalyst' },
    @{ Id = 'crystals_catalyst'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_catalyst' },
    @{ Id = 'catalyst_glow'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_catalyst' },
    @{ Id = 'reagent_fireessence'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_fireessence' },
    @{ Id = 'vial_fire'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_fireessence' },
    @{ Id = 'liquid_fire'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_fireessence' },
    @{ Id = 'embers'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_fireessence' },
    @{ Id = 'fire_glow'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_fireessence' },
    @{ Id = 'reagent_icecrystal'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_icecrystal' },
    @{ Id = 'vial_ice'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_icecrystal' },
    @{ Id = 'liquid_ice'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_icecrystal' },
    @{ Id = 'frost'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_icecrystal' },
    @{ Id = 'crystals'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_icecrystal' },
    @{ Id = 'reagent_oilpowder'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_oilpowder' },
    @{ Id = 'pouch'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_oilpowder' },
    @{ Id = 'powder_oil'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_oilpowder' },
    @{ Id = 'oil_stain'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_oilpowder' },
    @{ Id = 'reagent_poisoncloud'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_poisoncloud' },
    @{ Id = 'canister'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_poisoncloud' },
    @{ Id = 'gas_poison'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_poisoncloud' },
    @{ Id = 'warning_label'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_poisoncloud' },
    @{ Id = 'safety_seal'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_poisoncloud' },
    @{ Id = 'reagent_vial'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_vial' },
    @{ Id = 'vial'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_vial' },
    @{ Id = 'liquid_empty'; Type = 'ItemSprite'; Prompt = 'Item sprite for reagent_vial' },
    @{ Id = 'magitech_berserker_core'; Type = 'ItemSprite'; Prompt = 'Item sprite for magitech_berserker_core' },
    @{ Id = 'magitech_elemental_shard'; Type = 'ItemSprite'; Prompt = 'Item sprite for magitech_elemental_shard' },
    @{ Id = 'magitech_essence_crystal'; Type = 'ItemSprite'; Prompt = 'Item sprite for magitech_essence_crystal' },
    @{ Id = 'magitech_evolution_catalyst'; Type = 'ItemSprite'; Prompt = 'Item sprite for magitech_evolution_catalyst' },
    @{ Id = 'mt_dimensionalkey'; Type = 'ItemSprite'; Prompt = 'Item sprite for mt_dimensionalkey' },
    @{ Id = 'mt_stellarfragment'; Type = 'ItemSprite'; Prompt = 'Item sprite for mt_stellarfragment' },
    @{ Id = 'mt_voidessence'; Type = 'ItemSprite'; Prompt = 'Item sprite for mt_voidessence' },
    @{ Id = 'explosive_core'; Type = 'ItemSprite'; Prompt = 'Item sprite for explosive_core' },
    @{ Id = 'fire_essence'; Type = 'ItemSprite'; Prompt = 'Item sprite for fire_essence' },
    @{ Id = 'ice_essence'; Type = 'ItemSprite'; Prompt = 'Item sprite for ice_essence' },
    @{ Id = 'lightning_essence'; Type = 'ItemSprite'; Prompt = 'Item sprite for lightning_essence' },
    @{ Id = 'mana_crystal'; Type = 'ItemSprite'; Prompt = 'Item sprite for mana_crystal' },
    @{ Id = 'chemicalgrenadelauncher_tech2'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech2' },
    @{ Id = 'butt_tech2'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech2' },
    @{ Id = 'middle_tech2'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech2' },
    @{ Id = 'barrel_tech2'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech2' },
    @{ Id = 'muzzleflash_tech2'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech2' },
    @{ Id = 'filigree'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech2' },
    @{ Id = 'chemicalgrenadelauncher_tech3'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'butt_tech3'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'middle_tech3'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'barrel_tech3'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'muzzleflash_tech3'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'runes'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'arcane_glow'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher_tech3' },
    @{ Id = 'chemicalgrenadelauncher'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher' },
    @{ Id = 'butt'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher' },
    @{ Id = 'middle'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher' },
    @{ Id = 'barrel'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher' },
    @{ Id = 'muzzleflash'; Type = 'ItemSprite'; Prompt = 'Item sprite for chemicalgrenadelauncher' },
    @{ Id = 'flamelord_grenadegun'; Type = 'ItemSprite'; Prompt = 'Item sprite for flamelord_grenadegun' },
    @{ Id = 'flamelord_butt'; Type = 'ItemSprite'; Prompt = 'Item sprite for flamelord_grenadegun' },
    @{ Id = 'flamelord_middle'; Type = 'ItemSprite'; Prompt = 'Item sprite for flamelord_grenadegun' },
    @{ Id = 'flamelord_barrel'; Type = 'ItemSprite'; Prompt = 'Item sprite for flamelord_grenadegun' },
    @{ Id = 'flamelord_muzzleflash'; Type = 'ItemSprite'; Prompt = 'Item sprite for flamelord_grenadegun' },
    @{ Id = 'embers'; Type = 'ItemSprite'; Prompt = 'Item sprite for flamelord_grenadegun' },
    @{ Id = 'molten_glow'; Type = 'ItemSprite'; Prompt = 'Item sprite for flamelord_grenadegun' },
    @{ Id = 'spellstone_core_common'; Type = 'ItemSprite'; Prompt = 'Arcane Core (Common) - /items/other/crystal/crystal1.png' },
    @{ Id = 'spellstone_core_refined'; Type = 'ItemSprite'; Prompt = 'Refined Core (Rare) - /items/other/crystal/crystal2.png' },
    @{ Id = 'spellstone_core_arcane'; Type = 'ItemSprite'; Prompt = 'Arcane Core (Epic) - /items/other/crystal/crystal3.png' },
    @{ Id = 'spellstone_core_apex'; Type = 'ItemSprite'; Prompt = 'Apex Core (Legendary) - /items/other/crystal/crystal4.png' },
    @{ Id = 'spellstone_fire'; Type = 'ItemSprite'; Prompt = 'Fire Spellstone - /items/consumable/essence/essencefire.png' },
    @{ Id = 'spellstone_ice'; Type = 'ItemSprite'; Prompt = 'Frost Spellstone - /items/consumable/essence/essenceice.png' },
    @{ Id = 'spellstone_lightning'; Type = 'ItemSprite'; Prompt = 'Storm Spellstone - /items/consumable/essence/essencelightning.png' },
    @{ Id = 'spellstone_nature'; Type = 'ItemSprite'; Prompt = 'Nature Spellstone - /items/consumable/essence/essencepoison.png' },
    @{ Id = 'spellstone_arcane'; Type = 'ItemSprite'; Prompt = 'Arcane Spellstone - /items/consumable/essence/essenceelectric.png' },
    @{ Id = 'spellstone_void'; Type = 'ItemSprite'; Prompt = 'Void Spellstone - /items/consumable/essence/essenceslash.png' },
    @{ Id = 'spellstone_cosmic'; Type = 'ItemSprite'; Prompt = 'Cosmic Spellstone - /items/consumable/essence/essenceplasma.png' },
    @{ Id = 'spellstone_temporal'; Type = 'ItemSprite'; Prompt = 'Temporal Spellstone - /items/consumable/essence/essencechronon.png' },
    @{ Id = 'fire_ruby'; Type = 'ItemSprite'; Prompt = 'Fire Ruby - /items/materials/fire_ruby.png' },
    @{ Id = 'ice_crystal'; Type = 'ItemSprite'; Prompt = 'Ice Crystal - /items/materials/ice_crystal.png' },
    @{ Id = 'lightning_core'; Type = 'ItemSprite'; Prompt = 'Lightning Core - /items/materials/lightning_core.png' },
    @{ Id = 'earth_core'; Type = 'ItemSprite'; Prompt = 'Earth Core - /items/materials/earth_core.png' },
    @{ Id = 'water_pearl'; Type = 'ItemSprite'; Prompt = 'Water Pearl - /items/materials/water_pearl.png' },
    @{ Id = 'air_wisp'; Type = 'ItemSprite'; Prompt = 'Air Wisp - /items/materials/air_wisp.png' },
    @{ Id = 'shadow_wisp'; Type = 'ItemSprite'; Prompt = 'Shadow Wisp - /items/materials/shadow_wisp.png' },
    @{ Id = 'light_prism'; Type = 'ItemSprite'; Prompt = 'Light Prism - /items/materials/light_prism.png' },
    @{ Id = 'nature_seed'; Type = 'ItemSprite'; Prompt = 'Nature Seed - /items/materials/nature_seed.png' },
    @{ Id = 'cosmic_dust'; Type = 'ItemSprite'; Prompt = 'Cosmic Dust - /items/materials/cosmic_dust.png' },
    @{ Id = 'mana_crystal'; Type = 'ItemSprite'; Prompt = 'Mana Crystal - /items/materials/mana_crystal.png' },
    @{ Id = 'focus_crystal'; Type = 'ItemSprite'; Prompt = 'Focus Crystal - /items/materials/focus_crystal.png' },
    @{ Id = 'resonance_crystal'; Type = 'ItemSprite'; Prompt = 'Resonance Crystal - /items/materials/resonance_crystal.png' },
    @{ Id = 'prismatic_crystal'; Type = 'ItemSprite'; Prompt = 'Prismatic Crystal - /items/materials/prismatic_crystal.png' },
    @{ Id = 'chaos_crystal'; Type = 'ItemSprite'; Prompt = 'Chaos Crystal - /items/materials/chaos_crystal.png' },
    @{ Id = 'stability_catalyst'; Type = 'ItemSprite'; Prompt = 'Stability Catalyst - /items/materials/stability_catalyst.png' },
    @{ Id = 'power_amplifier'; Type = 'ItemSprite'; Prompt = 'Power Amplifier - /items/materials/power_amplifier.png' },
    @{ Id = 'resonance_tuner'; Type = 'ItemSprite'; Prompt = 'Resonance Tuner - /items/materials/resonance_tuner.png' },
    @{ Id = 'mana_conductor'; Type = 'ItemSprite'; Prompt = 'Mana Conductor - /items/materials/mana_conductor.png' },
    @{ Id = 'elemental_focus'; Type = 'ItemSprite'; Prompt = 'Elemental Focus - /items/materials/elemental_focus.png' },
    @{ Id = 'salamander_scale'; Type = 'ItemSprite'; Prompt = 'Salamander Scale - /items/materials/salamander_scale.png' },
    @{ Id = 'frost_essence'; Type = 'ItemSprite'; Prompt = 'Frost Essence - /items/materials/frost_essence.png' },
    @{ Id = 'storm_catalyst'; Type = 'ItemSprite'; Prompt = 'Storm Catalyst - /items/materials/storm_catalyst.png' },
    @{ Id = 'void_fragment'; Type = 'ItemSprite'; Prompt = 'Void Fragment - /items/materials/void_fragment.png' },
    @{ Id = 'solar_essence'; Type = 'ItemSprite'; Prompt = 'Solar Essence - /items/materials/solar_essence.png' },
    @{ Id = 'mountain_stone'; Type = 'ItemSprite'; Prompt = 'Mountain Stone - /items/materials/mountain_stone.png' },
    @{ Id = 'ocean_essence'; Type = 'ItemSprite'; Prompt = 'Ocean Essence - /items/materials/ocean_essence.png' },
    @{ Id = 'life_essence'; Type = 'ItemSprite'; Prompt = 'Life Essence - /items/materials/life_essence.png' },
    @{ Id = 'star_fragment'; Type = 'ItemSprite'; Prompt = 'Star Fragment - /items/materials/star_fragment.png' },
    @{ Id = 'void_crystal'; Type = 'ItemSprite'; Prompt = 'Void Crystal - /items/materials/void_crystal.png' },
    @{ Id = 'phoenix_feather'; Type = 'ItemSprite'; Prompt = 'Phoenix Feather - /items/materials/phoenix_feather.png' },
    @{ Id = 'dimensional_anchor'; Type = 'ItemSprite'; Prompt = 'Dimensional Anchor - /items/materials/dimensional_anchor.png' },
    @{ Id = 'temporal_dust'; Type = 'ItemSprite'; Prompt = 'Temporal Dust - /items/materials/temporal_dust.png' },
    @{ Id = 'living_crystal'; Type = 'ItemSprite'; Prompt = 'Living Crystal - /items/materials/living_crystal.png' },
    @{ Id = 'quantum_particle'; Type = 'ItemSprite'; Prompt = 'Quantum Particle - /items/materials/quantum_particle.png' },
    @{ Id = 'mighty_strength'; Type = 'Icon'; Prompt = 'Buff icon for ' },
    @{ Id = 'frost_aura'; Type = 'Icon'; Prompt = 'Buff icon for ' },
    @{ Id = 'stone_skin'; Type = 'Icon'; Prompt = 'Buff icon for ' },
    @{ Id = 'berserker_rage'; Type = 'Icon'; Prompt = 'Buff icon for ' },
    @{ Id = 'regeneration'; Type = 'Icon'; Prompt = 'Buff icon for ' },
    @{ Id = 'vampiric_touch'; Type = 'Icon'; Prompt = 'Buff icon for ' },
    @{ Id = 'boss_power'; Type = 'Icon'; Prompt = 'Buff icon for ' },
    @{ Id = 'pet_loyalty'; Type = 'Icon'; Prompt = 'Buff icon for ' },
    @{ Id = 'arcane_shield'; Type = 'Icon'; Prompt = 'Buff icon for ' },
    @{ Id = 'invisibility'; Type = 'Icon'; Prompt = 'Buff icon for ' },
)

# Generate all assets
foreach ($item in $itemsToGenerate) {
    .\StarboundOllamaAssetGenerator.ps1 
        -AssetType $item.Type 
        -AssetName $item.Id 
        -Prompt $item.Prompt 
        -OllamaModel "codellama:7b-instruct"
}
