#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Generate integration scripts for assets (Lua and C++).
    
.DESCRIPTION
    Creates integration scripts in:
    - Lua: scripts/[AssetName]AssetManager.lua
    - C++: cpp_backend/core/modules/[AssetName]AssetManager.hpp
    
.PARAMETER AssetName
    Name of the asset system (e.g., "MagicOrb", "Spellstone")
    
.PARAMETER AssetType
    Type of asset system (e.g., "Weapon", "Item", "Projectile", "Particle")
    
.PARAMETER ModPath
    Path to the mod directory
    
.PARAMETER Assets
    Array of asset definitions with id, path, type, etc.
#>

param(
    [Parameter(Mandatory=$true)
# Validate ModPath is not empty
if ([string]::IsNullOrWhiteSpace($ModPath)) {
    Write-Host "Error: ModPath cannot be empty" -ForegroundColor Red
    Write-Host "  Please provide a valid mod path or use the default" -ForegroundColor Gray
    exit 1
}
]
    [string]$AssetName,
    
    [Parameter(Mandatory=$true)]
    [string]$AssetType,
    
    [Parameter(Mandatory=$false)]
    [string]$ModPath = "F:\Games\OpenStarbound\mods\Magi-Tech Arcane Alchemy and Sorcery",
    
    [Parameter(Mandatory=$false)]
    [array]$Assets = @()
)

$ErrorActionPreference = "Continue"

# Load shared asset generation settings
$settingsPath = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "..\\AssetGenerationSettings.ps1"
if (Test-Path $settingsPath) {
    . $settingsPath
}
$PSScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path

# Normalize asset name (PascalCase)
$normalizedName = $AssetName -replace '([a-z])([A-Z])', '$1$2' -split ' ' | ForEach-Object { 
    if ($_.Length -gt 0) {
        $_.Substring(0,1).ToUpper() + $_.Substring(1).ToLower()
    }
} | Where-Object { $_ } | ForEach-Object { $_ }
$normalizedName = ($normalizedName -join '') -replace '[^a-zA-Z0-9]', ''

# Paths
# Validate $ModPath before Join-Path
$luaScriptPath = Join-Path $ModPath "scripts\BusPlugins\${normalizedName}AssetManager\mt_${normalizedName}AssetManager.lua"
 if ([string]::IsNullOrWhiteSpace($luaScriptPath)) {
    Write-Host "  [FAIL] luaScriptPath is null (${ModPath}: '${ModPath}')" -ForegroundColor Red
    continue
}
 if ([string]::IsNullOrWhiteSpace($luaScriptPath)) {
    Write-Host "  [FAIL] luaScriptPath is null (${ModPath}: '${ModPath}')" -ForegroundColor Red
    continue
}
# Validate $ModPath before Join-Path
$cppHeaderPath = Join-Path $ModPath "cpp_backend\core\modules\${normalizedName}AssetManager.hpp"
 if ([string]::IsNullOrWhiteSpace($cppHeaderPath)) {
    Write-Host "  [FAIL] cppHeaderPath is null (${ModPath}: '${ModPath}')" -ForegroundColor Red
    continue
}
 if ([string]::IsNullOrWhiteSpace($cppHeaderPath)) {
    Write-Host "  [FAIL] cppHeaderPath is null (${ModPath}: '${ModPath}')" -ForegroundColor Red
    continue
}
# Validate $ModPath before Join-Path
$cppSourcePath = Join-Path $ModPath "cpp_backend\core\modules\${normalizedName}AssetManager.cpp"
 if ([string]::IsNullOrWhiteSpace($cppSourcePath)) {
    Write-Host "  [FAIL] cppSourcePath is null (${ModPath}: '${ModPath}')" -ForegroundColor Red
    continue
}
 if ([string]::IsNullOrWhiteSpace($cppSourcePath)) {
    Write-Host "  [FAIL] cppSourcePath is null (${ModPath}: '${ModPath}')" -ForegroundColor Red
    continue
}

# Ensure directories exist
$luaDir = Split-Path -Parent $luaScriptPath
$cppDir = Split-Path -Parent $cppHeaderPath
if (-not (Test-Path $luaDir)) {
    New-Item -ItemType Directory -Path $luaDir -Force | Out-Null
}
if (-not (Test-Path $cppDir)) {
    New-Item -ItemType Directory -Path $cppDir -Force | Out-Null
}

# ============================================================================
# Generate Lua Integration Script
# ============================================================================

$luaContent = @"
--[[
    Magi-Tech Arcane Alchemy and Sorcery
    ${normalizedName} Asset Manager - Lua Integration
    
    Provides asset loading and management for ${AssetName} ${AssetType} system.
    Auto-generated by asset generation pipeline.
]]

local ${normalizedName}AssetManager = {}

-- Configuration
local config = {
    enableLicenseVerification = true,
    requireLicenseCompliance = true,
    trackAssetUsage = true,
    autoRegisterAssets = true,
    fallbackToInternal = true,
    logAssetUsage = true
}

-- State
local state = {
    initialized = false,
    registered = false,
    assets = {},
    usageLog = {},
    complianceCache = {}
}

-- ============================================================================
-- Initialization
-- ============================================================================

function ${normalizedName}AssetManager.initialize()
    if state.initialized then
        return true
    end
    
    try(function()
        -- Initialize Enhanced Asset Manager if available
        if MainPlugin and MainPlugin.EnhancedAssetManager then
            if not MainPlugin.EnhancedAssetManager.initialize() then
                error("Failed to initialize Enhanced Asset Manager")
            end
        else
            error("Enhanced Asset Manager not available")
        end
        
        -- Load asset definitions
        ${normalizedName}AssetManager.loadAssetDefinitions()
        
        -- Register assets with Enhanced Asset Manager
        if config.autoRegisterAssets then
            ${normalizedName}AssetManager.registerAllAssets()
        end
        
        -- Register with event system
        ${normalizedName}AssetManager.registerEventHandlers()
        
        state.initialized = true
        log.info("${normalizedName}AssetManager: Initialized successfully")
        
    catch(function(err)
        log.error("${normalizedName}AssetManager: Initialization failed: " .. tostring(err))
        return false
    end))
    
    return state.initialized
end

-- ============================================================================
-- Asset Loading and Registration
-- ============================================================================

function ${normalizedName}AssetManager.loadAssetDefinitions()
    try(function()
        -- Asset definitions
        state.assets = {
$(if ($Assets.Count -gt 0) {
    $assetLines = $Assets | ForEach-Object {
        $lines = @()
        $lines += "            [`"$($_.Id)`"] = {"
        $lines += "                id = `"$($_.Id)`","
        $lines += "                path = `"$($_.Path)`","
        $lines += "                type = `"$($_.Type)`","
        if ($_.License) { $lines += "                license = `"$($_.License)`"," }
        if ($_.Description) { $lines += "                description = `"$($_.Description)`"," }
        $lines += "            },"
        $lines -join "`n"
    }
    $assetLines -join "`n"
} else {
            "            -- Assets will be registered here"
})
        }
        
        log.info("${normalizedName}AssetManager: Loaded " .. table.getn(state.assets) .. " assets")
        
    catch(function(err)
        log.error("${normalizedName}AssetManager: Failed to load asset definitions: " .. tostring(err))
    end))
end

function ${normalizedName}AssetManager.registerAllAssets()
    if not state.initialized then
        log.error("${normalizedName}AssetManager: Cannot register assets - not initialized")
        return
    end
    
    try(function()
        for assetId, assetData in pairs(state.assets) do
            ${normalizedName}AssetManager.registerAsset(assetId, assetData)
        end
        
        log.info("${normalizedName}AssetManager: Registered all assets successfully")
        
    catch(function(err)
        log.error("${normalizedName}AssetManager: Failed to register assets: " .. tostring(err))
    end))
end

function ${normalizedName}AssetManager.registerAsset(assetId, assetData)
    if not assetData.path then
        log.warning("${normalizedName}AssetManager: No path for asset " .. assetId)
        return false
    end
    
    -- Register with Enhanced Asset Manager
    local success = MainPlugin.EnhancedAssetManager.registerAsset(
        assetId,
        assetData.path,
        assetData.type or "${AssetType}",
        "MagiTech",
        assetData.license or "CC-BY-NC-SA",
        {
            description = assetData.description or "Auto-generated ${AssetName} asset",
            category = "${AssetType}",
            system = "${normalizedName}"
        }
    )
    
    if success then
        if config.logAssetUsage then
            table.insert(state.usageLog, {
                assetId = assetId,
                action = "registered",
                timestamp = os.time()
            })
        end
        return true
    else
        log.warning("${normalizedName}AssetManager: Failed to register asset " .. assetId)
        return false
    end
end

-- ============================================================================
-- Asset Access Functions
-- ============================================================================

function ${normalizedName}AssetManager.getAsset(assetId)
    if not state.initialized then
        log.error("${normalizedName}AssetManager: Not initialized")
        return nil
    end
    
    if not state.assets[assetId] then
        log.warning("${normalizedName}AssetManager: Asset not found: " .. assetId)
        return nil
    end
    
    -- Load asset through Enhanced Asset Manager
    local asset = MainPlugin.EnhancedAssetManager.loadAsset(assetId)
    
    if asset and config.logAssetUsage then
        table.insert(state.usageLog, {
            assetId = assetId,
            action = "loaded",
            timestamp = os.time()
        })
    end
    
    return asset
end

function ${normalizedName}AssetManager.getAllAssets()
    return state.assets
end

-- ============================================================================
-- Event Handlers
-- ============================================================================

function ${normalizedName}AssetManager.registerEventHandlers()
    -- Register for asset reload events
    if eventBus then
        eventBus.subscribe("asset.reload", function(data)
            if data.system == "${normalizedName}" or data.assetId and state.assets[data.assetId] then
                ${normalizedName}AssetManager.reloadAsset(data.assetId)
            end
        end)
    end
end

function ${normalizedName}AssetManager.reloadAsset(assetId)
    if not assetId or not state.assets[assetId] then
        return false
    end
    
    log.info("${normalizedName}AssetManager: Reloading asset " .. assetId)
    
    -- Reload through Enhanced Asset Manager
    if MainPlugin.EnhancedAssetManager then
        return MainPlugin.EnhancedAssetManager.reloadAsset(assetId)
    end
    
    return false
end

-- ============================================================================
-- Export
-- ============================================================================

return ${normalizedName}AssetManager
"@

# Write Lua script
[System.IO.File]::WriteAllText($luaScriptPath, $luaContent, [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated Lua integration script: $luaScriptPath" -ForegroundColor Green

# ============================================================================
# Generate C++ Integration Header
# ============================================================================

$cppHeaderContent = @"
#pragma once

#include <memory>
#include <string>
#include <unordered_map>
#include <shared_mutex>
#include <future>
#include <vector>
#include <optional>
#include <filesystem>
#include "vendor/json/include/nlohmann/json.hpp"

#include "IMagiTechModule.hpp"
#include "core/plugins/AdaptiveBusPlugin.hpp"
#include "core/modules/AssetManager.hpp"

namespace MagiTech {

// Forward declarations
class AssetManager;
struct AssetInfo;

// ${normalizedName} Asset Manager
// Provides C++ integration for ${AssetName} ${AssetType} assets
class ${normalizedName}AssetManager : public IMagiTechModule {
public:
    ${normalizedName}AssetManager();
    ~${normalizedName}AssetManager() override = default;
    
    // IMagiTechModule interface
    bool initialize() override;
    void shutdown() override;
    void update(float deltaTime) override;
    std::string getName() const override { return "${normalizedName}AssetManager"; }
    
    // Asset management
    bool registerAsset(const std::string& assetId, const std::string& filepath, 
                      const std::string& assetType = "${AssetType}");
    std::shared_ptr<AssetInfo> getAsset(const std::string& assetId);
    bool reloadAsset(const std::string& assetId);
    std::vector<std::string> getAllAssetIds() const;
    
    // Asset loading
    bool loadAsset(const std::string& assetId);
    bool unloadAsset(const std::string& assetId);
    bool isAssetLoaded(const std::string& assetId) const;
    
private:
    std::shared_ptr<AssetManager> m_assetManager;
    std::unordered_map<std::string, std::shared_ptr<AssetInfo>> m_assets;
    mutable std::shared_mutex m_assetsMutex;
    bool m_initialized = false;
    
    void loadAssetDefinitions();
    void registerAllAssets();
};

} // namespace MagiTech
"@

# Write C++ header
[System.IO.File]::WriteAllText($cppHeaderPath, $cppHeaderContent, [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated C++ header: $cppHeaderPath" -ForegroundColor Green

# ============================================================================
# Generate C++ Implementation
# ============================================================================

$cppSourceContent = @"
#include "${normalizedName}AssetManager.hpp"
#include "core/modules/AssetManager.hpp"
#include "core/Log.hpp"
#include <fstream>

namespace MagiTech {

${normalizedName}AssetManager::${normalizedName}AssetManager()
    : m_assetManager(std::make_shared<AssetManager>())
{
}

bool ${normalizedName}AssetManager::initialize()
{
    if (m_initialized) {
        return true;
    }
    
    try {
        // Initialize asset manager
        if (!m_assetManager->initialize()) {
            Log::error("${normalizedName}AssetManager: Failed to initialize AssetManager");
            return false;
        }
        
        // Load asset definitions
        loadAssetDefinitions();
        
        // Register all assets
        registerAllAssets();
        
        m_initialized = true;
        Log::info("${normalizedName}AssetManager: Initialized successfully");
        return true;
        
    } catch (const std::exception& e) {
        Log::error("${normalizedName}AssetManager: Initialization failed: " + std::string(e.what()));
        return false;
    }
}

void ${normalizedName}AssetManager::shutdown()
{
    std::unique_lock lock(m_assetsMutex);
    m_assets.clear();
    m_initialized = false;
}

void ${normalizedName}AssetManager::update(float deltaTime)
{
    // Update logic if needed
}

void ${normalizedName}AssetManager::loadAssetDefinitions()
{
    // Asset definitions
    // Assets will be registered here during initialization
$(if ($Assets.Count -gt 0) {
    $assetLines = $Assets | ForEach-Object {
        "    registerAsset(`"$($_.Id)`", `"$($_.Path)`", `"$($_.Type)`");"
    }
    $assetLines -join "`n"
})
}

void ${normalizedName}AssetManager::registerAllAssets()
{
    // All assets are registered in loadAssetDefinitions()
}

bool ${normalizedName}AssetManager::registerAsset(const std::string& assetId, 
                                                  const std::string& filepath,
                                                  const std::string& assetType)
{
    std::unique_lock lock(m_assetsMutex);
    
    auto assetInfo = std::make_shared<AssetInfo>();
    assetInfo->id = assetId;
    assetInfo->filepath = filepath;
    assetInfo->type = AssetManager::stringToAssetType(assetType);
    assetInfo->state = AssetState::NotLoaded;
    assetInfo->modId = "MagiTech";
    assetInfo->isHotReloadable = true;
    
    m_assets[assetId] = assetInfo;
    
    // Register with main asset manager
    if (m_assetManager) {
        return m_assetManager->registerAsset(assetInfo);
    }
    
    return false;
}

std::shared_ptr<AssetInfo> ${normalizedName}AssetManager::getAsset(const std::string& assetId)
{
    std::shared_lock lock(m_assetsMutex);
    
    auto it = m_assets.find(assetId);
    if (it != m_assets.end()) {
        return it->second;
    }
    
    return nullptr;
}

bool ${normalizedName}AssetManager::reloadAsset(const std::string& assetId)
{
    std::unique_lock lock(m_assetsMutex);
    
    auto it = m_assets.find(assetId);
    if (it == m_assets.end()) {
        return false;
    }
    
    if (m_assetManager) {
        return m_assetManager->reloadAsset(assetId);
    }
    
    return false;
}

std::vector<std::string> ${normalizedName}AssetManager::getAllAssetIds() const
{
    std::shared_lock lock(m_assetsMutex);
    
    std::vector<std::string> ids;
    ids.reserve(m_assets.size());
    
    for (const auto& [id, asset] : m_assets) {
        ids.push_back(id);
    }
    
    return ids;
}

bool ${normalizedName}AssetManager::loadAsset(const std::string& assetId)
{
    if (!m_assetManager) {
        return false;
    }
    
    return m_assetManager->loadAsset(assetId);
}

bool ${normalizedName}AssetManager::unloadAsset(const std::string& assetId)
{
    if (!m_assetManager) {
        return false;
    }
    
    return m_assetManager->unloadAsset(assetId);
}

bool ${normalizedName}AssetManager::isAssetLoaded(const std::string& assetId) const
{
    std::shared_lock lock(m_assetsMutex);
    
    auto it = m_assets.find(assetId);
    if (it != m_assets.end()) {
        return it->second->state == AssetState::Loaded;
    }
    
    return false;
}

} // namespace MagiTech
"@

# Write C++ source
[System.IO.File]::WriteAllText($cppSourcePath, $cppSourceContent, [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated C++ source: $cppSourcePath" -ForegroundColor Green

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Integration Scripts Generated" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Now merge into central agent files
Write-Host "Merging into central agent files..." -ForegroundColor Cyan
$mergeScript = Join-Path $PSScriptRoot "MergeAssetIntegrationScripts.ps1"
if (Test-Path $mergeScript) {
    & $mergeScript -AssetName $AssetName -AssetType $AssetType -ModPath $ModPath -Assets $Assets -MergeMode "Group"
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  [OK] Merged into central agent files" -ForegroundColor Green
        
        # Clean up individual files since they're now merged
        Write-Host "Cleaning up individual integration files..." -ForegroundColor Yellow
        if (Test-Path $luaScriptPath) {
            Remove-Item $luaScriptPath -Force
            Write-Host "  [OK] Removed: $luaScriptPath" -ForegroundColor Green
        }
        if (Test-Path $cppHeaderPath) {
            Remove-Item $cppHeaderPath -Force
            Write-Host "  [OK] Removed: $cppHeaderPath" -ForegroundColor Green
        }
        if (Test-Path $cppSourcePath) {
            Remove-Item $cppSourcePath -Force
            Write-Host "  [OK] Removed: $cppSourcePath" -ForegroundColor Green
        }
    } else {
        Write-Host "  [WARNING] Merge failed, keeping individual files" -ForegroundColor Yellow
    }
} else {
    Write-Host "  [WARNING] Merge script not found, keeping individual files" -ForegroundColor Yellow
}
Write-Host "Lua script: $luaScriptPath" -ForegroundColor Green
Write-Host "C++ header: $cppHeaderPath" -ForegroundColor Green
Write-Host "C++ source: $cppSourcePath" -ForegroundColor Green
Write-Host ""
