namespace ApiMigrator.Core;

/// <summary>
/// Shared "research + merge" workflow used by both the CLI (refresh-dump) and the GUI
/// (DLL Research tab), so the two never drift out of sync. Scanning is always read-only
/// against the Managed DLLs; nothing is written until SaveWithBackup is explicitly called.
/// </summary>
public static class DumpRefresher
{
    public sealed class RefreshPreview
    {
        public DllResearcher.ScanResult Scan { get; init; } = null!;
        public DumpDiffResult? Diff { get; init; }
        public ObsoleteDump OldDump { get; init; } = null!;
        public bool HadExistingDump { get; init; }
    }

    /// <summary>Reflects the given DLLs and diffs the result against whatever dump currently
    /// exists at dumpPath (or an empty dump if none exists yet). Nothing is written to disk.</summary>
    public static RefreshPreview Scan(string managedDir, IEnumerable<string> dlls, string dumpPath)
    {
        var scan = DllResearcher.ScanForObsoleteMembers(managedDir, dlls);
        var hadExisting = File.Exists(dumpPath);
        var oldDump = hadExisting ? DumpStore.LoadDump(dumpPath) : new ObsoleteDump { Entries = new() };
        var diff = hadExisting ? DllResearcher.Diff(oldDump, scan.Members) : null;
        return new RefreshPreview { Scan = scan, Diff = diff, OldDump = oldDump, HadExistingDump = hadExisting };
    }

    /// <summary>
    /// Builds the merged dump in-memory (existing curated entries preserved verbatim, new
    /// members appended - deduped per overload group - and single-overload message changes
    /// applied in place). Does not touch disk.
    /// </summary>
    public static ObsoleteDump BuildMerged(RefreshPreview preview, IEnumerable<string> managedDllPaths)
    {
        if (!preview.HadExistingDump || preview.Diff is null)
        {
            return new ObsoleteDump
            {
                Meta = new ObsoleteDumpMeta
                {
                    Description = "Obsolete Caves of Qud (Assembly-CSharp.dll) API -> replacement map. Generated by ApiMigrator refresh-dump.",
                    Source = "Generated via ApiMigrator.Core.DllResearcher (Assembly.LoadFrom reflection over live Managed DLLs).",
                    AssemblySource = string.Join(", ", managedDllPaths),
                    ApiDumpTool = "ApiMigrator refresh-dump",
                    CapturedDate = DateTime.Now.ToString("yyyy-MM-dd"),
                },
                Entries = DedupeAdded(preview.Scan.Members),
            };
        }

        var merged = preview.OldDump;
        foreach (var (oldE, newM) in preview.Diff.MessageChanged)
        {
            oldE.ObsoleteMessage = newM.ObsoleteMessage;
        }
        merged.Entries.AddRange(DedupeAdded(preview.Diff.Added));
        HealInstanceMethodSearchPatterns(merged);
        TightenNoisySearchPatterns(merged);
        merged.Meta ??= new ObsoleteDumpMeta();
        merged.Meta.CapturedDate = DateTime.Now.ToString("yyyy-MM-dd");
        return merged;
    }

    /// <summary>
    /// Re-applies known false-positive-safe pattern tightenings when an entry still has the
    /// naive refresh-default pattern. Never overwrites a hand-customized <c>searchPattern</c>.
    /// </summary>
    public static int TightenNoisySearchPatterns(ObsoleteDump dump)
    {
        var tightened = 0;
        foreach (var e in dump.Entries)
        {
            var key = (e.Type, e.Member);
            if (!NoisyPatternTightenings.TryGetValue(key, out var fix))
                continue;
            // Re-apply when still on the naive pattern, OR when stuck on a known intermediate
            // too-broad tightening (e.g. override GetDescription before we disabled the scan).
            var canTighten = string.Equals(e.SearchPattern, fix.NaivePattern, StringComparison.Ordinal)
                || IntermediateBroadPatterns.TryGetValue(key, out var intermediates)
                   && intermediates.Contains(e.SearchPattern);
            if (!canTighten)
                continue;

            e.SearchPattern = fix.TightPattern;
            if (!string.IsNullOrWhiteSpace(fix.NotesSuffix))
            {
                var suffix = fix.NotesSuffix!;
                if (string.IsNullOrWhiteSpace(e.Notes) ||
                    e.Notes.IndexOf(suffix, StringComparison.OrdinalIgnoreCase) < 0)
                {
                    e.Notes = string.IsNullOrWhiteSpace(e.Notes)
                        ? suffix
                        : e.Notes.TrimEnd() + " " + suffix;
                }
            }
            tightened++;
        }
        return tightened;
    }

    private readonly record struct PatternFix(string NaivePattern, string TightPattern, string? NotesSuffix);

    /// <summary>
    /// Patterns left by earlier tightenings that are still too broad and should be upgraded
    /// to the current <see cref="NoisyPatternTightenings"/> target.
    /// </summary>
    private static readonly Dictionary<(string Type, string Member), HashSet<string>> IntermediateBroadPatterns = new()
    {
        [("XRL.World.Parts.IStingerProperties", "GetDescription")] = new(StringComparer.Ordinal)
        {
            @"(?m)override\s+string\s+GetDescription\s*\(",
        },
        [("XRL.World.Parts.IStingerProperties", "AppendLevelText")] = new(StringComparer.Ordinal)
        {
            @"(?m)override\s+void\s+AppendLevelText\s*\(",
        },
    };

    /// <summary>
    /// Naive (refresh-default) → tightened patterns for members that textually collide with
    /// non-obsolete APIs or modern replacements. Keyed by (type, member).
    /// </summary>
    private static readonly Dictionary<(string Type, string Member), PatternFix> NoisyPatternTightenings = new()
    {
        // Obsolete: Register(GameObject). Modern Register(GameObject, IEventRegistrar) and
        // Registrar.Register("EventId") must not match.
        [("XRL.World.IPart", "Register")] = new(
            @"\.Register\(",
            @"(?<![Rr]egistrar)\.Register\(\s*[^,\)]+\s*\)",
            "Tightened: only single-arg Register(Object) call sites; ignores Registrar.Register(string) and Register(Object, IEventRegistrar)."),
        [("XRL.World.Effect", "Register")] = new(
            @"\.Register\(",
            @"(?<![Rr]egistrar)\.Register\(\s*[^,\)]+\s*\)",
            "Tightened: only single-arg Register(Object) call sites; ignores Registrar.Register(string) and Register(Object, IEventRegistrar)."),
        [("XRL.World.IPart", "Unregister")] = new(
            @"\.Unregister\(",
            @"(?<![Rr]egistrar)\.Unregister\(\s*[^,\)]+\s*\)",
            "Tightened: only single-arg Unregister(Object); ignores two-arg modern form."),
        [("XRL.World.Effect", "Unregister")] = new(
            @"\.Unregister\(",
            @"(?<![Rr]egistrar)\.Unregister\(\s*[^,\)]+\s*\)",
            "Tightened: only single-arg Unregister(Object); ignores two-arg modern form."),

        // Only Action<StringBuilder> overloads are obsolete; string AppendRules is current.
        [("XRL.Extensions", "AppendRules")] = new(
            @"\.AppendRules\(",
            @"\.AppendRules\(\s*(?:delegate\b|\([^;]*?\)\s*=>|[A-Za-z_]\w*\s*=>)",
            "Tightened: only lambda/delegate Action args (Action<StringBuilder> overloads). String AppendRules(...) is current."),

        // IStingerProperties.GetDescription is mutation-specific; override GetDescription is
        // ubiquitous on IPart/attachments. Text scan disabled — rely on CS0618 compile.
        [("XRL.World.Parts.IStingerProperties", "GetDescription")] = new(
            @"\.GetDescription\(",
            @"(?!)",
            "Text scan disabled: collides with ubiquitous IPart.GetDescription overrides. Use CS0618 compile for real IStingerProperties hits."),
        [("XRL.World.Parts.IStingerProperties", "AppendLevelText")] = new(
            @"\.AppendLevelText\(",
            @"(?!)",
            "Text scan disabled: collides with unrelated AppendLevelText overrides. Use CS0618 compile for real IStingerProperties hits."),

        // BodyPart.Save collides with every custom Save(SerializationWriter) wrapper.
        [("XRL.World.Anatomy.BodyPart", "Save")] = new(
            @"\.Save\(",
            @"BodyPart\.Save\(",
            "Tightened: only BodyPart.Save( (matches Load style). Instance part.Save(Writer) needs CS0618 compile."),

        // HistoricEntity/Event.ExpandString collides with mod wrappers like RomanceText.ExpandString.
        [("HistoryKit.HistoricEntity", "ExpandString")] = new(
            @"\.ExpandString\(",
            @"(?i)(?:HistoricEntity|\bentity)\.ExpandString\(",
            "Tightened: only HistoricEntity/entity.ExpandString. Mod wrappers (e.g. RomanceText.ExpandString) ignored."),
        [("HistoryKit.HistoricEvent", "ExpandString")] = new(
            @"\.ExpandString\(",
            @"(?i)(?:HistoricEvent|\bevent)\.ExpandString\(",
            "Tightened: only HistoricEvent/event.ExpandString. Mod wrappers ignored."),

        // GameObject.RegisterPartEvent is NOT obsolete; only IEventRegistrar.RegisterPartEvent is.
        [("XRL.IEventRegistrar", "RegisterPartEvent")] = new(
            @"\.RegisterPartEvent\(",
            @"(?i)Registrar\.RegisterPartEvent\(",
            "Tightened: only Registrar.RegisterPartEvent(...). GameObject.RegisterPartEvent / UnregisterPartEvent are current cross-object APIs."),
        [("XRL.IEventRegistrar", "UnregisterPartEvent")] = new(
            @"\.UnregisterPartEvent\(",
            @"(?i)Registrar\.UnregisterPartEvent\(",
            "Tightened: only Registrar.UnregisterPartEvent(...). GameObject.UnregisterPartEvent is current."),

        // XmlDataHelper.ReadString vs SerializationReader.ReadString (Reader.ReadString in mods).
        [("XRL.XmlDataHelper", "ReadString")] = new(
            @"\.ReadString\(",
            @"(?i)(?<!\bReader)(?<!\bSR)\.ReadString\(",
            "Tightened: skips SerializationReader-style Reader.ReadString / SR.ReadString. XmlDataHelper.ReadString remains flagged."),

        // Obsolete AddAction is the multi-string overload; AddAction(new InventoryAction) is the replacement.
        [("XRL.World.IInventoryActionsEvent", "AddAction")] = new(
            @"\.AddAction\(",
            @"\.AddAction\(\s*(?:\$?@?""|Name\s*:)",
            "Tightened: only string-/Name:-first-arg AddAction (obsolete). AddAction(new InventoryAction) is the replacement."),
        [("XRL.UI.EventParameterGetInventoryActions", "AddAction")] = new(
            @"\.AddAction\(",
            @"\.AddAction\(\s*(?:\$?@?""|Name\s*:)",
            "Tightened: only string-/Name:-first-arg AddAction (obsolete). AddAction(new InventoryAction) is the replacement."),

        // GameObject article/pronoun properties: avoid GameText =subject.The= / =subject.the.name=
        [("XRL.World.GameObject", "the")] = new(@"\.the\b", @"\.the\b(?![.=:#])",
            "Tightened: excludes GameText tokens (=subject.the= / =subject.the.name=)."),
        [("XRL.World.GameObject", "The")] = new(@"\.The\b", @"\.The\b(?![.=:#])",
            "Tightened: excludes GameText tokens (=subject.The= / =subject.The.name=)."),
        [("XRL.World.GameObject", "a")] = new(@"\.a\b", @"\.a\b(?![.=:#])",
            "Tightened: excludes GameText tokens (=subject.a= / =subject.a.name=)."),
        [("XRL.World.GameObject", "A")] = new(@"\.A\b", @"\.A\b(?![.=:#])",
            "Tightened: excludes GameText tokens (=subject.A= / =subject.A.name=)."),
        [("XRL.World.GameObject", "an")] = new(@"\.an\b", @"\.an\b(?![.=:#])",
            "Tightened: excludes GameText tokens."),
        [("XRL.World.GameObject", "An")] = new(@"\.An\b", @"\.An\b(?![.=:#])",
            "Tightened: excludes GameText tokens."),
        [("XRL.World.GameObject", "them")] = new(@"\.them\b", @"\.them\b(?![.=:#])",
            "Tightened: excludes GameText tokens."),
        [("XRL.World.GameObject", "Them")] = new(@"\.Them\b", @"\.Them\b(?![.=:#])",
            "Tightened: excludes GameText tokens."),
        [("XRL.World.GameObject", "its")] = new(@"\.its\b", @"\.its\b(?![.=:#])",
            "Tightened: excludes GameText tokens."),
        [("XRL.World.GameObject", "Its")] = new(@"\.Its\b", @"\.Its\b(?![.=:#])",
            "Tightened: excludes GameText tokens."),
        [("XRL.World.GameObject", "itself")] = new(@"\.itself\b", @"\.itself\b(?![.=:#])",
            "Tightened: excludes GameText tokens."),
        [("XRL.World.GameObject", "Itself")] = new(@"\.Itself\b", @"\.Itself\b(?![.=:#])",
            "Tightened: excludes GameText tokens."),
        [("XRL.World.GameObject", "it")] = new(@"\.it\b", @"\.it\b(?![.=:#])",
            "Tightened: excludes GameText tokens."),
        [("XRL.World.GameObject", "It")] = new(@"\.It\b", @"\.It\b(?![.=:#])",
            "Tightened: excludes GameText tokens."),

        // Loose ".get(" / ".set(" / ".modify(" collide with HotkeySpread.get, Dictionary, etc.
        [("XRL.World.Reputation", "get")] = new(@"\.get\(", @"Reputation\.get\(",
            "Tightened: Reputation.get only (was .get( — HotkeySpread.get false positive)."),
        [("XRL.World.Reputation", "set")] = new(@"\.set\(", @"Reputation\.set\(",
            "Tightened: Reputation.set only."),
        [("XRL.World.Reputation", "modify")] = new(@"\.modify\(", @"Reputation\.modify\(",
            "Tightened: Reputation.modify only."),
    };

    /// <summary>
    /// Older dump refreshes used <c>Type.Member(</c> for instance methods, which almost never
    /// appears in mod source (<c>receiver.Member(</c> does). Rewrite those patterns in place
    /// without touching curated notes / autoFixable flags.
    /// </summary>
    public static int HealInstanceMethodSearchPatterns(ObsoleteDump dump)
    {
        var healed = 0;
        foreach (var e in dump.Entries)
        {
            if (!string.Equals(e.Kind, "Method", StringComparison.OrdinalIgnoreCase))
                continue;
            if (string.IsNullOrEmpty(e.Member) || string.IsNullOrEmpty(e.Type))
                continue;
            if (LooksStaticSignature(e.Signature))
                continue;

            var shortType = ShortTypeName(e.Type);
            var legacy = shortType + @"\." + System.Text.RegularExpressions.Regex.Escape(e.Member) + @"\(";
            var preferred = @"\." + System.Text.RegularExpressions.Regex.Escape(e.Member) + @"\(";
            if (string.Equals(e.SearchPattern, legacy, StringComparison.Ordinal) ||
                string.Equals(e.SearchPattern, shortType + "." + e.Member + "(", StringComparison.Ordinal))
            {
                e.SearchPattern = preferred;
                healed++;
            }
            // Also heal the common "Type\.Member\(" form produced by Regex.Escape on Type.
            else if (e.SearchPattern == System.Text.RegularExpressions.Regex.Escape(shortType) + @"\." +
                     System.Text.RegularExpressions.Regex.Escape(e.Member) + @"\(")
            {
                e.SearchPattern = preferred;
                healed++;
            }
        }
        return healed;
    }

    private static bool LooksStaticSignature(string? signature)
    {
        if (string.IsNullOrWhiteSpace(signature)) return false;
        var s = signature.TrimStart();
        return s.StartsWith("static ", StringComparison.Ordinal);
    }

    private static string ShortTypeName(string type)
    {
        var shortType = type.Contains('.') ? type[(type.LastIndexOf('.') + 1)..] : type;
        var tick = shortType.IndexOf('`');
        if (tick >= 0) shortType = shortType[..tick];
        return shortType;
    }

    private static List<ObsoleteEntry> DedupeAdded(List<DiscoveredMember> added)
    {
        var result = new List<ObsoleteEntry>();
        foreach (var group in added.GroupBy(m => (m.Type, m.Member)))
        {
            var members = group.ToList();
            var first = members[0];
            var distinctMessages = members.Select(m => m.ObsoleteMessage?.Trim() ?? "").Distinct().ToList();
            result.Add(new ObsoleteEntry
            {
                Type = first.Type,
                Member = first.Member,
                Kind = first.Kind,
                Signature = members.Count == 1 ? first.Signature : $"{members.Count} overload(s), e.g. {first.Signature}",
                ObsoleteMessage = string.Join(" | ", distinctMessages),
                SearchPattern = DerivePattern(first),
                NeedsManual = true,
                AutoFixable = false,
                Notes = "Auto-added by a dump refresh; unreviewed - verify replacement signature before promoting to a curated rule.",
            });
        }
        return result;
    }

    public static string DerivePattern(DiscoveredMember m)
    {
        // Prefer call-site patterns that match real mod code (obj.the, DidX(, …), not
        // fully-qualified Type.Member which almost never appears in source.
        var member = m.Member;
        var type = m.Type ?? "";

        if (type.Contains("IComponent") && member is "DidX" or "DidXToY" or "DidXToYWithZ"
            or "XDidY" or "XDidYToZ" or "WDidXToYWithZ")
            return $@"\b{System.Text.RegularExpressions.Regex.Escape(member)}\(";

        if (type.EndsWith("Messaging", StringComparison.Ordinal) &&
            member is "XDidY" or "XDidYToZ" or "WDidXToYWithZ")
            return $@"(?:Messaging\.)?{System.Text.RegularExpressions.Regex.Escape(member)}\(";

        if (type.EndsWith("GameObject", StringComparison.Ordinal) &&
            member is "the" or "The" or "a" or "A" or "an" or "An" or "its" or "Its"
            or "itself" or "Itself" or "It" or "it" or "Them" or "them" or "They" or "they"
            or "Their" or "their" or "tis" or "Tis" or "itis" or "Is" or "are")
            // Exclude GameText =subject.The= / =subject.the.name= tokens.
            return $@"\.{System.Text.RegularExpressions.Regex.Escape(member)}\b(?![.=:#])";

        if (type.EndsWith("GameObject", StringComparison.Ordinal) &&
            member is "Does" or "does" or "GetVerb" or "poss" or "Poss")
            return $@"\.{System.Text.RegularExpressions.Regex.Escape(member)}\(";

        // IEventRegistrar.RegisterPartEvent collides with non-obsolete GameObject.RegisterPartEvent.
        if (type.EndsWith("IEventRegistrar", StringComparison.Ordinal) &&
            member is "RegisterPartEvent" or "UnregisterPartEvent")
            return $@"(?i)Registrar\.{System.Text.RegularExpressions.Regex.Escape(member)}\(";

        // Obsolete Register(GameObject) only — not Register(Object, IEventRegistrar) / Registrar.Register(string).
        if ((type.EndsWith(".IPart", StringComparison.Ordinal) || type.EndsWith(".Effect", StringComparison.Ordinal) ||
             type is "XRL.World.IPart" or "XRL.World.Effect") &&
            member is "Register" or "Unregister")
            return $@"(?<![Rr]egistrar)\.{System.Text.RegularExpressions.Regex.Escape(member)}\(\s*[^,\)]+\s*\)";

        // BodyPart.Save is obsolete; bare .Save( matches every serialization wrapper.
        if (type.EndsWith("BodyPart", StringComparison.Ordinal) && member == "Save")
            return @"BodyPart\.Save\(";

        // HistoricEntity/Event.ExpandString vs mod wrappers named ExpandString.
        if (type.EndsWith("HistoricEntity", StringComparison.Ordinal) && member == "ExpandString")
            return @"(?i)(?:HistoricEntity|\bentity)\.ExpandString\(";
        if (type.EndsWith("HistoricEvent", StringComparison.Ordinal) && member == "ExpandString")
            return @"(?i)(?:HistoricEvent|\bevent)\.ExpandString\(";

        if (member is "Capitalize" or "CapitalizeExceptFormatting")
            return $@"\.{System.Text.RegularExpressions.Regex.Escape(member)}\(";

        var shortType = ShortTypeName(type);

        // Instance methods: mods call receiver.Member(, almost never Type.Member(.
        // Signature from FormatMethodSignature prefixes static methods with "static ".
        if (string.Equals(m.Kind, "Method", StringComparison.OrdinalIgnoreCase) &&
            !LooksStaticSignature(m.Signature))
        {
            return $@"\.{System.Text.RegularExpressions.Regex.Escape(member)}\(";
        }

        return m.Kind == "Method"
            ? $@"{System.Text.RegularExpressions.Regex.Escape(shortType)}\.{System.Text.RegularExpressions.Regex.Escape(member)}\("
            : $@"{System.Text.RegularExpressions.Regex.Escape(shortType)}\.{System.Text.RegularExpressions.Regex.Escape(member)}\b";
    }

    /// <summary>Backs up the existing dump file (if present) then writes the merged dump.
    /// Also stamps game FileVersion meta and refreshes <c>data/by-version/{version}/</c>
    /// (dump + curated rules). Returns the backup path, or null if there was nothing to back up.</summary>
    public static string? SaveWithBackup(string dumpPath, string backupDir, ObsoleteDump merged,
        string? dataDir = null, string? managedDir = null)
    {
        string? backupPath = null;
        if (File.Exists(dumpPath))
        {
            backupPath = DumpStore.Backup(dumpPath, backupDir);
        }
        dataDir ??= Path.GetDirectoryName(Path.GetFullPath(dumpPath));
        if (!string.IsNullOrEmpty(dataDir))
        {
            DumpVersionControl.AfterDumpSaved(dataDir, merged, managedDir);
        }
        else
        {
            DumpStore.SaveDump(dumpPath, merged);
        }
        return backupPath;
    }

    /// <summary>
    /// Writes a markdown research report (added / changed / removed) next to other tool reports.
    /// Used by the GUI "Update ApiMigrator" flow so dump refreshes are reviewable later.
    /// </summary>
    public static string WriteResearchReport(RefreshPreview preview, string reportPath, string dumpPath)
    {
        var dir = Path.GetDirectoryName(Path.GetFullPath(reportPath));
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# ApiMigrator DLL Research");
        sb.AppendLine();
        sb.AppendLine($"- Captured: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"- Dump target: `{dumpPath}`");
        sb.AppendLine($"- Types scanned: {preview.Scan.TypesScanned}");
        sb.AppendLine($"- Obsolete members found: {preview.Scan.Members.Count}");
        sb.AppendLine();

        if (preview.Diff is { } diff)
        {
            sb.AppendLine("## Summary");
            sb.AppendLine();
            sb.AppendLine($"| Unchanged | Added | Removed | Message changed |");
            sb.AppendLine($"|----------:|------:|--------:|----------------:|");
            sb.AppendLine($"| {diff.UnchangedCount} | {diff.Added.Count} | {diff.Removed.Count} | {diff.MessageChanged.Count} |");
            sb.AppendLine();

            if (diff.Added.Count > 0)
            {
                sb.AppendLine("## Added");
                sb.AppendLine();
                foreach (var m in diff.Added)
                    sb.AppendLine($"- `{m.Type}.{m.Member}` — {m.ObsoleteMessage}");
                sb.AppendLine();
            }

            if (diff.MessageChanged.Count > 0)
            {
                sb.AppendLine("## Message changed");
                sb.AppendLine();
                foreach (var (oldE, newM) in diff.MessageChanged)
                {
                    sb.AppendLine($"- `{oldE.Type}.{oldE.Member}`");
                    sb.AppendLine($"  - was: {oldE.ObsoleteMessage}");
                    sb.AppendLine($"  - now: {newM.ObsoleteMessage}");
                }
                sb.AppendLine();
            }

            if (diff.Removed.Count > 0)
            {
                sb.AppendLine("## Removed (no longer obsolete / gone from Managed)");
                sb.AppendLine();
                foreach (var e in diff.Removed)
                    sb.AppendLine($"- `{e.Type}.{e.Member}` — {e.ObsoleteMessage}");
                sb.AppendLine();
            }
        }
        else
        {
            sb.AppendLine("No prior dump — this refresh creates a new obsolete map.");
            sb.AppendLine();
        }

        if (preview.Scan.Warnings.Count > 0)
        {
            sb.AppendLine("## Scan warnings");
            sb.AppendLine();
            foreach (var w in preview.Scan.Warnings)
                sb.AppendLine($"- {w}");
            sb.AppendLine();
        }

        sb.AppendLine("## What this updates");
        sb.AppendLine();
        sb.AppendLine("Saving the merged dump updates **ApiMigrator** itself: Migrate, CS0618 Resolve, and Obsolete Map all read `obsolete_api_dump.json`. Curated autofix regexes in `curated_rewrite_rules.json` stay hand-maintained — new dump entries are flagged `needsManual` until promoted to a curated rule.");

        File.WriteAllText(reportPath, sb.ToString());
        return reportPath;
    }
}
